Repository prgrms-be-devcourse/springboot-basic, pull requests merged in 2022-12, with the labels that each got.

#620 [3기-C] 이택승 SpringBoot weekly Mission 3주차 (1차) 제출합니다.
  build.gradle
  src/main/java/org/prgrms/kdt/app/VoucherCommandLineApp.java
  src/main/java/org/prgrms/kdt/app/VoucherCommandLineAppStatus.java
  src/main/java/org/prgrms/kdt/command/VoucherExecutor.java
  src/main/java/org/prgrms/kdt/customer/JdbcCustomerManager.java
  src/main/java/org/prgrms/kdt/exception/ErrorCode.java
  src/main/java/org/prgrms/kdt/exception/ErrorResponse.java
  src/main/java/org/prgrms/kdt/exception/GlobalExceptionHandler.java
  src/main/java/org/prgrms/kdt/voucher/VoucherController.java
  src/main/resources/application.yml
  src/main/resources/logback.xml
  src/main/resources/static/css/bootstrap.min.css
  src/main/resources/static/image/trash.svg
  src/main/resources/templates/app/addForm.html
  src/main/resources/templates/app/voucher.html
  src/main/resources/templates/app/vouchers.html
  src/main/resources/templates/error/404.html
  src/main/resources/templates/error/500.html
  src/test/java/org/prgrms/kdt/JdbcConfig.java
Labels: 🔥 매운맛, Team-Allen

#625 [3기-C] 김선호 SpringBoot Part3 Weekly Mission 제출합니다. (1차)
  .gitignore
  README.md
  build.gradle
  src/main/java/prgms/vouchermanagementapp/configuration/FileConfig.java
  src/main/java/prgms/vouchermanagementapp/controller/CommandExecutor.java
  src/main/java/prgms/vouchermanagementapp/controller/CustomerController.java
  src/main/java/prgms/vouchermanagementapp/controller/MainController.java
  src/main/java/prgms/vouchermanagementapp/controller/WebVoucherController.java
  src/main/java/prgms/vouchermanagementapp/domain/FileVoucherRecord.java
  src/main/java/prgms/vouchermanagementapp/domain/FixedAmountVoucher.java
  src/main/java/prgms/vouchermanagementapp/domain/MemoryVoucherRecord.java
  src/main/java/prgms/vouchermanagementapp/domain/PercentDiscountVoucher.java
  src/main/java/prgms/vouchermanagementapp/domain/Voucher.java
  src/main/java/prgms/vouchermanagementapp/domain/VoucherEntity.java
  src/main/java/prgms/vouchermanagementapp/domain/VoucherRecord.java
  src/main/java/prgms/vouchermanagementapp/domain/VoucherType.java
  src/main/java/prgms/vouchermanagementapp/domain/dto/VoucherViewDTO.java
  src/main/java/prgms/vouchermanagementapp/domain/value/Amount.java
  src/main/java/prgms/vouchermanagementapp/domain/value/FixedDiscountLevel.java
  src/main/java/prgms/vouchermanagementapp/domain/value/Ratio.java
  src/main/java/prgms/vouchermanagementapp/repository/FileVoucherRepository.java
  src/main/java/prgms/vouchermanagementapp/repository/FileVouchers.java
  src/main/java/prgms/vouchermanagementapp/repository/JdbcCustomerRepository.java
  src/main/java/prgms/vouchermanagementapp/repository/JdbcVoucherRepository.java
  src/main/java/prgms/vouchermanagementapp/repository/JdbcVouchers.java
  src/main/java/prgms/vouchermanagementapp/repository/MemoryVoucherRepository.java
  src/main/java/prgms/vouchermanagementapp/repository/MemoryVouchers.java
  src/main/java/prgms/vouchermanagementapp/repository/VoucherRepository.java
  src/main/java/prgms/vouchermanagementapp/repository/Vouchers.java
  src/main/java/prgms/vouchermanagementapp/repository/util/EntityMapper.java
  src/main/java/prgms/vouchermanagementapp/repository/util/FileManager.java
  src/main/java/prgms/vouchermanagementapp/repository/util/VoucherContentConverter.java
  src/main/java/prgms/vouchermanagementapp/repository/util/VoucherContentsConverter.java
  src/main/java/prgms/vouchermanagementapp/service/CustomerManager.java
  src/main/java/prgms/vouchermanagementapp/service/CustomerService.java
  src/main/java/prgms/vouchermanagementapp/service/VoucherCreationFactory.java
  src/main/java/prgms/vouchermanagementapp/service/VoucherFactory.java
  src/main/java/prgms/vouchermanagementapp/service/VoucherManager.java
  src/main/java/prgms/vouchermanagementapp/service/VoucherService.java
  src/main/java/prgms/vouchermanagementapp/view/FileManager.java
  src/main/java/prgms/vouchermanagementapp/view/IoManager.java
  src/main/java/prgms/vouchermanagementapp/view/Writer.java
  src/main/resources/application.properties
  src/main/resources/application.yaml
  src/main/resources/customer_blacklist.csv
  src/main/resources/static/css/bootstrap.min.css
  src/main/resources/static/index.html
  src/main/resources/templates/css/bootstrap.min.css
  src/main/resources/templates/voucher/voucherAddForm.html
  src/main/resources/templates/voucher/voucherDetail.html
  src/main/resources/templates/voucher/voucherEditForm.html
  src/main/resources/templates/voucher/voucherList.html
  src/test/java/prgms/vouchermanagementapp/domain/FixedAmountVoucherTest.java
  src/test/java/prgms/vouchermanagementapp/domain/value/AmountTest.java
  src/test/java/prgms/vouchermanagementapp/domain/value/RatioTest.java
  src/test/java/prgms/vouchermanagementapp/repository/JdbcVoucherRepositoryTest.java
  src/test/java/prgms/vouchermanagementapp/repository/JdbcVouchersTest.java
  src/test/java/prgms/vouchermanagementapp/service/CustomerServiceTest.java
  src/test/resources/schema.sql
Labels: 🔥 매운맛, Team-Allen

#597 [3기-C] 김태희 SpringBoot Part2 Weekly Mission 제출합니다.
  .gitignore
  HELP.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/programmers/voucher/VoucherApplication.java
  src/main/java/com/programmers/voucher/controller/CustomerController.java
  src/main/java/com/programmers/voucher/controller/VoucherController.java
  src/main/java/com/programmers/voucher/controller/VoucherProgram.java
  src/main/java/com/programmers/voucher/controller/dto/CustomerCreateRequest.java
  src/main/java/com/programmers/voucher/controller/dto/VoucherAssignRequest.java
  src/main/java/com/programmers/voucher/controller/dto/VoucherCreateRequest.java
  src/main/java/com/programmers/voucher/controller/dto/VoucherUpdateRequest.java
  src/main/java/com/programmers/voucher/io/CommandType.java
  src/main/java/com/programmers/voucher/io/Input.java
  src/main/java/com/programmers/voucher/io/Message.java
  src/main/java/com/programmers/voucher/io/Output.java
  src/main/java/com/programmers/voucher/model/customer/Customer.java
  src/main/java/com/programmers/voucher/model/voucher/FixedAmountVoucher.java
  src/main/java/com/programmers/voucher/model/voucher/PercentDiscountVoucher.java
  src/main/java/com/programmers/voucher/model/voucher/Voucher.java
  src/main/java/com/programmers/voucher/model/voucher/VoucherType.java
  src/main/java/com/programmers/voucher/repository/customer/CustomerJdbcRepository.java
  src/main/java/com/programmers/voucher/repository/customer/CustomerRepository.java
  src/main/java/com/programmers/voucher/repository/voucher/VoucherJdbcRepository.java
  src/main/java/com/programmers/voucher/repository/voucher/VoucherRepository.java
  src/main/java/com/programmers/voucher/service/CustomerService.java
  src/main/java/com/programmers/voucher/service/VoucherService.java
  src/main/java/com/programmers/voucher/utils/JdbcParamMapper.java
  src/main/resources/META-INF/MANIFEST.MF
  src/main/resources/application.yaml
  src/main/resources/logback.xml
  src/main/resources/schema.sql
  src/test/java/com/programmers/voucher/MysqlTestContainer.java
  src/test/java/com/programmers/voucher/VoucherApplicationTests.java
  src/test/java/com/programmers/voucher/model/voucher/FixedAmountVoucherTest.java
  src/test/java/com/programmers/voucher/model/voucher/PercentDiscountVoucherTest.java
  src/test/java/com/programmers/voucher/model/voucher/VoucherTypeTest.java
  src/test/java/com/programmers/voucher/repository/customer/CustomerRepositoryTest.java
  src/test/java/com/programmers/voucher/repository/voucher/VoucherRepositoryTest.java
  src/test/resources/application.yaml
  src/test/resources/logback-test.xml
Labels: 🔥 매운맛, Team-Hoon

#612 [3기-C] 김주형 SpringBoot Part2 Weekly Mission 2주차 제출합니다.
  pom.xml
  src/main/java/org/prgrms/springbootbasic/Console.java
  src/main/java/org/prgrms/springbootbasic/CustomerInputDto.java
  src/main/java/org/prgrms/springbootbasic/NotificationProperties.java
  src/main/java/org/prgrms/springbootbasic/SpringbootBasicApplication.java
  src/main/java/org/prgrms/springbootbasic/configuration/FactoryConfiguration.java
  src/main/java/org/prgrms/springbootbasic/dto/Response.java
  src/main/java/org/prgrms/springbootbasic/entity/Customer.java
  src/main/java/org/prgrms/springbootbasic/entity/User.java
  src/main/java/org/prgrms/springbootbasic/entity/voucher/FixedAmountVoucher.java
  src/main/java/org/prgrms/springbootbasic/entity/voucher/PercentAmountVoucher.java
  src/main/java/org/prgrms/springbootbasic/entity/voucher/Voucher.java
  src/main/java/org/prgrms/springbootbasic/factory/FixedAmountVoucherFactory.java
  src/main/java/org/prgrms/springbootbasic/factory/PercentAmountVoucherFactory.java
  src/main/java/org/prgrms/springbootbasic/factory/VoucherFactory.java
  src/main/java/org/prgrms/springbootbasic/processor/BlackListManagementProcessor.java
  src/main/java/org/prgrms/springbootbasic/processor/CustomerProcessor.java
  src/main/java/org/prgrms/springbootbasic/processor/Processor.java
  src/main/java/org/prgrms/springbootbasic/processor/VoucherProcessor.java
  src/main/java/org/prgrms/springbootbasic/repository/BlackListRepository.java
  src/main/java/org/prgrms/springbootbasic/repository/CustomerRepository.java
  src/main/java/org/prgrms/springbootbasic/repository/CustomerRepositoryImpl.java
  src/main/java/org/prgrms/springbootbasic/repository/DbVoucherRepository.java
  src/main/java/org/prgrms/springbootbasic/repository/FileBlackListRepository.java
  src/main/java/org/prgrms/springbootbasic/repository/FileVoucherRepository.java
  src/main/java/org/prgrms/springbootbasic/repository/InMemoryVoucherRepository.java
  src/main/java/org/prgrms/springbootbasic/repository/VoucherRepository.java
  src/main/java/org/prgrms/springbootbasic/service/BlackListManagementService.java
  src/main/java/org/prgrms/springbootbasic/service/CustomerService.java
  src/main/java/org/prgrms/springbootbasic/service/VoucherService.java
  src/main/java/org/prgrms/springbootbasic/type/MethodType.java
  src/main/java/org/prgrms/springbootbasic/type/ServiceType.java
  src/main/java/org/prgrms/springbootbasic/type/VoucherType.java
  src/main/java/org/prgrms/springbootbasic/util/CommandLineInput.java
  src/main/java/org/prgrms/springbootbasic/util/UUIDUtil.java
  src/main/resources/application.yaml
  src/main/resources/blackListRepository.csv
  src/main/resources/fileVoucherRepository.csv
  src/test/java/org/prgrms/springbootbasic/factory/FixedAmountVoucherFactoryTest.java
  src/test/java/org/prgrms/springbootbasic/factory/PercentAmountVoucherFactoryTest.java
  src/test/java/org/prgrms/springbootbasic/repository/CustomerRepositoryImplTest.java
  src/test/java/org/prgrms/springbootbasic/repository/DbVoucherRepositoryTest.java
  src/test/java/org/prgrms/springbootbasic/repository/FileVoucherRepositoryTest.java
  src/test/java/org/prgrms/springbootbasic/repository/InMemoryVoucherRepositoryTest.java
  src/test/java/org/prgrms/springbootbasic/service/CustomerServiceTest.java
  src/test/java/org/prgrms/springbootbasic/service/VoucherServiceTest.java
  src/test/java/org/prgrms/springbootbasic/type/MethodTypeTest.java
  src/test/java/org/prgrms/springbootbasic/type/ServiceTypeTest.java
  src/test/java/org/prgrms/springbootbasic/type/VoucherTypeTest.java
  src/test/resources/fileVoucherRepository.csv
  src/test/resources/schema.sql
Labels: 🔥 매운맛, Team-Hoon

#609 [3기-C] 김보섭 스프링 부트 2주차 과제 풀리퀘스트입니다
  .gitignore
  .idea/.gitignore
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/org/programmers/program/SpringVoucherApplication.java
  src/main/java/org/programmers/program/VoucherProgram.java
  src/main/java/org/programmers/program/config/VoucherProgramConfig.java
  src/main/java/org/programmers/program/customer/controller/CustomerDto.java
  src/main/java/org/programmers/program/customer/model/Customer.java
  src/main/java/org/programmers/program/customer/repository/CustomerRepository.java
  src/main/java/org/programmers/program/customer/repository/NameJdbcCustomerRepository.java
  src/main/java/org/programmers/program/customer/service/CustomerService.java
  src/main/java/org/programmers/program/instruction/model/Instruction.java
  src/main/java/org/programmers/program/io/Input.java
  src/main/java/org/programmers/program/io/Message.java
  src/main/java/org/programmers/program/io/Output.java
  src/main/java/org/programmers/program/voucher/controller/VoucherController.java
  src/main/java/org/programmers/program/voucher/controller/VoucherDto.java
  src/main/java/org/programmers/program/voucher/controller/api/VoucherRestController.java
  src/main/java/org/programmers/program/voucher/model/FixedAmountVoucher.java
  src/main/java/org/programmers/program/voucher/model/PercentDiscountVoucher.java
  src/main/java/org/programmers/program/voucher/model/Voucher.java
  src/main/java/org/programmers/program/voucher/model/VoucherType.java
  src/main/java/org/programmers/program/voucher/repository/MemoryVoucherRepository.java
  src/main/java/org/programmers/program/voucher/repository/NamedJdbcVoucherRepository.java
  src/main/java/org/programmers/program/voucher/repository/VoucherRepository.java
  src/main/java/org/programmers/program/voucher/service/VoucherService.java
  src/main/java/org/programmers/program/voucher/validator/VoucherValidator.java
  src/main/resources/META-INF/MANIFEST.MF
  src/main/resources/application.yaml
  src/main/resources/customerSchema.sql
  src/main/resources/images/Class_Diagram.png
  src/main/resources/images/VoucherProgram.png
  src/main/resources/images/VoucherService.png
  src/main/resources/images/VoucherType.png
  src/main/resources/logback.xml
  src/main/resources/templates/newVouchers.html
  src/main/resources/templates/voucher-detail.html
  src/main/resources/templates/voucher-list.html
  src/main/resources/voucherSchema.sql
  src/test/java/org/programmers/program/customer/repository/NameJdbcCustomerRepositoryTest.java
  src/test/java/org/programmers/program/customer/service/CustomerServiceTest.java
  src/test/java/org/programmers/program/io/IOTest.java
  src/test/java/org/programmers/program/voucher/model/VoucherTest.java
  src/test/java/org/programmers/program/voucher/repository/MemoryVoucherRepositoryTest.java
  src/test/java/org/programmers/program/voucher/repository/NamedJdbcVoucherRepositoryTest.java
  src/test/java/org/programmers/program/voucher/service/VoucherServiceTest.java
  src/test/java/org/programmers/program/voucher/validator/VoucherValidatorTest.java
Labels: 🔥 매운맛, Team-Hoon

#530 [3기-C] 권성준 SpringBoot Part1 Weekly Mission 제출합니다.
  .gitignore
  README.md
  build.gradle
  settings.gradle
  src/main/java/com/programmers/voucher/VoucherApplication.java
  src/main/java/com/programmers/voucher/config/AppConfig.java
  src/main/java/com/programmers/voucher/controller/Command.java
  src/main/java/com/programmers/voucher/controller/ControllerPower.java
  src/main/java/com/programmers/voucher/controller/Message.java
  src/main/java/com/programmers/voucher/controller/QuadFunction.java
  src/main/java/com/programmers/voucher/controller/VoucherController.java
  src/main/java/com/programmers/voucher/domain/customer/model/Customer.java
  src/main/java/com/programmers/voucher/domain/customer/model/CustomerType.java
  src/main/java/com/programmers/voucher/domain/customer/repository/CustomerRepository.java
  src/main/java/com/programmers/voucher/domain/customer/repository/FileCustomerRepository.java
  src/main/java/com/programmers/voucher/domain/customer/service/CustomerService.java
  src/main/java/com/programmers/voucher/domain/voucher/model/FixedDiscountVoucher.java
  src/main/java/com/programmers/voucher/domain/voucher/model/PercentDiscountVoucher.java
  src/main/java/com/programmers/voucher/domain/voucher/model/Voucher.java
  src/main/java/com/programmers/voucher/domain/voucher/model/VoucherType.java
  src/main/java/com/programmers/voucher/domain/voucher/repository/FileVoucherRepository.java
  src/main/java/com/programmers/voucher/domain/voucher/repository/MemoryVoucherRepository.java
  src/main/java/com/programmers/voucher/domain/voucher/repository/VoucherRepository.java
  src/main/java/com/programmers/voucher/domain/voucher/service/VoucherService.java
  src/main/java/com/programmers/voucher/domain/voucher/util/VoucherFactory.java
  src/main/java/com/programmers/voucher/exception/EmptyBufferException.java
  src/main/java/com/programmers/voucher/exception/ExceptionMessage.java
  src/main/java/com/programmers/voucher/exception/VoucherNotFoundException.java
  src/main/java/com/programmers/voucher/io/ConsoleInput.java
  src/main/java/com/programmers/voucher/io/ConsoleOutput.java
  src/main/java/com/programmers/voucher/io/Input.java
  src/main/java/com/programmers/voucher/io/Output.java
  src/main/resources/application.yaml
  src/main/resources/customer_blacklist.csv
  src/main/resources/error/log_error.2022-11-06.log
  src/main/resources/logback.xml
  src/main/resources/voucher.csv
  src/main/resources/voucher_test.csv
  src/test/java/com/programmers/voucher/domain/voucher/repository/FileVoucherRepositoryTest.java
  src/test/java/com/programmers/voucher/domain/voucher/repository/MemoryVoucherRepositoryTest.java
  src/test/java/com/programmers/voucher/domain/voucher/service/VoucherServiceTest.java
  src/test/resources/application.yaml
Labels: 🔥 매운맛, Team-Marco

#532 [3기-C] 이수영 SpringBoot Part1 Weekly Mission 제출합니다.
  .gitignore
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/org/prgrms/kdt/Application.java
  src/main/java/org/prgrms/kdt/dao/entity/BlackList.java
  src/main/java/org/prgrms/kdt/dao/entity/voucher/Voucher.java
  src/main/java/org/prgrms/kdt/dao/entity/voucher/VoucherFactory.java
  src/main/java/org/prgrms/kdt/dao/entity/voucher/VoucherType.java
  src/main/java/org/prgrms/kdt/dao/repository/voucher/FileVoucherRepository.java
  src/main/java/org/prgrms/kdt/dao/repository/voucher/MemoryVoucherRepository.java
  src/main/java/org/prgrms/kdt/dao/repository/voucher/VoucherRepository.java
  src/main/java/org/prgrms/kdt/exception/NotDevelopException.java
  src/main/java/org/prgrms/kdt/exception/io/WrongInputDataException.java
  src/main/java/org/prgrms/kdt/exception/io/WrongOutputDataException.java
  src/main/java/org/prgrms/kdt/exception/repository/NotPresentInRepositoryException.java
  src/main/java/org/prgrms/kdt/presentation/controller/CommandLineController.java
  src/main/java/org/prgrms/kdt/presentation/controller/CommandType.java
  src/main/java/org/prgrms/kdt/presentation/io/ConsoleIO.java
  src/main/java/org/prgrms/kdt/service/BlackListService.java
  src/main/java/org/prgrms/kdt/service/VoucherService.java
  src/main/java/org/prgrms/kdt/util/ValidatorUtil.java
  src/main/resources/application.properties
  src/main/resources/application.yaml
  src/main/resources/blacklist.csv
  src/main/resources/logback-spring.xml
  src/main/resources/voucher_list.txt
  src/test/java/org/prgrms/kdt/repository/voucher/FileVoucherRepositoryTest.java
  src/test/java/org/prgrms/kdt/repository/voucher/MemoryVoucherRepositoryTest.java
  src/test/java/org/prgrms/kdt/service/VoucherServiceTest.java
  src/test/java/org/prgrms/kdt/voucher/ValidatorUtilTest.java
  src/test/resources/application.yaml
  src/test/resources/testFileRepository.txt
Labels: 🔥 매운맛, Team-Marco

#638 [3기-C] 김환 SpringBoot Part3 Weekly Mission 제출합니다.(2차)
  src/main/java/com/prgrms/springbootbasic/common/exception/GlobalExceptionHandler.java
  src/main/java/com/prgrms/springbootbasic/voucher/controller/VoucherController.java
  src/main/java/com/prgrms/springbootbasic/voucher/controller/VoucherRestController.java
Labels: 🔥 매운맛, Team-Allen

#633 [3기-C] 고승원 SpringBoot Part3 Weekly Mission 3주차 제출합니다.
  build.gradle
  src/main/java/com/programmers/assignment/voucher/CliApplication.java
  src/main/java/com/programmers/assignment/voucher/VoucherApplication.java
  src/main/java/com/programmers/assignment/voucher/common/exceptions/GlobalExceptionHandler.java
  src/main/java/com/programmers/assignment/voucher/common/response/CommonResponse.java
  src/main/java/com/programmers/assignment/voucher/common/response/ResponseMessage.java
  src/main/java/com/programmers/assignment/voucher/engine/controller/CustomerApiController.java
  src/main/java/com/programmers/assignment/voucher/engine/controller/CustomerController.java
  src/main/java/com/programmers/assignment/voucher/engine/controller/HomeController.java
  src/main/java/com/programmers/assignment/voucher/engine/controller/MenuController.java
  src/main/java/com/programmers/assignment/voucher/engine/controller/VoucherApiController.java
  src/main/java/com/programmers/assignment/voucher/engine/controller/VoucherController.java
  src/main/java/com/programmers/assignment/voucher/engine/io/ConsoleInput.java
  src/main/java/com/programmers/assignment/voucher/engine/io/ConsoleOutput.java
  src/main/java/com/programmers/assignment/voucher/engine/model/Customer.java
  src/main/java/com/programmers/assignment/voucher/engine/model/Voucher.java
  src/main/java/com/programmers/assignment/voucher/engine/repository/CustomerRepository.java
  src/main/java/com/programmers/assignment/voucher/engine/repository/JdbcCustomerRepository.java
  src/main/java/com/programmers/assignment/voucher/engine/service/CustomerService.java
  src/main/java/com/programmers/assignment/voucher/engine/service/MenuService.java
  src/main/java/com/programmers/assignment/voucher/engine/service/VoucherService.java
  src/main/java/com/programmers/assignment/voucher/util/domain/Menu.java
  src/main/java/com/programmers/assignment/voucher/util/domain/VoucherVariable.java
  src/main/resources/static/index.html
  src/main/resources/templates/customer-details.html
  src/main/resources/templates/customer-form.html
  src/main/resources/templates/customer.html
  src/main/resources/templates/home.html
  src/main/resources/templates/voucher-details.html
  src/main/resources/templates/voucher-form.html
  src/main/resources/templates/voucher.html
  src/test/java/com/programmers/assignment/voucher/engine/repository/JdbcCustomerRepositoryTest.java
Labels: 🔥 매운맛, Team-Hoon
