Repository prgrms-be-devcourse/springboot-basic, pull requests merged in 2023-08, with the labels that each got.

#859 [4기] 강병곤 SpringBoot Part3 Weekly Mission 두번째 PR 제출합니다.
  pom.xml
  src/main/java/org/prgrms/kdt/KdtApplication.java
  src/main/java/org/prgrms/kdt/common/codes/ErrorCode.java
  src/main/java/org/prgrms/kdt/common/exception/GlobalExceptionHandler.java
  src/main/java/org/prgrms/kdt/common/exception/VoucherRuntimeException.java
  src/main/java/org/prgrms/kdt/common/response/ErrorResponse.java
  src/main/java/org/prgrms/kdt/controller/MainController.java
  src/main/java/org/prgrms/kdt/controller/VoucherAPIController.java
  src/main/java/org/prgrms/kdt/controller/VoucherController.java
  src/main/java/org/prgrms/kdt/model/domain/Voucher.java
  src/main/java/org/prgrms/kdt/model/dto/VoucherRequest.java
  src/main/java/org/prgrms/kdt/model/dto/VoucherResponse.java
  src/main/java/org/prgrms/kdt/model/entity/CustomerEntity.java
  src/main/java/org/prgrms/kdt/model/entity/VoucherEntity.java
  src/main/java/org/prgrms/kdt/model/repository/CustomerRepository.java
  src/main/java/org/prgrms/kdt/model/repository/VoucherRepository.java
  src/main/java/org/prgrms/kdt/model/repository/file/FileVoucherRepository.java
  src/main/java/org/prgrms/kdt/model/repository/inmemory/InMemoryVoucherRepository.java
  src/main/java/org/prgrms/kdt/model/repository/jdbc/CustomerJdbcRepository.java
  src/main/java/org/prgrms/kdt/model/repository/jdbc/VoucherJdbcRepository.java
  src/main/java/org/prgrms/kdt/service/BusinessService.java
  src/main/java/org/prgrms/kdt/service/VoucherService.java
  src/main/java/org/prgrms/kdt/util/FileIO.java
  src/main/java/org/prgrms/kdt/util/VoucherFactory.java
  src/main/java/org/prgrms/kdt/util/VoucherMapper.java
  src/main/java/org/prgrms/kdt/view/ConsoleView.java
  src/main/java/org/prgrms/kdt/view/OutputView.java
  src/main/resources/templates/new-vouchers.html
  src/main/resources/templates/vouchers.html
  src/test/java/org/prgrms/kdt/controller/VoucherAPIControllerTest.java
  src/test/java/org/prgrms/kdt/model/repository/file/FileVoucherRepositoryTest.java
  src/test/java/org/prgrms/kdt/model/repository/inmemory/InMemoryVoucherRepositoryTestEntity.java
  src/test/java/org/prgrms/kdt/model/repository/jdbc/CustomerJdbcRepositoryTest.java
  src/test/java/org/prgrms/kdt/model/repository/jdbc/VoucherJdbcRepositoryTest.java
  src/test/java/org/prgrms/kdt/service/VoucherEntityServiceTest.java
Labels: 🔥 매운맛, Team-HeeHee

#838 [4기 - 신범철] SpringBoot Part2 Weekly Mission 두 번째 PR 제출합니다
  .gitignore
  README.md
  build.gradle
  docs/week1/img.png
  docs/week1/img_1.png
  docs/week1/week1.md
  docs/week2/img1-1.png
  docs/week2/img1-2.png
  docs/week2/img2-1.png
  docs/week2/img2-2.png
  src/main/java/org/prgrms/kdtspringdemo/CommandLineApplication.java
  src/main/java/org/prgrms/kdtspringdemo/customer/constant/CustomerCommand.java
  src/main/java/org/prgrms/kdtspringdemo/customer/exception/CustomerException.java
  src/main/java/org/prgrms/kdtspringdemo/customer/exception/CustomerExceptionMessage.java
  src/main/java/org/prgrms/kdtspringdemo/customer/model/dto/CustomerResponse.java
  src/main/java/org/prgrms/kdtspringdemo/customer/model/entity/Customer.java
  src/main/java/org/prgrms/kdtspringdemo/customer/repository/CustomerRepository.java
  src/main/java/org/prgrms/kdtspringdemo/customer/repository/JdbcCustomerRepository.java
  src/main/java/org/prgrms/kdtspringdemo/customer/service/CustomerService.java
  src/main/java/org/prgrms/kdtspringdemo/util/JdbcUtils.java
  src/main/java/org/prgrms/kdtspringdemo/util/queryBuilder/constant/Column.java
  src/main/java/org/prgrms/kdtspringdemo/util/queryBuilder/constant/Symbol.java
  src/main/java/org/prgrms/kdtspringdemo/util/queryBuilder/constant/Table.java
  src/main/java/org/prgrms/kdtspringdemo/util/queryBuilder/query/DeleteBuilder.java
  src/main/java/org/prgrms/kdtspringdemo/util/queryBuilder/query/InsertBuilder.java
  src/main/java/org/prgrms/kdtspringdemo/util/queryBuilder/query/SelectBuilder.java
  src/main/java/org/prgrms/kdtspringdemo/util/queryBuilder/query/UpdateBuilder.java
  src/main/java/org/prgrms/kdtspringdemo/util/queryBuilder/query/WhereBuilder.java
  src/main/java/org/prgrms/kdtspringdemo/view/console/Console.java
  src/main/java/org/prgrms/kdtspringdemo/view/console/Message.java
  src/main/java/org/prgrms/kdtspringdemo/view/console/VoucherConsole.java
  src/main/java/org/prgrms/kdtspringdemo/view/constant/MainCommandType.java
  src/main/java/org/prgrms/kdtspringdemo/voucher/constant/VoucherCommand.java
  src/main/java/org/prgrms/kdtspringdemo/voucher/constant/VoucherType.java
  src/main/java/org/prgrms/kdtspringdemo/voucher/exception/VoucherExceptionMessage.java
  src/main/java/org/prgrms/kdtspringdemo/voucher/exception/VoucherIdNotFoundException.java
  src/main/java/org/prgrms/kdtspringdemo/voucher/model/dto/VoucherDto.java
  src/main/java/org/prgrms/kdtspringdemo/voucher/model/dto/VoucherResponse.java
  src/main/java/org/prgrms/kdtspringdemo/voucher/model/entity/FixedAmountVoucher.java
  src/main/java/org/prgrms/kdtspringdemo/voucher/model/entity/PercentAmountVoucher.java
  src/main/java/org/prgrms/kdtspringdemo/voucher/model/entity/Voucher.java
  src/main/java/org/prgrms/kdtspringdemo/voucher/ropository/JdbcVoucherRepository.java
  src/main/java/org/prgrms/kdtspringdemo/voucher/ropository/MemoryVoucherRepository.java
  src/main/java/org/prgrms/kdtspringdemo/voucher/ropository/VoucherRepository.java
  src/main/java/org/prgrms/kdtspringdemo/voucher/service/VoucherService.java
  src/main/java/org/prgrms/kdtspringdemo/voucher/service/VoucherServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/application.yaml
  src/test/java/org/prgrms/kdtspringdemo/voucher/ropository/JdbcVoucherRepositoryTest.java
  src/test/java/org/prgrms/kdtspringdemo/voucher/service/VoucherServiceTest.java
Labels: 🔥 매운맛, Team-Kyu

#829 [4기 - 문희조] SpringBoot Part2 Weekly Mission 제출합니다.
  build.gradle
  docs/README.md
  docs/weekly1.png
  docs/weekly2.png
  src/main/java/com/devcourse/global/ApplicationController.java
  src/main/java/com/devcourse/global/Command.java
  src/main/java/com/devcourse/global/common/Constant.java
  src/main/java/com/devcourse/global/console/Console.java
  src/main/java/com/devcourse/global/console/IoParser.java
  src/main/java/com/devcourse/global/dto/CreateVoucherRequest.java
  src/main/java/com/devcourse/global/sql/Delete.java
  src/main/java/com/devcourse/global/sql/Insert.java
  src/main/java/com/devcourse/global/sql/Select.java
  src/main/java/com/devcourse/global/sql/Sql.java
  src/main/java/com/devcourse/global/sql/Update.java
  src/main/java/com/devcourse/global/sql/Where.java
  src/main/java/com/devcourse/global/utils/CaseConverter.java
  src/main/java/com/devcourse/user/User.java
  src/main/java/com/devcourse/user/application/UserService.java
  src/main/java/com/devcourse/user/domain/User.java
  src/main/java/com/devcourse/user/domain/repository/UserRepository.java
  src/main/java/com/devcourse/user/repository/BlackListRepository.java
  src/main/java/com/devcourse/user/repository/JdbcUserRepository.java
  src/main/java/com/devcourse/user/repository/UserRepository.java
  src/main/java/com/devcourse/voucher/application/VoucherService.java
  src/main/java/com/devcourse/voucher/domain/Transient.java
  src/main/java/com/devcourse/voucher/domain/Voucher.java
  src/main/java/com/devcourse/voucher/domain/repository/AbstractVoucherRepository.java
  src/main/java/com/devcourse/voucher/domain/repository/FileVoucherRepository.java
  src/main/java/com/devcourse/voucher/domain/repository/JdbcVoucherRepository.java
  src/main/java/com/devcourse/voucher/domain/repository/MemoryVoucherRepository.java
  src/main/java/com/devcourse/voucher/domain/repository/VoucherRepository.java
  src/main/java/com/devcourse/voucher/presentation/Command.java
  src/main/java/com/devcourse/voucher/presentation/VoucherController.java
  src/main/resources/application.yml
  src/main/resources/file/vouchers.txt
  src/main/resources/schema.sql
  src/test/java/com/devcourse/global/console/ParserTest.java
  src/test/java/com/devcourse/user/repository/JdbcUserRepositoryTest.java
  src/test/java/com/devcourse/voucher/application/VoucherServiceTest.java
  src/test/java/com/devcourse/voucher/domain/DiscountPolicyTest.java
  src/test/java/com/devcourse/voucher/domain/VoucherTest.java
  src/test/java/com/devcourse/voucher/domain/repository/JdbcVoucherRepositoryTest.java
  src/test/java/com/devcourse/voucher/domain/repository/MemoryVoucherRepositoryTest.java
  src/test/resources/application.yml
Labels: 🔥 매운맛, Team-Kyu

#823 [4기 - 장수연] SpringBoot Part2 Weekly Mission 제출합니다.
  README.md
  build.gradle
  src/main/java/builder/Condition.java
  src/main/java/builder/Delete.java
  src/main/java/builder/Insert.java
  src/main/java/builder/Operator.java
  src/main/java/builder/Order.java
  src/main/java/builder/Select.java
  src/main/java/builder/Sort.java
  src/main/java/builder/Update.java
  src/main/java/builder/Where.java
  src/main/java/builder/builderEntity/Entity.java
  src/main/java/com/prgms/voucher/voucherproject/App/CustomerApp.java
  src/main/java/com/prgms/voucher/voucherproject/App/VoucherApp.java
  src/main/java/com/prgms/voucher/voucherproject/AppType.java
  src/main/java/com/prgms/voucher/voucherproject/ProjectApp.java
  src/main/java/com/prgms/voucher/voucherproject/domain/Voucher.java
  src/main/java/com/prgms/voucher/voucherproject/domain/customer/Customer.java
  src/main/java/com/prgms/voucher/voucherproject/domain/customer/CustomerResponse.java
  src/main/java/com/prgms/voucher/voucherproject/domain/customer/CustomerType.java
  src/main/java/com/prgms/voucher/voucherproject/domain/voucher/FixedAmountVoucher.java
  src/main/java/com/prgms/voucher/voucherproject/domain/voucher/MenuType.java
  src/main/java/com/prgms/voucher/voucherproject/domain/voucher/PercentDiscountVoucher.java
  src/main/java/com/prgms/voucher/voucherproject/domain/voucher/Voucher.java
  src/main/java/com/prgms/voucher/voucherproject/domain/voucher/VoucherResponse.java
  src/main/java/com/prgms/voucher/voucherproject/domain/voucher/VoucherType.java
  src/main/java/com/prgms/voucher/voucherproject/exception/NotFoundCustomerException.java
  src/main/java/com/prgms/voucher/voucherproject/io/Console.java
  src/main/java/com/prgms/voucher/voucherproject/io/Constant.java
  src/main/java/com/prgms/voucher/voucherproject/repository/VoucherRepository.java
  src/main/java/com/prgms/voucher/voucherproject/repository/customer/CustomerRepository.java
  src/main/java/com/prgms/voucher/voucherproject/repository/customer/JdbcCustomerRepository.java
  src/main/java/com/prgms/voucher/voucherproject/repository/voucher/JdbcVoucherRepository.java
  src/main/java/com/prgms/voucher/voucherproject/repository/voucher/MemoryVoucherRepository.java
  src/main/java/com/prgms/voucher/voucherproject/repository/voucher/VoucherRepository.java
  src/main/java/com/prgms/voucher/voucherproject/service/CustomerService.java
  src/main/java/com/prgms/voucher/voucherproject/service/VoucherService.java
  src/main/java/com/prgms/voucher/voucherproject/util/JdbcUtils.java
  src/main/resources/application.yml
  src/main/resources/logback.xml
  src/main/resources/schema.sql
  src/test/java/builder/DeleteCriteriaTest.java
  src/test/java/builder/InsertCriteriaTest.java
  src/test/java/builder/SelectCriteriaTest.java
  src/test/resources/application-test.yml
Labels: 💧 순한맛, Team-Kyu

#840 [4기 - 민승현] SpringBoot Part2 Weekly Mission 첫 번째 PR 제출합니다.
  .gitignore
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  img.png
  img_1.png
  settings.gradle
  src/main/java/org/promgrammers/voucher/VoucherApplication.java
  src/main/java/org/promgrammers/voucher/config/AppConfig.java
  src/main/java/org/promgrammers/voucher/controller/CustomerController.java
  src/main/java/org/promgrammers/voucher/controller/VoucherController.java
  src/main/java/org/promgrammers/voucher/domain/Customer.java
  src/main/java/org/promgrammers/voucher/domain/CustomerType.java
  src/main/java/org/promgrammers/voucher/domain/FixedAmountVoucher.java
  src/main/java/org/promgrammers/voucher/domain/PercentDiscountVoucher.java
  src/main/java/org/promgrammers/voucher/domain/Voucher.java
  src/main/java/org/promgrammers/voucher/domain/VoucherType.java
  src/main/java/org/promgrammers/voucher/domain/dto/customer/CustomerListResponseDto.java
  src/main/java/org/promgrammers/voucher/domain/dto/customer/CustomerRequestDto.java
  src/main/java/org/promgrammers/voucher/domain/dto/customer/CustomerResponseDto.java
  src/main/java/org/promgrammers/voucher/domain/dto/voucher/VoucherCreateRequestDto.java
  src/main/java/org/promgrammers/voucher/domain/dto/voucher/VoucherListResponseDto.java
  src/main/java/org/promgrammers/voucher/domain/dto/voucher/VoucherResponseDto.java
  src/main/java/org/promgrammers/voucher/repository/CustomerRepository.java
  src/main/java/org/promgrammers/voucher/repository/JdbcCustomerRepository.java
  src/main/java/org/promgrammers/voucher/repository/JdbcVoucherRepository.java
  src/main/java/org/promgrammers/voucher/repository/MemoryVoucherRepository.java
  src/main/java/org/promgrammers/voucher/repository/VoucherRepository.java
  src/main/java/org/promgrammers/voucher/service/CustomerService.java
  src/main/java/org/promgrammers/voucher/service/VoucherFactory.java
  src/main/java/org/promgrammers/voucher/service/VoucherService.java
  src/main/java/org/promgrammers/voucher/util/CustomerUtils.java
  src/main/java/org/promgrammers/voucher/util/VoucherUtils.java
  src/main/java/org/promgrammers/voucher/view/Console.java
  src/main/java/org/promgrammers/voucher/view/CustomerAction.java
  src/main/java/org/promgrammers/voucher/view/Option.java
  src/main/resources/application.yaml
  src/test/java/org/promgrammers/voucher/VoucherApplicationTests.java
  src/test/java/org/promgrammers/voucher/domain/FixedAmountVoucherTest.java
  src/test/java/org/promgrammers/voucher/domain/PercentDiscountVoucherTest.java
  src/test/java/org/promgrammers/voucher/repository/MemoryVoucherRepositoryTest.java
Labels: 🔥 매운맛, Team-Navy

#872 [4기 - 신범철] SpringBoot Weekly Mission 쿼리 빌더 PR입니다.
  src/main/java/org/prgrms/kdtspringdemo/CommandLineApplication.java
  src/main/java/org/prgrms/kdtspringdemo/customer/constant/CustomerColumn.java
  src/main/java/org/prgrms/kdtspringdemo/customer/exception/CustomerException.java
  src/main/java/org/prgrms/kdtspringdemo/customer/exception/CustomerNotFoundException.java
  src/main/java/org/prgrms/kdtspringdemo/customer/model/dto/CustomerResponse.java
  src/main/java/org/prgrms/kdtspringdemo/customer/model/entity/Customer.java
  src/main/java/org/prgrms/kdtspringdemo/customer/repository/JdbcCustomerRepository.java
  src/main/java/org/prgrms/kdtspringdemo/customer/service/CustomerService.java
  src/main/java/org/prgrms/kdtspringdemo/util/JdbcUtils.java
  src/main/java/org/prgrms/kdtspringdemo/util/queryBuilder/Entity.java
  src/main/java/org/prgrms/kdtspringdemo/util/queryBuilder/constant/Operator.java
  src/main/java/org/prgrms/kdtspringdemo/util/queryBuilder/constant/Symbol.java
  src/main/java/org/prgrms/kdtspringdemo/util/queryBuilder/constant/Table.java
  src/main/java/org/prgrms/kdtspringdemo/util/queryBuilder/query/Delete.java
  src/main/java/org/prgrms/kdtspringdemo/util/queryBuilder/query/DeleteBuilder.java
  src/main/java/org/prgrms/kdtspringdemo/util/queryBuilder/query/Insert.java
  src/main/java/org/prgrms/kdtspringdemo/util/queryBuilder/query/InsertBuilder.java
  src/main/java/org/prgrms/kdtspringdemo/util/queryBuilder/query/Order.java
  src/main/java/org/prgrms/kdtspringdemo/util/queryBuilder/query/Select.java
  src/main/java/org/prgrms/kdtspringdemo/util/queryBuilder/query/SelectBuilder.java
  src/main/java/org/prgrms/kdtspringdemo/util/queryBuilder/query/Update.java
  src/main/java/org/prgrms/kdtspringdemo/util/queryBuilder/query/UpdateBuilder.java
  src/main/java/org/prgrms/kdtspringdemo/util/queryBuilder/query/Where.java
  src/main/java/org/prgrms/kdtspringdemo/util/queryBuilder/query/WhereBuilder.java
  src/main/java/org/prgrms/kdtspringdemo/voucher/constant/VoucherColumn.java
  src/main/java/org/prgrms/kdtspringdemo/voucher/model/dto/VoucherResponse.java
  src/main/java/org/prgrms/kdtspringdemo/voucher/model/entity/Voucher.java
  src/main/java/org/prgrms/kdtspringdemo/voucher/ropository/JdbcVoucherRepository.java
  src/main/java/org/prgrms/kdtspringdemo/voucher/service/VoucherServiceImpl.java
  src/test/java/org/prgrms/kdtspringdemo/voucher/model/entity/FixedAmountVoucherTest.java
  src/test/java/org/prgrms/kdtspringdemo/voucher/model/entity/PercentAmountVoucherTest.java
Labels: 🔥 매운맛, Team-Kyu
