Repository prgrms-be-devcourse/springboot-basic, pull requests merged in 2023-10, with the labels that each got.

#885 [5기 김별이] SpringBoot Part1 Weekly Mission 제출합니다.
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/prgrms/springbasic/SpringBasicApplication.java
  src/main/java/com/prgrms/springbasic/common/CommandType.java
  src/main/java/com/prgrms/springbasic/common/MenuHandler.java
  src/main/java/com/prgrms/springbasic/common/VoucherRunner.java
  src/main/java/com/prgrms/springbasic/domain/customer/controller/CustomerController.java
  src/main/java/com/prgrms/springbasic/domain/customer/dto/CustomerResponse.java
  src/main/java/com/prgrms/springbasic/domain/customer/entity/Customer.java
  src/main/java/com/prgrms/springbasic/domain/customer/repository/CustomerRepository.java
  src/main/java/com/prgrms/springbasic/domain/customer/service/CustomerService.java
  src/main/java/com/prgrms/springbasic/domain/voucher/controller/VoucherController.java
  src/main/java/com/prgrms/springbasic/domain/voucher/dto/CreateVoucherRequest.java
  src/main/java/com/prgrms/springbasic/domain/voucher/dto/VoucherResponse.java
  src/main/java/com/prgrms/springbasic/domain/voucher/entity/DiscountType.java
  src/main/java/com/prgrms/springbasic/domain/voucher/entity/FixedAmountVoucher.java
  src/main/java/com/prgrms/springbasic/domain/voucher/entity/PercentDiscountVoucher.java
  src/main/java/com/prgrms/springbasic/domain/voucher/entity/Voucher.java
  src/main/java/com/prgrms/springbasic/domain/voucher/repository/FileVoucherRepository.java
  src/main/java/com/prgrms/springbasic/domain/voucher/repository/MemoryVoucherRepository.java
  src/main/java/com/prgrms/springbasic/domain/voucher/repository/VoucherRepository.java
  src/main/java/com/prgrms/springbasic/domain/voucher/service/VoucherService.java
  src/main/java/com/prgrms/springbasic/io/Console.java
  src/main/java/com/prgrms/springbasic/io/ConsoleMessage.java
  src/main/java/com/prgrms/springbasic/io/Input.java
  src/main/java/com/prgrms/springbasic/io/Output.java
  src/main/java/com/prgrms/springbasic/util/CsvFileUtil.java
  src/main/resources/application.yml
  src/main/resources/logback.xml
  src/test/java/com/prgrms/springbasic/SpringBasicApplicationTests.java
  src/test/java/com/prgrms/springbasic/domain/voucher/entity/FixedAmountVoucherTest.java
Labels: 🔥 매운맛, Team-BingBong

#889 [5기 김대휘] SpringBoot Part1 Weekly Mission 제출합니다.
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/programmers/vouchermanagement/VoucherManagementApplication.java
  src/main/java/com/programmers/vouchermanagement/common/ConsoleMessage.java
  src/main/java/com/programmers/vouchermanagement/common/ErrorMessage.java
  src/main/java/com/programmers/vouchermanagement/domain/customer/Customer.java
  src/main/java/com/programmers/vouchermanagement/domain/voucher/FixedAmountVoucher.java
  src/main/java/com/programmers/vouchermanagement/domain/voucher/PercentDiscountVoucher.java
  src/main/java/com/programmers/vouchermanagement/domain/voucher/Voucher.java
  src/main/java/com/programmers/vouchermanagement/domain/voucher/VoucherFactory.java
  src/main/java/com/programmers/vouchermanagement/domain/voucher/VoucherType.java
  src/main/java/com/programmers/vouchermanagement/repository/customer/CustomerRepository.java
  src/main/java/com/programmers/vouchermanagement/repository/customer/FileCustomerRepository.java
  src/main/java/com/programmers/vouchermanagement/repository/voucher/FileVoucherRepository.java
  src/main/java/com/programmers/vouchermanagement/repository/voucher/MemoryVoucherRepository.java
  src/main/java/com/programmers/vouchermanagement/repository/voucher/VoucherRepository.java
  src/main/java/com/programmers/vouchermanagement/service/VoucherService.java
  src/main/java/com/programmers/vouchermanagement/view/Command.java
  src/main/java/com/programmers/vouchermanagement/view/Console.java
  src/main/resources/application.yml
  src/main/resources/files/customer_blacklist.csv
  src/main/resources/files/vouchers.csv
  src/main/resources/logback.xml
  src/test/java/com/programmers/vouchermanagement/VoucherManagementApplicationTests.java
  src/test/java/com/programmers/vouchermanagement/domain/FixedAmountVoucherTest.java
Labels: 🔥 매운맛, Team-BingBong

#887 [5기 - 조은비] SpringBoot Part1 Weekly Mission 제출합니다.
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/programmers/springbasic/VoucherApplication.java
  src/main/java/com/programmers/springbasic/command/Command.java
  src/main/java/com/programmers/springbasic/command/CommandExecutor.java
  src/main/java/com/programmers/springbasic/command/CommandFactory.java
  src/main/java/com/programmers/springbasic/command/CreateVoucherCommand.java
  src/main/java/com/programmers/springbasic/command/ExitCommand.java
  src/main/java/com/programmers/springbasic/command/GetBlacklistCustomersCommand.java
  src/main/java/com/programmers/springbasic/command/GetVouchersCommand.java
  src/main/java/com/programmers/springbasic/console/ConsoleInputHandler.java
  src/main/java/com/programmers/springbasic/console/ConsoleOutputHandler.java
  src/main/java/com/programmers/springbasic/controller/CustomerController.java
  src/main/java/com/programmers/springbasic/controller/VoucherController.java
  src/main/java/com/programmers/springbasic/dto/CreateFixedAmountVoucherRequest.java
  src/main/java/com/programmers/springbasic/dto/CreatePercentDiscountVoucherRequest.java
  src/main/java/com/programmers/springbasic/dto/GetBlacklistCustomersResponse.java
  src/main/java/com/programmers/springbasic/dto/GetVouchersResponse.java
  src/main/java/com/programmers/springbasic/entity/customer/Customer.java
  src/main/java/com/programmers/springbasic/entity/voucher/FixedAmountVoucher.java
  src/main/java/com/programmers/springbasic/entity/voucher/PercentDiscountVoucher.java
  src/main/java/com/programmers/springbasic/entity/voucher/Voucher.java
  src/main/java/com/programmers/springbasic/entity/voucher/VoucherType.java
  src/main/java/com/programmers/springbasic/enums/CommandType.java
  src/main/java/com/programmers/springbasic/enums/ErrorCode.java
  src/main/java/com/programmers/springbasic/mapper/CustomerMapper.java
  src/main/java/com/programmers/springbasic/mapper/VoucherMapper.java
  src/main/java/com/programmers/springbasic/repository/customer/CustomerRepository.java
  src/main/java/com/programmers/springbasic/repository/customer/FileCustomerRepository.java
  src/main/java/com/programmers/springbasic/repository/voucher/FileVoucherRepository.java
  src/main/java/com/programmers/springbasic/repository/voucher/MemoryVoucherRepository.java
  src/main/java/com/programmers/springbasic/repository/voucher/VoucherRepository.java
  src/main/java/com/programmers/springbasic/service/CustomerService.java
  src/main/java/com/programmers/springbasic/service/VoucherService.java
  src/main/java/com/programmers/springbasic/utils/FileUtils.java
  src/main/resources/application.yml
  src/main/resources/logback.xml
Labels: 🔥 매운맛, Team-BingBong

#874 [5기 - 이한나] SpringBoot Part1 Weekly Mission 제출합니다.
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/programmers/vouchermanagement/VoucherManagementApp.java
  src/main/java/com/programmers/vouchermanagement/config/properties/FileProperties.java
  src/main/java/com/programmers/vouchermanagement/controller/CustomerShellController.java
  src/main/java/com/programmers/vouchermanagement/controller/GlobalShellController.java
  src/main/java/com/programmers/vouchermanagement/controller/VoucherShellController.java
  src/main/java/com/programmers/vouchermanagement/domain/customer/Customer.java
  src/main/java/com/programmers/vouchermanagement/domain/voucher/FixedAmountVoucher.java
  src/main/java/com/programmers/vouchermanagement/domain/voucher/PercentDiscountVoucher.java
  src/main/java/com/programmers/vouchermanagement/domain/voucher/Voucher.java
  src/main/java/com/programmers/vouchermanagement/domain/voucher/VoucherFactory.java
  src/main/java/com/programmers/vouchermanagement/domain/voucher/VoucherType.java
  src/main/java/com/programmers/vouchermanagement/dto/customer/GetCustomersRequestDto.java
  src/main/java/com/programmers/vouchermanagement/infra/ApplicationListenerImpl.java
  src/main/java/com/programmers/vouchermanagement/infra/ShellCommandLoggingAspect.java
  src/main/java/com/programmers/vouchermanagement/infra/io/ConsoleInput.java
  src/main/java/com/programmers/vouchermanagement/infra/io/ConsoleOutput.java
  src/main/java/com/programmers/vouchermanagement/repository/customer/CustomerRepository.java
  src/main/java/com/programmers/vouchermanagement/repository/customer/FileCustomerRepository.java
  src/main/java/com/programmers/vouchermanagement/repository/voucher/MemoryVoucherRepository.java
  src/main/java/com/programmers/vouchermanagement/repository/voucher/VoucherRepository.java
  src/main/java/com/programmers/vouchermanagement/service/CustomerService.java
  src/main/java/com/programmers/vouchermanagement/service/VoucherService.java
  src/main/java/com/programmers/vouchermanagement/util/CsvMapper.java
  src/main/java/com/programmers/vouchermanagement/util/IdProvider.java
  src/main/java/com/programmers/vouchermanagement/util/UuidProvider.java
  src/main/resources/application.yml
  src/main/resources/customers.csv
  src/main/resources/logback.xml
  src/test/java/com/programmers/vouchermanagement/service/CustomerServiceTest.java
  src/test/java/com/programmers/vouchermanagement/service/VoucherServiceTest.java
  src/test/java/com/programmers/vouchermanagement/stub/repository/StubCustomerRepository.java
  src/test/java/com/programmers/vouchermanagement/stub/repository/StubVoucherRepository.java
  src/test/java/com/programmers/vouchermanagement/stub/util/StubUuidProvider.java
Labels: 🔥 매운맛, Team-BingBong

#891 [5기 - 김강훈] SpringBoot Part1 Weekly Mission 제출합니다.
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/weeklyMission/DemoApplication.java
  src/main/java/com/weeklyMission/client/Client.java
  src/main/java/com/weeklyMission/client/VoucherType.java
  src/main/java/com/weeklyMission/config/Config.java
  src/main/java/com/weeklyMission/console/ConsoleIO.java
  src/main/java/com/weeklyMission/exception/ExceptionHandler.java
  src/main/java/com/weeklyMission/exception/IncorrectInputException.java
  src/main/java/com/weeklyMission/member/controller/MemberController.java
  src/main/java/com/weeklyMission/member/domain/Member.java
  src/main/java/com/weeklyMission/member/repository/FileMemberRepository.java
  src/main/java/com/weeklyMission/member/service/MemberService.java
  src/main/java/com/weeklyMission/voucher/controller/VoucherController.java
  src/main/java/com/weeklyMission/voucher/domain/FixedAmountVoucher.java
  src/main/java/com/weeklyMission/voucher/domain/PercentDiscountVoucher.java
  src/main/java/com/weeklyMission/voucher/domain/Voucher.java
  src/main/java/com/weeklyMission/voucher/dto/VoucherRequest.java
  src/main/java/com/weeklyMission/voucher/dto/VoucherResponse.java
  src/main/java/com/weeklyMission/voucher/repository/FileVoucherRepository.java
  src/main/java/com/weeklyMission/voucher/repository/MemoryVoucherRepository.java
  src/main/java/com/weeklyMission/voucher/repository/VoucherFactory.java
  src/main/java/com/weeklyMission/voucher/repository/VoucherRepository.java
  src/main/java/com/weeklyMission/voucher/service/VoucherService.java
  src/main/resources/application.yaml
  src/main/resources/csv/blackListMember.csv
  src/main/resources/csv/voucherRepository.csv
  src/main/resources/logback.xml
  src/test/java/com/weeklyMission/demo/DemoApplicationTests.java
  src/test/java/com/weeklyMission/voucher/domain/FixedAmountVoucherTest.java
  src/test/java/com/weeklyMission/voucher/domain/PercentDiscountVoucherTest.java
  src/test/resources/csv/voucherRepository.csv
Labels: 🔥 매운맛, Team-Hoon

#880 [5기 박영재] SpringBoot Part1 Weekly Mission 제출합니다.
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/zerozae/voucher/VoucherApplication.java
  src/main/java/com/zerozae/voucher/common/MenuHandler.java
  src/main/java/com/zerozae/voucher/common/MenuType.java
  src/main/java/com/zerozae/voucher/common/ProgramRunner.java
  src/main/java/com/zerozae/voucher/common/response/Response.java
  src/main/java/com/zerozae/voucher/controller/customer/CustomerController.java
  src/main/java/com/zerozae/voucher/controller/voucher/VoucherController.java
  src/main/java/com/zerozae/voucher/domain/customer/Customer.java
  src/main/java/com/zerozae/voucher/domain/customer/CustomerType.java
  src/main/java/com/zerozae/voucher/domain/voucher/FixedDiscountVoucher.java
  src/main/java/com/zerozae/voucher/domain/voucher/PercentDiscountVoucher.java
  src/main/java/com/zerozae/voucher/domain/voucher/UseStatusType.java
  src/main/java/com/zerozae/voucher/domain/voucher/Voucher.java
  src/main/java/com/zerozae/voucher/domain/voucher/VoucherType.java
  src/main/java/com/zerozae/voucher/dto/customer/CustomerRequest.java
  src/main/java/com/zerozae/voucher/dto/customer/CustomerResponse.java
  src/main/java/com/zerozae/voucher/dto/voucher/VoucherRequest.java
  src/main/java/com/zerozae/voucher/dto/voucher/VoucherResponse.java
  src/main/java/com/zerozae/voucher/exception/ErrorMessage.java
  src/main/java/com/zerozae/voucher/repository/customer/CustomerRepository.java
  src/main/java/com/zerozae/voucher/repository/voucher/FileVoucherRepository.java
  src/main/java/com/zerozae/voucher/repository/voucher/MemoryVoucherRepository.java
  src/main/java/com/zerozae/voucher/repository/voucher/VoucherRepository.java
  src/main/java/com/zerozae/voucher/service/customer/CustomerService.java
  src/main/java/com/zerozae/voucher/service/voucher/VoucherService.java
  src/main/java/com/zerozae/voucher/validator/InputValidator.java
  src/main/java/com/zerozae/voucher/view/ConsoleView.java
  src/main/java/com/zerozae/voucher/view/Input.java
  src/main/java/com/zerozae/voucher/view/Output.java
  src/main/resources/application.yml
  src/main/resources/logback.xml
  src/test/java/com/zerozae/voucher/controller/CustomerControllerTest.java
  src/test/java/com/zerozae/voucher/controller/VoucherControllerTest.java
  src/test/java/com/zerozae/voucher/domain/CustomerTest.java
  src/test/java/com/zerozae/voucher/domain/VoucherTest.java
  src/test/java/com/zerozae/voucher/service/CustomerServiceTest.java
  src/test/java/com/zerozae/voucher/service/VoucherServiceTest.java
  src/test/java/com/zerozae/voucher/validator/InputValidatorTest.java
Labels: 🔥 매운맛, Team-BingBong

#906 [5기 - 박주한] SpringBoot Part1 Weekly Mission 제출합니다.
  .gitignore
  .mvn/wrapper/MavenWrapperDownloader.java
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/org/prgrms/kdt/KdtApplication.java
  src/main/java/org/prgrms/kdt/OrderTester.java
  src/main/java/org/prgrms/kdt/app/configuration/AppConfiguration.java
  src/main/java/org/prgrms/kdt/app/configuration/YamlPropertiesFactory.java
  src/main/java/org/prgrms/kdt/app/configuration/io/ConsoleInputHandler.java
  src/main/java/org/prgrms/kdt/app/configuration/io/ConsoleOutputHandler.java
  src/main/java/org/prgrms/kdt/app/configuration/io/InputHandler.java
  src/main/java/org/prgrms/kdt/app/configuration/io/OutputHandler.java
  src/main/java/org/prgrms/kdt/user/controller/UserController.java
  src/main/java/org/prgrms/kdt/user/domain/User.java
  src/main/java/org/prgrms/kdt/user/repository/UserRepository.java
  src/main/java/org/prgrms/kdt/user/service/UserService.java
  src/main/java/org/prgrms/kdt/voucher/controller/VoucherController.java
  src/main/java/org/prgrms/kdt/voucher/domain/FixedAmountVoucher.java
  src/main/java/org/prgrms/kdt/voucher/domain/PercentDiscountVoucher.java
  src/main/java/org/prgrms/kdt/voucher/repository/JdbcVoucherRepository.java
  src/main/java/org/prgrms/kdt/voucher/repository/MemoryVoucherRepository.java
  src/main/java/org/prgrms/kdt/voucher/repository/VoucherRepository.java
  src/main/java/org/prgrms/kdt/voucher/service/VoucherService.java
  src/main/resources/application-local.yaml
  src/main/resources/application.properties
  src/main/resources/application.yaml
  src/main/resources/banner.txt
  src/main/resources/logback-backup.xml
  src/main/resources/logback.xml
  src/main/resources/version.properties
  src/test/java/org/prgrms/kdt/KdtApplicationTests.java
  test/sample.txt
Labels: 🔥 매운맛

#908 [5기 - 박주한] SpringBoot Part1 Weekly Mission 제출합니다.
  src/main/java/org/prgrms/kdt/KdtApplication.java
  src/main/java/org/prgrms/kdt/OrderTester.java
  src/main/java/org/prgrms/kdt/app/configuration/io/ConsoleInputHandler.java
  src/main/java/org/prgrms/kdt/voucher/controller/VoucherController.java
  src/main/java/org/prgrms/kdt/voucher/domain/FixedAmountVoucher.java
  src/main/java/org/prgrms/kdt/voucher/domain/PercentDiscountVoucher.java
  src/main/java/org/prgrms/kdt/voucher/domain/Voucher.java
  src/main/java/org/prgrms/kdt/voucher/repository/JdbcVoucherRepository.java
  src/main/java/org/prgrms/kdt/voucher/repository/MemoryVoucherRepository.java
  src/main/java/org/prgrms/kdt/voucher/repository/VoucherRepository.java
  src/main/java/org/prgrms/kdt/voucher/service/VoucherService.java
Labels: 🔥 매운맛, Team-Hoon

#899 [5기 - 엄예림] SpringBoot Part1 Weekly Mission 제출합니다.
  .gitignore
  HELP.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  logs/error_2023-10-19.log
  settings.gradle
  src/main/java/org/programmers/springorder/SpringOrderApplication.java
  src/main/java/org/programmers/springorder/VoucherApplication.java
  src/main/java/org/programmers/springorder/console/Console.java
  src/main/java/org/programmers/springorder/console/Input.java
  src/main/java/org/programmers/springorder/console/Output.java
  src/main/java/org/programmers/springorder/consts/ErrorMessage.java
  src/main/java/org/programmers/springorder/consts/Message.java
  src/main/java/org/programmers/springorder/customer/controller/CustomerController.java
  src/main/java/org/programmers/springorder/customer/dto/CustomerResponseDto.java
  src/main/java/org/programmers/springorder/customer/model/Customer.java
  src/main/java/org/programmers/springorder/customer/model/CustomerType.java
  src/main/java/org/programmers/springorder/customer/repository/CustomerRepository.java
  src/main/java/org/programmers/springorder/customer/repository/FileCustomerRepository.java
  src/main/java/org/programmers/springorder/customer/service/CustomerService.java
  src/main/java/org/programmers/springorder/utils/MenuType.java
  src/main/java/org/programmers/springorder/utils/Validation.java
  src/main/java/org/programmers/springorder/voucher/controller/VoucherController.java
  src/main/java/org/programmers/springorder/voucher/dto/VoucherRequestDto.java
  src/main/java/org/programmers/springorder/voucher/dto/VoucherResponseDto.java
  src/main/java/org/programmers/springorder/voucher/model/Voucher.java
  src/main/java/org/programmers/springorder/voucher/model/VoucherType.java
  src/main/java/org/programmers/springorder/voucher/repository/FileVoucherRepository.java
  src/main/java/org/programmers/springorder/voucher/repository/MemoryVoucherRepository.java
  src/main/java/org/programmers/springorder/voucher/repository/VoucherRepository.java
  src/main/java/org/programmers/springorder/voucher/service/VoucherService.java
  src/main/resources/application.yml
  src/main/resources/csv/customerList.csv
  src/main/resources/csv/voucher.csv
  src/main/resources/logback.xml
  src/test/java/org/programmers/springorder/model/VoucherTest.java
  src/test/java/org/programmers/springorder/model/VoucherTypeTest.java
  src/test/java/org/programmers/springorder/repository/MemoryVoucherRepositoryTest.java
  src/test/java/org/programmers/springorder/service/VoucherServiceTest.java
Labels: 🔥 매운맛, Team-Marco

#902 [5기 - 김주환] SpringBoot Part1 Weekly Mission 제출합니다.
  .gitignore
  blacklist.csv
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/programmers/springbootbasic/VoucherApplication.java
  src/main/java/com/programmers/springbootbasic/domain/user/application/UserService.java
  src/main/java/com/programmers/springbootbasic/domain/user/domain/entity/User.java
  src/main/java/com/programmers/springbootbasic/domain/user/infrastructure/dto/CsvUser.java
  src/main/java/com/programmers/springbootbasic/domain/user/presentation/UserController.java
  src/main/java/com/programmers/springbootbasic/domain/user/presentation/dto/UserResponse.java
  src/main/java/com/programmers/springbootbasic/domain/voucher/application/VoucherService.java
  src/main/java/com/programmers/springbootbasic/domain/voucher/domain/VoucherRepository.java
  src/main/java/com/programmers/springbootbasic/domain/voucher/domain/VoucherType/FixedAmountVoucher.java
  src/main/java/com/programmers/springbootbasic/domain/voucher/domain/VoucherType/PercentDiscountVoucher.java
  src/main/java/com/programmers/springbootbasic/domain/voucher/domain/VoucherType/VoucherType.java
  src/main/java/com/programmers/springbootbasic/domain/voucher/domain/VoucherType/VoucherTypeEnum.java
  src/main/java/com/programmers/springbootbasic/domain/voucher/domain/entity/Voucher.java
  src/main/java/com/programmers/springbootbasic/domain/voucher/infrastructure/CsvVoucher.java
  src/main/java/com/programmers/springbootbasic/domain/voucher/infrastructure/FilePersistenceVoucherRepository.java
  src/main/java/com/programmers/springbootbasic/domain/voucher/infrastructure/MemoryVoucherRepository.java
  src/main/java/com/programmers/springbootbasic/domain/voucher/presentation/VoucherController.java
  src/main/java/com/programmers/springbootbasic/domain/voucher/presentation/dto/CreateVoucherRequest.java
  src/main/java/com/programmers/springbootbasic/domain/voucher/presentation/dto/VoucherResponse.java
  src/main/java/com/programmers/springbootbasic/exception/AppExceptionHandler.java
  src/main/java/com/programmers/springbootbasic/exception/ErrorCode.java
  src/main/java/com/programmers/springbootbasic/exception/exceptionClass/CustomException.java
  src/main/java/com/programmers/springbootbasic/exception/exceptionClass/FileIOException.java
  src/main/java/com/programmers/springbootbasic/exception/exceptionClass/SystemException.java
  src/main/java/com/programmers/springbootbasic/exception/exceptionClass/UserException.java
  src/main/java/com/programmers/springbootbasic/exception/exceptionClass/VoucherException.java
  src/main/java/com/programmers/springbootbasic/infrastructure/IO/Console.java
  src/main/java/com/programmers/springbootbasic/infrastructure/IO/ConsoleInteractionAggregator.java
  src/main/java/com/programmers/springbootbasic/infrastructure/IO/ConsoleValidatorConfig.java
  src/main/java/com/programmers/springbootbasic/mediator/ConsoleRequest.java
  src/main/java/com/programmers/springbootbasic/mediator/ConsoleResponse.java
  src/main/java/com/programmers/springbootbasic/mediator/RequestProcessor.java
  src/main/java/com/programmers/springbootbasic/mediator/provider/MenuRequestProvider.java
  src/main/java/com/programmers/springbootbasic/mediator/requestGenerator/ExitRequestGenerator.java
  src/main/java/com/programmers/springbootbasic/mediator/requestGenerator/MenuRequestGenerator.java
  src/main/java/com/programmers/springbootbasic/mediator/requestGenerator/RegisterVoucherGenerator.java
  src/main/java/com/programmers/springbootbasic/mediator/requestGenerator/ViewAllBlackUserGenerator.java
  src/main/java/com/programmers/springbootbasic/mediator/requestGenerator/ViewAllVoucherGenerator.java
  src/main/java/com/programmers/springbootbasic/presentation/ControllerAdapter.java
  src/main/java/com/programmers/springbootbasic/presentation/IOManager.java
  src/main/java/com/programmers/springbootbasic/presentation/MainMenu.java
  src/main/java/com/programmers/springbootbasic/presentation/validation/InputValidator.java
  src/main/java/com/programmers/springbootbasic/util/CsvManager.java
  src/main/java/com/programmers/springbootbasic/util/FileManager.java
  src/main/java/com/programmers/springbootbasic/util/Messages.java
  src/main/resources/application.yml
  src/main/resources/logback-spring.xml
  voucher.csv
Labels: 🔥 매운맛, Team-R

#875 [5기 - 이경민] SpringBoot Part1 Weekly Mission 제출합니다.
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/programmers/springbootbasic/SpringbootBasicApplication.java
  src/main/java/com/programmers/springbootbasic/common/handler/CommandHandler.java
  src/main/java/com/programmers/springbootbasic/common/handler/CommandType.java
  src/main/java/com/programmers/springbootbasic/common/response/model/CommonResult.java
  src/main/java/com/programmers/springbootbasic/common/response/model/ListResult.java
  src/main/java/com/programmers/springbootbasic/common/response/service/ResponseFactory.java
  src/main/java/com/programmers/springbootbasic/common/utils/ConsoleIOManager.java
  src/main/java/com/programmers/springbootbasic/common/utils/CsvFileManager.java
  src/main/java/com/programmers/springbootbasic/domain/customer/controller/BlacklistCustomerController.java
  src/main/java/com/programmers/springbootbasic/domain/customer/entity/Customer.java
  src/main/java/com/programmers/springbootbasic/domain/customer/repository/BlacklistCustomerRepository.java
  src/main/java/com/programmers/springbootbasic/domain/customer/repository/CustomerRepository.java
  src/main/java/com/programmers/springbootbasic/domain/customer/service/BlacklistCustomerService.java
  src/main/java/com/programmers/springbootbasic/domain/voucher/controller/VoucherController.java
  src/main/java/com/programmers/springbootbasic/domain/voucher/dto/VoucherRequestDto.java
  src/main/java/com/programmers/springbootbasic/domain/voucher/entity/FixedAmountVoucher.java
  src/main/java/com/programmers/springbootbasic/domain/voucher/entity/PercentDiscountVoucher.java
  src/main/java/com/programmers/springbootbasic/domain/voucher/entity/Voucher.java
  src/main/java/com/programmers/springbootbasic/domain/voucher/exception/ErrorMsg.java
  src/main/java/com/programmers/springbootbasic/domain/voucher/repository/VoucherFileRepository.java
  src/main/java/com/programmers/springbootbasic/domain/voucher/repository/VoucherMemoryRepository.java
  src/main/java/com/programmers/springbootbasic/domain/voucher/repository/VoucherRepository.java
  src/main/java/com/programmers/springbootbasic/domain/voucher/service/VoucherService.java
  src/main/java/com/programmers/springbootbasic/domain/voucher/service/VoucherType.java
  src/main/resources/application.yaml
  src/main/resources/customer_blacklist.csv
  src/main/resources/logback.xml
  src/test/java/com/programmers/springbootbasic/domain/voucher/controller/VoucherControllerTest.java
  src/test/java/com/programmers/springbootbasic/domain/voucher/service/VoucherServiceTest.java
  src/test/java/com/programmers/springbootbasic/domain/voucher/service/VoucherTypeTest.java
Labels: 🔥 매운맛, Team-R

#884 [5기 - 소승수] SpringBoot Part1 Weekly Mission 제출합니다.
  .gitignore
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  logs/error 2023-10-16 12:10:41.log
  settings.gradle
  src/main/java/org/prgrms/prgrmsspring/PrgrmsSpringApplication.java
  src/main/java/org/prgrms/prgrmsspring/controller/ApplicationController.java
  src/main/java/org/prgrms/prgrmsspring/domain/Command.java
  src/main/java/org/prgrms/prgrmsspring/domain/VoucherType.java
  src/main/java/org/prgrms/prgrmsspring/entity/user/User.java
  src/main/java/org/prgrms/prgrmsspring/entity/voucher/FixedAmountVoucher.java
  src/main/java/org/prgrms/prgrmsspring/entity/voucher/PercentDiscountVoucher.java
  src/main/java/org/prgrms/prgrmsspring/entity/voucher/Voucher.java
  src/main/java/org/prgrms/prgrmsspring/exception/ExceptionMessage.java
  src/main/java/org/prgrms/prgrmsspring/exception/NotFoundException.java
  src/main/java/org/prgrms/prgrmsspring/repository/user/FileUserRepository.java
  src/main/java/org/prgrms/prgrmsspring/repository/user/UserRepository.java
  src/main/java/org/prgrms/prgrmsspring/repository/voucher/FileVoucherRepository.java
  src/main/java/org/prgrms/prgrmsspring/repository/voucher/InMemoryVoucherRepository.java
  src/main/java/org/prgrms/prgrmsspring/repository/voucher/VoucherRepository.java
  src/main/java/org/prgrms/prgrmsspring/service/UserService.java
  src/main/java/org/prgrms/prgrmsspring/service/VoucherService.java
  src/main/java/org/prgrms/prgrmsspring/view/CommandLineView.java
  src/main/resources/application.yaml
  src/main/resources/customer_blacklist.csv
  src/main/resources/logback-spring.xml
  src/main/resources/logback-variables.properties
  src/main/resources/voucher-repo.csv
Labels: 🔥 매운맛, Team-R

#894 [5기 김용상] SpringBoot Part1 Weekly Mission 제출합니다.
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/prgms/vouchermanager/VouchermanagerApplication.java
  src/main/java/com/prgms/vouchermanager/contorller/customer/CustomerController.java
  src/main/java/com/prgms/vouchermanager/contorller/customer/CustomerMenuType.java
  src/main/java/com/prgms/vouchermanager/contorller/front/FrontController.java
  src/main/java/com/prgms/vouchermanager/contorller/front/FrontMenuType.java
  src/main/java/com/prgms/vouchermanager/contorller/voucher/VoucherController.java
  src/main/java/com/prgms/vouchermanager/contorller/voucher/VoucherMenuType.java
  src/main/java/com/prgms/vouchermanager/domain/customer/Customer.java
  src/main/java/com/prgms/vouchermanager/domain/voucher/FixedAmountVoucher.java
  src/main/java/com/prgms/vouchermanager/domain/voucher/PercentDiscountVoucher.java
  src/main/java/com/prgms/vouchermanager/domain/voucher/Voucher.java
  src/main/java/com/prgms/vouchermanager/domain/voucher/VoucherType.java
  src/main/java/com/prgms/vouchermanager/dto/CreateVoucherDto.java
  src/main/java/com/prgms/vouchermanager/exception/ExceptionType.java
  src/main/java/com/prgms/vouchermanager/repository/customer/CustomerRepository.java
  src/main/java/com/prgms/vouchermanager/repository/voucher/FileVoucherRepository.java
  src/main/java/com/prgms/vouchermanager/repository/voucher/MemoryVoucherRepository.java
  src/main/java/com/prgms/vouchermanager/repository/voucher/VoucherRepository.java
  src/main/java/com/prgms/vouchermanager/service/customer/CustomerService.java
  src/main/java/com/prgms/vouchermanager/service/voucher/VoucherService.java
  src/main/java/com/prgms/vouchermanager/util/file/FileManager.java
  src/main/java/com/prgms/vouchermanager/util/io/ConsoleInput.java
  src/main/java/com/prgms/vouchermanager/util/io/ConsoleOutput.java
  src/main/java/com/prgms/vouchermanager/validation/InputValidation.java
  src/main/resources/application.yaml
  src/main/resources/customer_blackList.csv
  src/main/resources/logback.xml
  src/main/resources/voucher_list.csv
  src/test/java/com/prgms/vouchermanager/VouchermanagerApplicationTests.java
Labels: 🔥 매운맛, Team-R

#895 [5기 - 홍지인] SpringBoot Part1 Weekly Mission 제출합니다.
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/org/programmers/springboot/basic/AppConstants.java
  src/main/java/org/programmers/springboot/basic/VoucherManagementApplication.java
  src/main/java/org/programmers/springboot/basic/config/AppConfig.java
  src/main/java/org/programmers/springboot/basic/config/CustomerConfig.java
  src/main/java/org/programmers/springboot/basic/config/VoucherConfig.java
  src/main/java/org/programmers/springboot/basic/domain/customer/controller/CustomerController.java
  src/main/java/org/programmers/springboot/basic/domain/customer/dto/CsvCustomerDto.java
  src/main/java/org/programmers/springboot/basic/domain/customer/dto/CustomerResponseDto.java
  src/main/java/org/programmers/springboot/basic/domain/customer/entity/Customer.java
  src/main/java/org/programmers/springboot/basic/domain/customer/entity/CustomerType.java
  src/main/java/org/programmers/springboot/basic/domain/customer/exception/CustomerNotFoundException.java
  src/main/java/org/programmers/springboot/basic/domain/customer/mapper/CustomerMapper.java
  src/main/java/org/programmers/springboot/basic/domain/customer/repository/CustomerRepository.java
  src/main/java/org/programmers/springboot/basic/domain/customer/service/CustomerService.java
  src/main/java/org/programmers/springboot/basic/domain/voucher/controller/VoucherController.java
  src/main/java/org/programmers/springboot/basic/domain/voucher/dto/CsvVoucherDto.java
  src/main/java/org/programmers/springboot/basic/domain/voucher/dto/VoucherRequestDto.java
  src/main/java/org/programmers/springboot/basic/domain/voucher/dto/VoucherResponseDto.java
  src/main/java/org/programmers/springboot/basic/domain/voucher/entity/FixedAmountVoucher.java
  src/main/java/org/programmers/springboot/basic/domain/voucher/entity/PercentDiscountVoucher.java
  src/main/java/org/programmers/springboot/basic/domain/voucher/entity/Voucher.java
  src/main/java/org/programmers/springboot/basic/domain/voucher/entity/VoucherType.java
  src/main/java/org/programmers/springboot/basic/domain/voucher/exception/IllegalDiscountException.java
  src/main/java/org/programmers/springboot/basic/domain/voucher/exception/VoucherNotFoundException.java
  src/main/java/org/programmers/springboot/basic/domain/voucher/exception/VoucherValidatorNotFoundException.java
  src/main/java/org/programmers/springboot/basic/domain/voucher/mapper/VoucherMapper.java
  src/main/java/org/programmers/springboot/basic/domain/voucher/repository/FileVoucherRepository.java
  src/main/java/org/programmers/springboot/basic/domain/voucher/repository/MemoryVoucherRepository.java
  src/main/java/org/programmers/springboot/basic/domain/voucher/repository/VoucherRepository.java
  src/main/java/org/programmers/springboot/basic/domain/voucher/service/VoucherService.java
  src/main/java/org/programmers/springboot/basic/domain/voucher/service/validate/FixedAmountVoucherValidator.java
  src/main/java/org/programmers/springboot/basic/domain/voucher/service/validate/PercentDiscountVoucherValidator.java
  src/main/java/org/programmers/springboot/basic/domain/voucher/service/validate/ValidateHandler.java
  src/main/java/org/programmers/springboot/basic/util/CommandType.java
  src/main/java/org/programmers/springboot/basic/util/exception/CSVFileIOFailureException.java
  src/main/java/org/programmers/springboot/basic/util/exception/CommandNotFoundException.java
  src/main/java/org/programmers/springboot/basic/util/exception/ConsoleIOFailureException.java
  src/main/java/org/programmers/springboot/basic/util/manager/CSVFileManager.java
  src/main/java/org/programmers/springboot/basic/util/manager/CommandManager.java
  src/main/java/org/programmers/springboot/basic/util/manager/ConsoleIOManager.java
  src/main/java/org/programmers/springboot/basic/util/properties/ExternalProperties.java
  src/main/java/org/programmers/springboot/basic/util/properties/FileProperties.java
  src/main/resources/application.yaml
  src/main/resources/customer_blacklist.csv
  src/main/resources/logback.xml
  src/main/resources/voucherRecord.csv
  src/test/java/org/programmers/springboot/basic/SpringbootBasicApplicationTests.java
  src/test/java/org/programmers/springboot/basic/voucher/repository/FileVoucherRepositoryTest.java
  src/test/resources/testVoucherRecord.csv
  src/test/resources/test_customer_blacklist.csv
Labels: 🔥 매운맛, Team-R

#897 [5기 - 정의진] SpringBoot Part1 Weekly Mission 제출합니다.
  .gitignore
  HELP.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/team/marco/vouchermanagementsystem/VoucherManagementSystemApplication.java
  src/main/java/team/marco/vouchermanagementsystem/application/CommandType.java
  src/main/java/team/marco/vouchermanagementsystem/application/ConsoleApplication.java
  src/main/java/team/marco/vouchermanagementsystem/model/FixedAmountVoucher.java
  src/main/java/team/marco/vouchermanagementsystem/model/LoadedVoucher.java
  src/main/java/team/marco/vouchermanagementsystem/model/PercentDiscountVoucher.java
  src/main/java/team/marco/vouchermanagementsystem/model/User.java
  src/main/java/team/marco/vouchermanagementsystem/model/Voucher.java
  src/main/java/team/marco/vouchermanagementsystem/model/VoucherType.java
  src/main/java/team/marco/vouchermanagementsystem/properties/FilePathProperties.java
  src/main/java/team/marco/vouchermanagementsystem/repository/BlacklistRepository.java
  src/main/java/team/marco/vouchermanagementsystem/repository/JSONFileVoucherRepository.java
  src/main/java/team/marco/vouchermanagementsystem/repository/MemoryVoucherRepository.java
  src/main/java/team/marco/vouchermanagementsystem/repository/VoucherRepository.java
  src/main/java/team/marco/vouchermanagementsystem/service/BlacklistService.java
  src/main/java/team/marco/vouchermanagementsystem/service/VoucherService.java
  src/main/java/team/marco/vouchermanagementsystem/util/Console.java
  src/main/resources/application.yml
  src/main/resources/banner.txt
  src/main/resources/blacklist.csv
  src/main/resources/logback.xml
  src/main/resources/sample_data.json
  src/main/resources/voucher_data.json
  src/test/java/team/marco/vouchermanagementsystem/VoucherManagementSystemApplicationTests.java
Labels: 🔥 매운맛, Team-Marco

#882 [5기 - 권효승] SpringBoot Part1 Weekly Mission 제출합니다.
  .gitignore
  HELP.md
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/devcourse/springbootbasic/AppConfig.java
  src/main/java/devcourse/springbootbasic/SpringbootBasicApplication.java
  src/main/java/devcourse/springbootbasic/commandline/CommandLineExecutor.java
  src/main/java/devcourse/springbootbasic/commandline/console/ConsoleIOHandler.java
  src/main/java/devcourse/springbootbasic/commandline/console/input/ConsoleInput.java
  src/main/java/devcourse/springbootbasic/commandline/console/input/ScannerInput.java
  src/main/java/devcourse/springbootbasic/commandline/console/output/ConsoleOutput.java
  src/main/java/devcourse/springbootbasic/commandline/console/output/PrintStreamOutput.java
  src/main/java/devcourse/springbootbasic/commandline/constant/ConsoleConstants.java
  src/main/java/devcourse/springbootbasic/commandline/constant/InputMessage.java
  src/main/java/devcourse/springbootbasic/commandline/domain/VoucherTypeSelector.java
  src/main/java/devcourse/springbootbasic/commandline/function/Function.java
  src/main/java/devcourse/springbootbasic/commandline/function/FunctionHandler.java
  src/main/java/devcourse/springbootbasic/controller/CustomerController.java
  src/main/java/devcourse/springbootbasic/controller/VoucherController.java
  src/main/java/devcourse/springbootbasic/domain/customer/Customer.java
  src/main/java/devcourse/springbootbasic/domain/voucher/Voucher.java
  src/main/java/devcourse/springbootbasic/domain/voucher/VoucherType.java
  src/main/java/devcourse/springbootbasic/dto/CustomerFindResponse.java
  src/main/java/devcourse/springbootbasic/dto/VoucherCreateRequest.java
  src/main/java/devcourse/springbootbasic/dto/VoucherCreateResponse.java
  src/main/java/devcourse/springbootbasic/dto/VoucherFindResponse.java
  src/main/java/devcourse/springbootbasic/exception/FileErrorMessage.java
  src/main/java/devcourse/springbootbasic/exception/FileException.java
  src/main/java/devcourse/springbootbasic/exception/InputErrorMessage.java
  src/main/java/devcourse/springbootbasic/exception/InputException.java
  src/main/java/devcourse/springbootbasic/exception/VoucherErrorMessage.java
  src/main/java/devcourse/springbootbasic/exception/VoucherException.java
  src/main/java/devcourse/springbootbasic/repository/customer/CsvCustomerRepository.java
  src/main/java/devcourse/springbootbasic/repository/customer/CustomerRepository.java
  src/main/java/devcourse/springbootbasic/repository/customer/InMemoryCustomerRepository.java
  src/main/java/devcourse/springbootbasic/repository/voucher/CsvVoucherRepository.java
  src/main/java/devcourse/springbootbasic/repository/voucher/InMemoryVoucherRepository.java
  src/main/java/devcourse/springbootbasic/repository/voucher/VoucherRepository.java
  src/main/java/devcourse/springbootbasic/service/CustomerService.java
  src/main/java/devcourse/springbootbasic/service/VoucherService.java
  src/main/java/devcourse/springbootbasic/util/CsvFileHandler.java
  src/main/resources/application.yaml
  src/main/resources/customer.csv
  src/main/resources/logback.xml
  src/main/resources/voucher.csv
Labels: 🔥 매운맛, Team-Dozzi

#905 [5기 - 이수진] SpringBoot Part1 Weekly Mission 제출합니다.
  .gitignore
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  logs/log
  settings.gradle
  src/main/java/com/prgrms/vouchermanagement/VouchermanagementApplication.java
  src/main/java/com/prgrms/vouchermanagement/core/voucher/controller/VoucherController.java
  src/main/java/com/prgrms/vouchermanagement/core/voucher/controller/request/VoucherCreateRequest.java
  src/main/java/com/prgrms/vouchermanagement/core/voucher/controller/response/VoucherResponse.java
  src/main/java/com/prgrms/vouchermanagement/core/voucher/controller/response/VouchersResponse.java
  src/main/java/com/prgrms/vouchermanagement/core/voucher/domain/Voucher.java
  src/main/java/com/prgrms/vouchermanagement/core/voucher/domain/VoucherType.java
  src/main/java/com/prgrms/vouchermanagement/core/voucher/dto/VoucherDto.java
  src/main/java/com/prgrms/vouchermanagement/core/voucher/repository/MemoryVoucherRepository.java
  src/main/java/com/prgrms/vouchermanagement/core/voucher/repository/VoucherRepository.java
  src/main/java/com/prgrms/vouchermanagement/core/voucher/repository/file/FileRepository.java
  src/main/java/com/prgrms/vouchermanagement/core/voucher/repository/file/FileStorage.java
  src/main/java/com/prgrms/vouchermanagement/core/voucher/repository/file/Voucher.json
  src/main/java/com/prgrms/vouchermanagement/core/voucher/repository/file/VoucherVO.java
  src/main/java/com/prgrms/vouchermanagement/core/voucher/service/VoucherService.java
  src/main/java/com/prgrms/vouchermanagement/core/voucher/utils/PropertiesUtil.java
  src/main/java/com/prgrms/vouchermanagement/core/voucher/utils/mapper/Mapper.java
  src/main/java/com/prgrms/vouchermanagement/infra/InfraManager.java
  src/main/java/com/prgrms/vouchermanagement/infra/exception/InvalidFormatException.java
  src/main/java/com/prgrms/vouchermanagement/infra/input/BufferedReaderImpl.java
  src/main/java/com/prgrms/vouchermanagement/infra/input/ConsoleImpl.java
  src/main/java/com/prgrms/vouchermanagement/infra/input/InputProvider.java
  src/main/java/com/prgrms/vouchermanagement/infra/input/ScannerImpl.java
  src/main/java/com/prgrms/vouchermanagement/infra/output/OutputImpl.java
  src/main/java/com/prgrms/vouchermanagement/infra/output/OutputProvider.java
  src/main/java/com/prgrms/vouchermanagement/infra/utils/MenuPatternUtils.java
  src/main/java/com/prgrms/vouchermanagement/infra/utils/MenuType.java
  src/main/java/com/prgrms/vouchermanagement/infra/utils/OutputMessage.java
  src/main/resources/application.properties
  src/test/java/com/prgrms/vouchermanagement/VouchermanagementApplicationTests.java
Labels: 🔥 매운맛, Team-Hoon

#896 [5기 - 김현우] SpringBoot Part1 Weekly Mission 제출합니다.
  .gitignore
  HELP.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/team/marco/vouchermanagementsystem/VoucherManagementSystemApplication.java
  src/main/java/team/marco/vouchermanagementsystem/application/CommandType.java
  src/main/java/team/marco/vouchermanagementsystem/application/ConsoleApplication.java
  src/main/java/team/marco/vouchermanagementsystem/model/FixedAmountVoucher.java
  src/main/java/team/marco/vouchermanagementsystem/model/LoadedVoucher.java
  src/main/java/team/marco/vouchermanagementsystem/model/PercentDiscountVoucher.java
  src/main/java/team/marco/vouchermanagementsystem/model/User.java
  src/main/java/team/marco/vouchermanagementsystem/model/Voucher.java
  src/main/java/team/marco/vouchermanagementsystem/model/VoucherType.java
  src/main/java/team/marco/vouchermanagementsystem/properties/FilePathProperties.java
  src/main/java/team/marco/vouchermanagementsystem/repository/BlacklistRepository.java
  src/main/java/team/marco/vouchermanagementsystem/repository/JSONFileVoucherRepository.java
  src/main/java/team/marco/vouchermanagementsystem/repository/MemoryVoucherRepository.java
  src/main/java/team/marco/vouchermanagementsystem/repository/VoucherRepository.java
  src/main/java/team/marco/vouchermanagementsystem/service/BlacklistService.java
  src/main/java/team/marco/vouchermanagementsystem/service/VoucherService.java
  src/main/java/team/marco/vouchermanagementsystem/util/Console.java
  src/main/resources/application.yml
  src/main/resources/banner.txt
  src/main/resources/blacklist.csv
  src/main/resources/logback.xml
  src/main/resources/sample_data.json
  src/main/resources/voucher_data.json
  src/test/java/team/marco/vouchermanagementsystem/VoucherManagementSystemApplicationTests.java
Labels: 🔥 매운맛, Team-Marco

#901 [5기 - 송인재] SpringBoot Part1 Weekly Mission 제출합니다.
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/programmers/vouchermanagement/VoucherManagementApplication.java
  src/main/java/com/programmers/vouchermanagement/configuration/AppConfig.java
  src/main/java/com/programmers/vouchermanagement/configuration/properties/AppProperties.java
  src/main/java/com/programmers/vouchermanagement/configuration/properties/Customer.java
  src/main/java/com/programmers/vouchermanagement/configuration/properties/Domains.java
  src/main/java/com/programmers/vouchermanagement/configuration/properties/Resources.java
  src/main/java/com/programmers/vouchermanagement/configuration/properties/Voucher.java
  src/main/java/com/programmers/vouchermanagement/consoleapp/io/ConsoleManager.java
  src/main/java/com/programmers/vouchermanagement/consoleapp/menu/Menu.java
  src/main/java/com/programmers/vouchermanagement/consoleapp/menu/MenuHandler.java
  src/main/java/com/programmers/vouchermanagement/consoleapp/runner/ConsoleAppRunner.java
  src/main/java/com/programmers/vouchermanagement/customer/controller/CustomerController.java
  src/main/java/com/programmers/vouchermanagement/customer/domain/Customer.java
  src/main/java/com/programmers/vouchermanagement/customer/domain/CustomerType.java
  src/main/java/com/programmers/vouchermanagement/customer/dto/CustomerResponse.java
  src/main/java/com/programmers/vouchermanagement/customer/repository/CustomerRepository.java
  src/main/java/com/programmers/vouchermanagement/customer/repository/FileCustomerRepository.java
  src/main/java/com/programmers/vouchermanagement/customer/service/CustomerService.java
  src/main/java/com/programmers/vouchermanagement/util/Formatter.java
  src/main/java/com/programmers/vouchermanagement/util/Validator.java
  src/main/java/com/programmers/vouchermanagement/voucher/controller/VoucherController.java
  src/main/java/com/programmers/vouchermanagement/voucher/domain/Voucher.java
  src/main/java/com/programmers/vouchermanagement/voucher/domain/VoucherType.java
  src/main/java/com/programmers/vouchermanagement/voucher/dto/CreateVoucherRequest.java
  src/main/java/com/programmers/vouchermanagement/voucher/dto/VoucherResponse.java
  src/main/java/com/programmers/vouchermanagement/voucher/repository/FileVoucherRepository.java
  src/main/java/com/programmers/vouchermanagement/voucher/repository/InMemoryVoucherRepository.java
  src/main/java/com/programmers/vouchermanagement/voucher/repository/VoucherRepository.java
  src/main/java/com/programmers/vouchermanagement/voucher/service/VoucherService.java
  src/main/resources/application-dev.yaml
  src/main/resources/application-prod.yaml
  src/main/resources/blacklist.csv
  src/main/resources/logback-spring.xml
  src/main/resources/voucher.json
  src/test/java/com/programmers/vouchermanagement/configuration/TestConfig.java
  src/test/java/com/programmers/vouchermanagement/configuration/YamlPropertiesFactory.java
  src/test/java/com/programmers/vouchermanagement/consoleapp/menu/MenuHandlerTest.java
  src/test/java/com/programmers/vouchermanagement/consoleapp/menu/MenuTest.java
  src/test/java/com/programmers/vouchermanagement/customer/repository/FileCustomerRepositoryTest.java
  src/test/java/com/programmers/vouchermanagement/customer/service/CustomerServiceTest.java
  src/test/java/com/programmers/vouchermanagement/voucher/domain/VoucherTypeTest.java
  src/test/java/com/programmers/vouchermanagement/voucher/repository/FileVoucherRepositoryTest.java
  src/test/java/com/programmers/vouchermanagement/voucher/service/VoucherServiceTest.java
  src/test/resources/application-test.yaml
  src/test/resources/blacklist-test.csv
  src/test/resources/voucher-test.json
Labels: 🔥 매운맛, Team-Marco

#898 [5기 - 이중원] SpringBoot Part1 Weekly Mission 제출합니다.
  .gitignore
  HELP.md
  bin/main/csv/customerList.csv
  bin/main/csv/voucher.csv
  bin/main/logback.xml
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  logs/error_2023-10-19.log
  settings.gradle
  src/main/java/org/programmers/springorder/SpringOrderApplication.java
  src/main/java/org/programmers/springorder/VoucherApplication.java
  src/main/java/org/programmers/springorder/console/Console.java
  src/main/java/org/programmers/springorder/console/Input.java
  src/main/java/org/programmers/springorder/console/Output.java
  src/main/java/org/programmers/springorder/consts/ErrorMessage.java
  src/main/java/org/programmers/springorder/consts/Message.java
  src/main/java/org/programmers/springorder/customer/controller/CustomerController.java
  src/main/java/org/programmers/springorder/customer/dto/CustomerResponseDto.java
  src/main/java/org/programmers/springorder/customer/model/Customer.java
  src/main/java/org/programmers/springorder/customer/model/CustomerType.java
  src/main/java/org/programmers/springorder/customer/repository/CustomerRepository.java
  src/main/java/org/programmers/springorder/customer/repository/FileCustomerRepository.java
  src/main/java/org/programmers/springorder/customer/repository/JdbcCustomerRepository.java
  src/main/java/org/programmers/springorder/customer/service/CustomerService.java
  src/main/java/org/programmers/springorder/utils/MenuType.java
  src/main/java/org/programmers/springorder/utils/Validation.java
  src/main/java/org/programmers/springorder/voucher/controller/VoucherController.java
  src/main/java/org/programmers/springorder/voucher/dto/VoucherRequestDto.java
  src/main/java/org/programmers/springorder/voucher/dto/VoucherResponseDto.java
  src/main/java/org/programmers/springorder/voucher/model/Voucher.java
  src/main/java/org/programmers/springorder/voucher/model/VoucherType.java
  src/main/java/org/programmers/springorder/voucher/repository/FileVoucherRepository.java
  src/main/java/org/programmers/springorder/voucher/repository/MemoryVoucherRepository.java
  src/main/java/org/programmers/springorder/voucher/repository/VoucherRepository.java
  src/main/java/org/programmers/springorder/voucher/service/VoucherService.java
  src/main/resources/application.yml
  src/main/resources/csv/customerList.csv
  src/main/resources/csv/voucher.csv
  src/main/resources/logback.xml
  src/test/java/org/programmers/springorder/customer/repository/JdbcCustomerRepositoryTest.java
  src/test/java/org/programmers/springorder/model/VoucherTest.java
  src/test/java/org/programmers/springorder/model/VoucherTypeTest.java
  src/test/java/org/programmers/springorder/repository/MemoryVoucherRepositoryTest.java
  src/test/java/org/programmers/springorder/service/VoucherServiceTest.java
Labels: 🔥 매운맛, Team-Marco

#881 [5기 박유진] SpringBoot Part1 Weekly Mission 제출합니다.
  .gitignore
  .mvn/wrapper/MavenWrapperDownloader.java
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  HELP.md
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/org/prgrms/kdtspringdemo/AppController.java
  src/main/java/org/prgrms/kdtspringdemo/KdtSpringDemoApplication.java
  src/main/java/org/prgrms/kdtspringdemo/customer/controller/CustomerController.java
  src/main/java/org/prgrms/kdtspringdemo/customer/domain/Customer.java
  src/main/java/org/prgrms/kdtspringdemo/customer/repository/CustomerRepository.java
  src/main/java/org/prgrms/kdtspringdemo/customer/repository/FileCustomerRepository.java
  src/main/java/org/prgrms/kdtspringdemo/customer/repository/JdbcCustomerRepository.java
  src/main/java/org/prgrms/kdtspringdemo/customer/service/CustomerService.java
  src/main/java/org/prgrms/kdtspringdemo/file/CsvFileHandler.java
  src/main/java/org/prgrms/kdtspringdemo/view/InputConsole.java
  src/main/java/org/prgrms/kdtspringdemo/view/OutputConsole.java
  src/main/java/org/prgrms/kdtspringdemo/voucher/VoucherFunction.java
  src/main/java/org/prgrms/kdtspringdemo/voucher/controller/VoucherController.java
  src/main/java/org/prgrms/kdtspringdemo/voucher/domain/FixedDiscountPolicy.java
  src/main/java/org/prgrms/kdtspringdemo/voucher/domain/PercentDiscountPolicy.java
  src/main/java/org/prgrms/kdtspringdemo/voucher/domain/Voucher.java
  src/main/java/org/prgrms/kdtspringdemo/voucher/domain/VoucherPolicy.java
  src/main/java/org/prgrms/kdtspringdemo/voucher/domain/VoucherTypeFunction.java
  src/main/java/org/prgrms/kdtspringdemo/voucher/repository/FileVoucherRepository.java
  src/main/java/org/prgrms/kdtspringdemo/voucher/repository/JdbcVoucherRepository.java
  src/main/java/org/prgrms/kdtspringdemo/voucher/repository/MemoryVoucherRepository.java
  src/main/java/org/prgrms/kdtspringdemo/voucher/repository/VoucherRepository.java
  src/main/java/org/prgrms/kdtspringdemo/voucher/service/VoucherService.java
  src/main/java/org/prgrms/kdtspringdemo/wallet/domain/Wallet.java
  src/main/java/org/prgrms/kdtspringdemo/wallet/domain/dto/WalletDBDto.java
  src/main/java/org/prgrms/kdtspringdemo/wallet/repository/JdbcWalletRepository.java
  src/main/java/org/prgrms/kdtspringdemo/wallet/repository/WalletRepository.java
  src/main/resources/application.yml
  src/main/resources/application_prod.yml
  src/main/resources/csvFiles/customer_blacklist.csv
  src/main/resources/csvFiles/voucherList.csv
  src/main/resources/logback.xml
  src/test/java/org/prgrms/kdtspringdemo/KdtSpringDemoApplicationTests.java
  src/test/java/org/prgrms/kdtspringdemo/customer/controller/CustomerControllerTest.java
  src/test/java/org/prgrms/kdtspringdemo/customer/repository/FileCustomerRepositoryTest.java
  src/test/java/org/prgrms/kdtspringdemo/customer/repository/JdbcCustomerRepositoryTest.java
  src/test/java/org/prgrms/kdtspringdemo/voucher/repository/FileVoucherRepositoryTest.java
  src/test/java/org/prgrms/kdtspringdemo/voucher/repository/JdbcVoucherRepositoryTest.java
  src/test/java/org/prgrms/kdtspringdemo/voucher/repository/MemoryVoucherRepositoryTest.java
  src/test/java/org/prgrms/kdtspringdemo/voucher/service/VoucherServiceTest.java
  src/test/java/org/prgrms/kdtspringdemo/wallet/repository/JdbcWalletRepositoryTest.java
  src/test/resources/test_customerBlackList
  src/test/resources/test_voucherList
Labels: 🔥 매운맛, Team-Dozzi

#909 [5기 - 박주한] SpringBoot Part1 Weekly Mission 제출합니다.
  pom.xml
  src/main/java/org/prgrms/kdt/KdtApplication.java
  src/main/java/org/prgrms/kdt/OrderTester.java
  src/main/java/org/prgrms/kdt/app/YamlPropertiesFactory.java
  src/main/java/org/prgrms/kdt/app/configuration/AppConfiguration.java
  src/main/java/org/prgrms/kdt/app/configuration/io/ConsoleOutputHandler.java
  src/main/java/org/prgrms/kdt/app/configuration/io/OutputHandler.java
  src/main/java/org/prgrms/kdt/app/io/ConsoleInputHandler.java
  src/main/java/org/prgrms/kdt/app/io/ConsoleOutputHandler.java
  src/main/java/org/prgrms/kdt/app/io/InputHandler.java
  src/main/java/org/prgrms/kdt/app/io/OutputHandler.java
  src/main/java/org/prgrms/kdt/app/io/StartMenu.java
  src/main/java/org/prgrms/kdt/app/io/SystemMessage.java
  src/main/java/org/prgrms/kdt/customer/controller/CustomerController.java
  src/main/java/org/prgrms/kdt/customer/domain/Customer.java
  src/main/java/org/prgrms/kdt/customer/repository/CustomerFileRepository.java
  src/main/java/org/prgrms/kdt/customer/repository/CustomerRepository.java
  src/main/java/org/prgrms/kdt/customer/service/CustomerService.java
  src/main/java/org/prgrms/kdt/user/controller/UserController.java
  src/main/java/org/prgrms/kdt/user/domain/User.java
  src/main/java/org/prgrms/kdt/user/repository/UserRepository.java
  src/main/java/org/prgrms/kdt/user/service/UserService.java
  src/main/java/org/prgrms/kdt/voucher/controller/FixedAmountVoucherDto.java
  src/main/java/org/prgrms/kdt/voucher/controller/PercentDiscountVoucherDto.java
  src/main/java/org/prgrms/kdt/voucher/controller/VoucherController.java
  src/main/java/org/prgrms/kdt/voucher/domain/FixedAmountVoucher.java
  src/main/java/org/prgrms/kdt/voucher/domain/PercentDiscountVoucher.java
  src/main/java/org/prgrms/kdt/voucher/repository/JdbcVoucherRepository.java
  src/main/java/org/prgrms/kdt/voucher/repository/MemoryVoucherRepository.java
  src/main/java/org/prgrms/kdt/voucher/repository/VoucherRepository.java
  src/main/java/org/prgrms/kdt/voucher/service/VoucherService.java
  src/main/resources/application.properties
  src/main/resources/customer_blacklist.csv
  src/main/resources/logback-backup.xml
  src/main/resources/logback.xml
  src/main/resources/version.properties
Labels: 🔥 매운맛, Team-Hoon

#892 [5기 - 최정은] SpringBoot Part1 Weekly Mission 제출합니다.
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/org/prgms/kdtspringweek1/AppCommandLineRunner.java
  src/main/java/org/prgms/kdtspringweek1/KdtSpringWeek1Application.java
  src/main/java/org/prgms/kdtspringweek1/console/ConsoleInput.java
  src/main/java/org/prgms/kdtspringweek1/console/ConsoleOutput.java
  src/main/java/org/prgms/kdtspringweek1/console/ScannerInput.java
  src/main/java/org/prgms/kdtspringweek1/console/dto/CreateVoucherRequestDto.java
  src/main/java/org/prgms/kdtspringweek1/console/dto/FindCustomerResponseDto.java
  src/main/java/org/prgms/kdtspringweek1/console/dto/FindVoucherResponseDto.java
  src/main/java/org/prgms/kdtspringweek1/console/dto/SelectFunctionTypeDto.java
  src/main/java/org/prgms/kdtspringweek1/console/dto/SelectVoucherTypeDto.java
  src/main/java/org/prgms/kdtspringweek1/controller/AppController.java
  src/main/java/org/prgms/kdtspringweek1/customer/CustomerService.java
  src/main/java/org/prgms/kdtspringweek1/customer/entity/Customer.java
  src/main/java/org/prgms/kdtspringweek1/customer/repository/CsvFileCustomerRepository.java
  src/main/java/org/prgms/kdtspringweek1/customer/repository/CustomerRepository.java
  src/main/java/org/prgms/kdtspringweek1/exception/FileException.java
  src/main/java/org/prgms/kdtspringweek1/exception/FileExceptionCode.java
  src/main/java/org/prgms/kdtspringweek1/exception/InputExceptionCode.java
  src/main/java/org/prgms/kdtspringweek1/voucher/entity/FixedAmountVoucher.java
  src/main/java/org/prgms/kdtspringweek1/voucher/entity/PercentDiscountVoucher.java
  src/main/java/org/prgms/kdtspringweek1/voucher/entity/Voucher.java
  src/main/java/org/prgms/kdtspringweek1/voucher/entity/VoucherType.java
  src/main/java/org/prgms/kdtspringweek1/voucher/repository/CsvFileVoucherRepository.java
  src/main/java/org/prgms/kdtspringweek1/voucher/repository/MemoryVoucherRepository.java
  src/main/java/org/prgms/kdtspringweek1/voucher/repository/VoucherRepository.java
  src/main/java/org/prgms/kdtspringweek1/voucher/service/VoucherService.java
  src/main/resources/application.yaml
  src/main/resources/customer_blacklist.csv
  src/main/resources/logback.xml
  src/main/resources/voucher.csv
  src/test/java/org/prgms/kdtspringweek1/KdtSpringWeek1ApplicationTests.java
Labels: 🔥 매운맛, Team-Dozzi

#873 [5기 - 이유정] SpringBoot Part1 Weekly Mission 제출합니다.
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/programmers/vouchermanagement/VoucherManagementApplication.java
  src/main/java/com/programmers/vouchermanagement/VoucherManagementController.java
  src/main/java/com/programmers/vouchermanagement/exception/CommandNotFoundException.java
  src/main/java/com/programmers/vouchermanagement/exception/FileIOException.java
  src/main/java/com/programmers/vouchermanagement/member/application/MemberService.java
  src/main/java/com/programmers/vouchermanagement/member/domain/Member.java
  src/main/java/com/programmers/vouchermanagement/member/domain/MemberType.java
  src/main/java/com/programmers/vouchermanagement/member/dto/MemberResponseDto.java
  src/main/java/com/programmers/vouchermanagement/member/exception/MemberNotFoundException.java
  src/main/java/com/programmers/vouchermanagement/member/mapper/MemberMapper.java
  src/main/java/com/programmers/vouchermanagement/member/presentation/MemberController.java
  src/main/java/com/programmers/vouchermanagement/member/repository/MemberRepository.java
  src/main/java/com/programmers/vouchermanagement/utils/Command.java
  src/main/java/com/programmers/vouchermanagement/utils/ConsoleInputManager.java
  src/main/java/com/programmers/vouchermanagement/utils/ConsoleOutputManager.java
  src/main/java/com/programmers/vouchermanagement/voucher/application/VoucherService.java
  src/main/java/com/programmers/vouchermanagement/voucher/domain/FixedVoucherPolicy.java
  src/main/java/com/programmers/vouchermanagement/voucher/domain/PercentVoucherPolicy.java
  src/main/java/com/programmers/vouchermanagement/voucher/domain/Voucher.java
  src/main/java/com/programmers/vouchermanagement/voucher/domain/VoucherPolicy.java
  src/main/java/com/programmers/vouchermanagement/voucher/domain/VoucherType.java
  src/main/java/com/programmers/vouchermanagement/voucher/dto/VoucherRequestDto.java
  src/main/java/com/programmers/vouchermanagement/voucher/dto/VoucherResponseDto.java
  src/main/java/com/programmers/vouchermanagement/voucher/exception/IllegalDiscountException.java
  src/main/java/com/programmers/vouchermanagement/voucher/exception/VoucherNotFoundException.java
  src/main/java/com/programmers/vouchermanagement/voucher/exception/VoucherTypeNotFoundException.java
  src/main/java/com/programmers/vouchermanagement/voucher/mapper/VoucherMapper.java
  src/main/java/com/programmers/vouchermanagement/voucher/presentation/VoucherController.java
  src/main/java/com/programmers/vouchermanagement/voucher/repository/FileVoucherRepository.java
  src/main/java/com/programmers/vouchermanagement/voucher/repository/MemoryVoucherRepository.java
  src/main/java/com/programmers/vouchermanagement/voucher/repository/VoucherRepository.java
  src/main/resources/application.yml
  src/main/resources/customer_blacklist.csv
  src/main/resources/logback.xml
  src/test/java/com/programmers/vouchermanagement/VoucherManagementApplicationTests.java
Labels: 🔥 매운맛, Team-Dozzi

#890 [5기 - 조인수] SpringBoot Part1 Weekly Mission 제출합니다.
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/org/prgms/springbootbasic/BasicApplication.java
  src/main/java/org/prgms/springbootbasic/common/CommonConstant.java
  src/main/java/org/prgms/springbootbasic/common/Console.java
  src/main/java/org/prgms/springbootbasic/common/file/CsvFileTemplate.java
  src/main/java/org/prgms/springbootbasic/common/file/CustomerCsvFileManager.java
  src/main/java/org/prgms/springbootbasic/common/file/VoucherCsvFileManager.java
  src/main/java/org/prgms/springbootbasic/controller/MainController.java
  src/main/java/org/prgms/springbootbasic/domain/VoucherType.java
  src/main/java/org/prgms/springbootbasic/domain/customer/Customer.java
  src/main/java/org/prgms/springbootbasic/domain/voucher/FixedAmountVoucher.java
  src/main/java/org/prgms/springbootbasic/domain/voucher/PercentDiscountVoucher.java
  src/main/java/org/prgms/springbootbasic/domain/voucher/VoucherPolicy.java
  src/main/java/org/prgms/springbootbasic/exception/OutOfRangeException.java
  src/main/java/org/prgms/springbootbasic/repository/CustomerFileRepository.java
  src/main/java/org/prgms/springbootbasic/repository/CustomerMemoryRepository.java
  src/main/java/org/prgms/springbootbasic/repository/CustomerRepository.java
  src/main/java/org/prgms/springbootbasic/repository/VoucherFileRepository.java
  src/main/java/org/prgms/springbootbasic/repository/VoucherMemoryRepository.java
  src/main/java/org/prgms/springbootbasic/repository/VoucherRepository.java
  src/main/java/org/prgms/springbootbasic/service/CustomerService.java
  src/main/java/org/prgms/springbootbasic/service/VoucherService.java
  src/main/resources/application.yml
  src/main/resources/customer_blacklist.csv
  src/main/resources/logback.xml
  src/test/java/org/prgms/springbootbasic/BasicApplicationTests.java
Labels: 🔥 매운맛, Team-Dozzi

#903 [5기 - 이경민] SpringBoot Part2 Weekly Mission 제출합니다.
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/programmers/springbootbasic/SpringbootBasicApplication.java
  src/main/java/com/programmers/springbootbasic/common/handler/CommandHandler.java
  src/main/java/com/programmers/springbootbasic/common/handler/CommandOutput.java
  src/main/java/com/programmers/springbootbasic/common/handler/CommandType.java
  src/main/java/com/programmers/springbootbasic/common/response/CommonResult.java
  src/main/java/com/programmers/springbootbasic/common/utils/ConsoleIOManager.java
  src/main/java/com/programmers/springbootbasic/common/utils/CsvFileManager.java
  src/main/java/com/programmers/springbootbasic/common/utils/UUIDConverter.java
  src/main/java/com/programmers/springbootbasic/common/utils/UUIDGenerator.java
  src/main/java/com/programmers/springbootbasic/common/utils/UUIDValueStrategy.java
  src/main/java/com/programmers/springbootbasic/domain/customer/controller/CustomerController.java
  src/main/java/com/programmers/springbootbasic/domain/customer/dto/CustomerRequestDto.java
  src/main/java/com/programmers/springbootbasic/domain/customer/entity/Customer.java
  src/main/java/com/programmers/springbootbasic/domain/customer/exception/ErrorMsg.java
  src/main/java/com/programmers/springbootbasic/domain/customer/repository/CustomerJDBCRepository.java
  src/main/java/com/programmers/springbootbasic/domain/customer/repository/CustomerRepository.java
  src/main/java/com/programmers/springbootbasic/domain/customer/service/CustomerService.java
  src/main/java/com/programmers/springbootbasic/domain/customer/vo/Email.java
  src/main/java/com/programmers/springbootbasic/domain/voucher/controller/VoucherController.java
  src/main/java/com/programmers/springbootbasic/domain/voucher/dto/VoucherRequestDto.java
  src/main/java/com/programmers/springbootbasic/domain/voucher/entity/FixedAmountVoucher.java
  src/main/java/com/programmers/springbootbasic/domain/voucher/entity/PercentDiscountVoucher.java
  src/main/java/com/programmers/springbootbasic/domain/voucher/entity/Voucher.java
  src/main/java/com/programmers/springbootbasic/domain/voucher/exception/ErrorMsg.java
  src/main/java/com/programmers/springbootbasic/domain/voucher/repository/VoucherFileRepository.java
  src/main/java/com/programmers/springbootbasic/domain/voucher/repository/VoucherJDBCRepository.java
  src/main/java/com/programmers/springbootbasic/domain/voucher/repository/VoucherMemoryRepository.java
  src/main/java/com/programmers/springbootbasic/domain/voucher/repository/VoucherRepository.java
  src/main/java/com/programmers/springbootbasic/domain/voucher/service/VoucherService.java
  src/main/java/com/programmers/springbootbasic/domain/voucher/service/VoucherType.java
  src/main/java/com/programmers/springbootbasic/domain/wallet/controller/WalletController.java
  src/main/java/com/programmers/springbootbasic/domain/wallet/dto/WalletRequestDto.java
  src/main/java/com/programmers/springbootbasic/domain/wallet/entity/Wallet.java
  src/main/java/com/programmers/springbootbasic/domain/wallet/exception/ErrorMsg.java
  src/main/java/com/programmers/springbootbasic/domain/wallet/repository/WalletRepository.java
  src/main/java/com/programmers/springbootbasic/domain/wallet/service/WalletService.java
  src/main/java/com/programmers/springbootbasic/domain/wallet/view/WalletView.java
  src/main/resources/application.yaml
  src/main/resources/customer_blacklist.csv
  src/main/resources/logback.xml
  src/main/resources/schema.sql
  src/test/java/com/programmers/springbootbasic/domain/customer/controller/CustomerControllerTest.java
  src/test/java/com/programmers/springbootbasic/domain/customer/service/CustomerServiceTest.java
  src/test/java/com/programmers/springbootbasic/domain/voucher/controller/VoucherControllerTest.java
  src/test/java/com/programmers/springbootbasic/domain/voucher/repository/VoucherFileRepositoryTest.java
  src/test/java/com/programmers/springbootbasic/domain/voucher/repository/VoucherMemoryRepositoryTest.java
  src/test/java/com/programmers/springbootbasic/domain/voucher/service/VoucherServiceTest.java
  src/test/java/com/programmers/springbootbasic/domain/voucher/service/VoucherTypeTest.java
  src/test/java/com/programmers/springbootbasic/domain/wallet/controller/WalletControllerTest.java
  src/test/java/com/programmers/springbootbasic/domain/wallet/service/WalletServiceTest.java
Labels: 🔥 매운맛, Team-R

#932 [5기 정의진] SpringBoot Part2 Weekly Mission 제출합니다.
  .gitignore
  HELP.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/team/marco/vouchermanagementsystem/VoucherManagementSystemApplication.java
  src/main/java/team/marco/vouchermanagementsystem/configuration/JdbcTemplateConfig.java
  src/main/java/team/marco/vouchermanagementsystem/controller/CustomerController.java
  src/main/java/team/marco/vouchermanagementsystem/controller/VoucherController.java
  src/main/java/team/marco/vouchermanagementsystem/model/Customer.java
  src/main/java/team/marco/vouchermanagementsystem/model/voucher/FixedAmountVoucher.java
  src/main/java/team/marco/vouchermanagementsystem/model/voucher/PercentDiscountVoucher.java
  src/main/java/team/marco/vouchermanagementsystem/model/voucher/Voucher.java
  src/main/java/team/marco/vouchermanagementsystem/model/voucher/VoucherType.java
  src/main/java/team/marco/vouchermanagementsystem/repository/custromer/BlacklistRepository.java
  src/main/java/team/marco/vouchermanagementsystem/repository/custromer/CsvBlacklistRepository.java
  src/main/java/team/marco/vouchermanagementsystem/repository/custromer/CustomerIdAndName.java
  src/main/java/team/marco/vouchermanagementsystem/repository/custromer/CustomerRepository.java
  src/main/java/team/marco/vouchermanagementsystem/repository/custromer/JdbcCustomerRepository.java
  src/main/java/team/marco/vouchermanagementsystem/repository/voucher/JdbcVoucherRepository.java
  src/main/java/team/marco/vouchermanagementsystem/repository/voucher/JsonFileVoucherRepository.java
  src/main/java/team/marco/vouchermanagementsystem/repository/voucher/LoadedJsonVoucher.java
  src/main/java/team/marco/vouchermanagementsystem/repository/voucher/MemoryVoucherRepository.java
  src/main/java/team/marco/vouchermanagementsystem/repository/voucher/VoucherRepository.java
  src/main/java/team/marco/vouchermanagementsystem/service/BlacklistService.java
  src/main/java/team/marco/vouchermanagementsystem/service/CustomerService.java
  src/main/java/team/marco/vouchermanagementsystem/service/VoucherService.java
  src/main/java/team/marco/vouchermanagementsystem/util/UUIDUtil.java
  src/main/java/team/marco/vouchermanagementsystem/view/CommandType.java
  src/main/java/team/marco/vouchermanagementsystem/view/ConsoleVoucherApplication.java
  src/main/java/team/marco/vouchermanagementsystem/view/ConsoleWalletApplication.java
  src/main/java/team/marco/vouchermanagementsystem/view/util/Console.java
  src/main/resources/application.yml
  src/main/resources/banner.txt
  src/main/resources/blacklist.csv
  src/main/resources/logback.xml
  src/main/resources/sample_data.json
  src/main/resources/schema.sql
  src/main/resources/voucher_data.json
  src/test/java/team/marco/vouchermanagementsystem/VoucherManagementSystemApplicationTests.java
  src/test/java/team/marco/vouchermanagementsystem/model/voucher/FixedAmountVoucherTest.java
  src/test/java/team/marco/vouchermanagementsystem/model/voucher/PercentDiscountVoucherTest.java
  src/test/java/team/marco/vouchermanagementsystem/repository/custromer/JdbcCustomerRepositoryTest.java
  src/test/java/team/marco/vouchermanagementsystem/repository/voucher/JdbcVoucherRepositoryTest.java
  src/test/java/team/marco/vouchermanagementsystem/repository/voucher/MemoryVoucherRepositoryTest.java
Labels: 🔥 매운맛, Team-Marco

#915 [5기 김별이] SpringBoot Part2 Weekly Mission 제출합니다.
  build.gradle
  src/main/java/com/prgrms/springbasic/common/CommandType.java
  src/main/java/com/prgrms/springbasic/common/MenuHandler.java
  src/main/java/com/prgrms/springbasic/common/MenuType.java
  src/main/java/com/prgrms/springbasic/common/VoucherRunner.java
  src/main/java/com/prgrms/springbasic/domain/customer/controller/CustomerController.java
  src/main/java/com/prgrms/springbasic/domain/customer/dto/CreateCustomerRequest.java
  src/main/java/com/prgrms/springbasic/domain/customer/dto/CustomerResponse.java
  src/main/java/com/prgrms/springbasic/domain/customer/entity/Customer.java
  src/main/java/com/prgrms/springbasic/domain/customer/repository/CustomerJdbcRepository.java
  src/main/java/com/prgrms/springbasic/domain/customer/repository/CustomerRepository.java
  src/main/java/com/prgrms/springbasic/domain/customer/service/CustomerService.java
  src/main/java/com/prgrms/springbasic/domain/voucher/controller/VoucherController.java
  src/main/java/com/prgrms/springbasic/domain/voucher/dto/CreateVoucherRequest.java
  src/main/java/com/prgrms/springbasic/domain/voucher/dto/UpdateVoucherRequest.java
  src/main/java/com/prgrms/springbasic/domain/voucher/dto/VoucherResponse.java
  src/main/java/com/prgrms/springbasic/domain/voucher/entity/FixedAmountVoucher.java
  src/main/java/com/prgrms/springbasic/domain/voucher/entity/PercentDiscountVoucher.java
  src/main/java/com/prgrms/springbasic/domain/voucher/entity/Voucher.java
  src/main/java/com/prgrms/springbasic/domain/voucher/repository/FileVoucherRepository.java
  src/main/java/com/prgrms/springbasic/domain/voucher/repository/JdbcVoucherRepository.java
  src/main/java/com/prgrms/springbasic/domain/voucher/repository/MemoryVoucherRepository.java
  src/main/java/com/prgrms/springbasic/domain/voucher/repository/VoucherRepository.java
  src/main/java/com/prgrms/springbasic/domain/voucher/service/VoucherService.java
  src/main/java/com/prgrms/springbasic/domain/wallet/controller/WalletController.java
  src/main/java/com/prgrms/springbasic/domain/wallet/dto/WalletRequest.java
  src/main/java/com/prgrms/springbasic/domain/wallet/dto/WalletResponse.java
  src/main/java/com/prgrms/springbasic/domain/wallet/entity/Wallet.java
  src/main/java/com/prgrms/springbasic/domain/wallet/repository/JdbcWalletRepository.java
  src/main/java/com/prgrms/springbasic/domain/wallet/service/WalletService.java
  src/main/java/com/prgrms/springbasic/io/Console.java
  src/main/java/com/prgrms/springbasic/io/ConsoleMessage.java
  src/main/java/com/prgrms/springbasic/io/Input.java
  src/main/java/com/prgrms/springbasic/util/CsvFileUtil.java
  src/main/java/com/prgrms/springbasic/util/UUIDUtils.java
  src/main/resources/application.yml
  src/main/resources/schema.sql
  src/test/java/com/prgrms/springbasic/domain/customer/service/CustomerServiceTest.java
  src/test/java/com/prgrms/springbasic/domain/voucher/entity/FixedAmountVoucherTest.java
  src/test/java/com/prgrms/springbasic/domain/voucher/entity/VoucherTest.java
  src/test/java/com/prgrms/springbasic/domain/voucher/repository/MemoryVoucherRepositoryTest.java
  src/test/java/com/prgrms/springbasic/domain/voucher/service/VoucherServiceTest.java
  src/test/java/com/prgrms/springbasic/domain/wallet/service/WalletServiceTest.java
Labels: 🔥 매운맛, Team-BingBong

#927 [5기 김대휘] SpringBoot Part2 Weekly Mission 제출합니다.
  .gitignore
  build.gradle
  src/main/java/com/programmers/vouchermanagement/common/ConsoleMessage.java
  src/main/java/com/programmers/vouchermanagement/domain/customer/Customer.java
  src/main/java/com/programmers/vouchermanagement/domain/voucher/FixedAmountVoucher.java
  src/main/java/com/programmers/vouchermanagement/domain/voucher/PercentDiscountVoucher.java
  src/main/java/com/programmers/vouchermanagement/domain/voucher/Voucher.java
  src/main/java/com/programmers/vouchermanagement/domain/voucher/VoucherFactory.java
  src/main/java/com/programmers/vouchermanagement/domain/voucher/VoucherType.java
  src/main/java/com/programmers/vouchermanagement/domain/wallet/Wallet.java
  src/main/java/com/programmers/vouchermanagement/dto/CustomerDto.java
  src/main/java/com/programmers/vouchermanagement/dto/VoucherDto.java
  src/main/java/com/programmers/vouchermanagement/message/ConsoleMessage.java
  src/main/java/com/programmers/vouchermanagement/message/CustomerMessage.java
  src/main/java/com/programmers/vouchermanagement/message/ErrorMessage.java
  src/main/java/com/programmers/vouchermanagement/message/VoucherMessage.java
  src/main/java/com/programmers/vouchermanagement/message/WalletMessage.java
  src/main/java/com/programmers/vouchermanagement/repository/customer/CustomerRepository.java
  src/main/java/com/programmers/vouchermanagement/repository/customer/FileCustomerRepository.java
  src/main/java/com/programmers/vouchermanagement/repository/customer/JdbcCustomerRepository.java
  src/main/java/com/programmers/vouchermanagement/repository/voucher/FileVoucherRepository.java
  src/main/java/com/programmers/vouchermanagement/repository/voucher/JdbcVoucherRepository.java
  src/main/java/com/programmers/vouchermanagement/repository/voucher/MemoryVoucherRepository.java
  src/main/java/com/programmers/vouchermanagement/repository/voucher/VoucherRepository.java
  src/main/java/com/programmers/vouchermanagement/repository/wallet/JdbcWalletRepository.java
  src/main/java/com/programmers/vouchermanagement/repository/wallet/WalletRepository.java
  src/main/java/com/programmers/vouchermanagement/service/CustomerService.java
  src/main/java/com/programmers/vouchermanagement/service/VoucherService.java
  src/main/java/com/programmers/vouchermanagement/service/WalletService.java
  src/main/java/com/programmers/vouchermanagement/utils/ConsoleUtil.java
  src/main/java/com/programmers/vouchermanagement/utils/CsvConvertable.java
  src/main/java/com/programmers/vouchermanagement/utils/CsvFileUtil.java
  src/main/java/com/programmers/vouchermanagement/view/Command.java
  src/main/java/com/programmers/vouchermanagement/view/Console.java
  src/main/resources/application.yml
  src/main/resources/database/docker-compose.yml
  src/main/resources/database/schema.sql
  src/test/java/com/programmers/vouchermanagement/domain/FixedAmountVoucherTest.java
  src/test/java/com/programmers/vouchermanagement/service/CustomerServiceTest.java
  src/test/java/com/programmers/vouchermanagement/service/VoucherServiceTest.java
  src/test/java/com/programmers/vouchermanagement/service/WalletServiceTest.java
  src/test/resources/application.yml
  src/test/resources/schema.sql
Labels: 🔥 매운맛, Team-BingBong

#934 [5기 - 김강훈] SpringBoot Part2 Weekly Mission 제출합니다
  .gitignore
  build.gradle
  src/main/java/com/weeklyMission/client/Client.java
  src/main/java/com/weeklyMission/common/CommandType.java
  src/main/java/com/weeklyMission/common/ResponseInfo.java
  src/main/java/com/weeklyMission/config/Config.java
  src/main/java/com/weeklyMission/console/ConsoleIO.java
  src/main/java/com/weeklyMission/exception/ExceptionHandler.java
  src/main/java/com/weeklyMission/member/controller/MemberController.java
  src/main/java/com/weeklyMission/member/domain/Member.java
  src/main/java/com/weeklyMission/member/dto/MemberRequest.java
  src/main/java/com/weeklyMission/member/dto/MemberResponse.java
  src/main/java/com/weeklyMission/member/repository/DBMemberRepository.java
  src/main/java/com/weeklyMission/member/repository/FileMemberRepository.java
  src/main/java/com/weeklyMission/member/repository/MemberRepository.java
  src/main/java/com/weeklyMission/member/service/MemberService.java
  src/main/java/com/weeklyMission/voucher/controller/VoucherController.java
  src/main/java/com/weeklyMission/voucher/domain/FixedAmountVoucher.java
  src/main/java/com/weeklyMission/voucher/domain/PercentDiscountVoucher.java
  src/main/java/com/weeklyMission/voucher/domain/Voucher.java
  src/main/java/com/weeklyMission/voucher/dto/VoucherRequest.java
  src/main/java/com/weeklyMission/voucher/dto/VoucherResponse.java
  src/main/java/com/weeklyMission/voucher/repository/DBVoucherRepository.java
  src/main/java/com/weeklyMission/voucher/repository/FileVoucherRepository.java
  src/main/java/com/weeklyMission/voucher/repository/MemoryVoucherRepository.java
  src/main/java/com/weeklyMission/voucher/repository/VoucherFactory.java
  src/main/java/com/weeklyMission/voucher/repository/VoucherRepository.java
  src/main/java/com/weeklyMission/voucher/service/VoucherService.java
  src/main/java/com/weeklyMission/wallet/controller/WalletController.java
  src/main/java/com/weeklyMission/wallet/domain/Wallet.java
  src/main/java/com/weeklyMission/wallet/repository/DBWalletRepository.java
  src/main/java/com/weeklyMission/wallet/repository/WalletRepository.java
  src/main/java/com/weeklyMission/wallet/service/WalletService.java
  src/main/resources/application.yaml
  src/main/resources/csv/blackListMember.csv
  src/main/resources/csv/voucherRepository.csv
  src/test/java/com/weeklyMission/member/repository/FileMemberRepositoryTest.java
  src/test/java/com/weeklyMission/voucher/domain/PercentDiscountVoucherTest.java
  src/test/java/com/weeklyMission/voucher/repository/FileVoucherRepositoryTest.java
  src/test/java/com/weeklyMission/voucher/repository/MemoryVoucherRepositoryTest.java
  src/test/java/com/weeklyMission/voucher/service/VoucherServiceTest.java
  src/test/resources/csv/blackListMember.csv
  src/test/resources/csv/voucherRepository.csv
Labels: 🔥 매운맛, Team-Hoon

#879 [5기 김남규] SpringBoot Part1 Weekly Mission 제출합니다.
  .gitignore
  application_log/application.log
  blacklist/blackList.csv
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/org/prgrms/vouchermanagement/VoucherManagementApplication.java
  src/main/java/org/prgrms/vouchermanagement/blackCustomer/BlackCustomer.java
  src/main/java/org/prgrms/vouchermanagement/blackCustomer/BlackCustomerRepository.java
  src/main/java/org/prgrms/vouchermanagement/blackCustomer/BlackCustomerService.java
  src/main/java/org/prgrms/vouchermanagement/controller/Controller.java
  src/main/java/org/prgrms/vouchermanagement/dto/VoucherInfo.java
  src/main/java/org/prgrms/vouchermanagement/exception/InsertFailException.java
  src/main/java/org/prgrms/vouchermanagement/exception/InvalidInputException.java
  src/main/java/org/prgrms/vouchermanagement/exception/InvalidRangeException.java
  src/main/java/org/prgrms/vouchermanagement/exception/LoadFailException.java
  src/main/java/org/prgrms/vouchermanagement/repository/FileRepository.java
  src/main/java/org/prgrms/vouchermanagement/repository/MemoryRepository.java
  src/main/java/org/prgrms/vouchermanagement/repository/VoucherRepository.java
  src/main/java/org/prgrms/vouchermanagement/service/VoucherService.java
  src/main/java/org/prgrms/vouchermanagement/view/Command.java
  src/main/java/org/prgrms/vouchermanagement/view/ConsoleInput.java
  src/main/java/org/prgrms/vouchermanagement/view/ConsoleOutput.java
  src/main/java/org/prgrms/vouchermanagement/voucher/DiscountPolicy.java
  src/main/java/org/prgrms/vouchermanagement/voucher/FixedAmountVoucher.java
  src/main/java/org/prgrms/vouchermanagement/voucher/PercentDiscountVoucher.java
  src/main/java/org/prgrms/vouchermanagement/voucher/PolicyStatus.java
  src/main/java/org/prgrms/vouchermanagement/voucher/Voucher.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/main/resources/logback.xml
  src/test/java/org/prgrms/vouchermanagement/VoucherManagementApplicationTests.java
  voucherFile/voucherFile
Labels: 🔥 매운맛, Team-Dozzi
