Repository prgrms-be-devcourse/springboot-basic, pull requests merged in 2023-06, with the labels that each got.

#643 [4기] 주홍석 프로젝트 생성 및 프레임 구성
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/org/devcourse/voucher/VoucherApplication.java
  src/main/java/org/devcourse/voucher/app/VoucherService.java
  src/main/java/org/devcourse/voucher/app/dto/VoucherDto.java
  src/main/java/org/devcourse/voucher/domain/voucher/DiscountAmount.java
  src/main/java/org/devcourse/voucher/domain/voucher/Voucher.java
  src/main/java/org/devcourse/voucher/domain/voucher/VoucherType.java
  src/main/java/org/devcourse/voucher/domain/voucher/repository/VoucherRepository.java
  src/main/resources/application.properties
Labels: 🔥 매운맛, Team-Ray

#649 [4기] 주홍석 도메인 객체 구현 - Voucher
  src/main/java/org/devcourse/voucher/app/VoucherService.java
  src/main/java/org/devcourse/voucher/console/dto/VoucherDto.java
  src/main/java/org/devcourse/voucher/domain/voucher/DiscountAmount.java
  src/main/java/org/devcourse/voucher/domain/voucher/DiscountVoucher.java
  src/main/java/org/devcourse/voucher/domain/voucher/FixedAmountVoucher.java
  src/main/java/org/devcourse/voucher/domain/voucher/Money.java
  src/main/java/org/devcourse/voucher/domain/voucher/PercentDiscountVoucher.java
  src/main/java/org/devcourse/voucher/domain/voucher/Voucher.java
  src/main/java/org/devcourse/voucher/domain/voucher/VoucherType.java
  src/main/java/org/devcourse/voucher/repository/VoucherRepository.java
Labels: 🔥 매운맛, Team-Ray

#661 [4기] 고범준 바우처 설계 및 바우처 개발
  .gitignore
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/dev/bootbasic/BootBasicApplication.java
  src/main/java/com/dev/bootbasic/voucher/domain/FixedAmountVoucher.java
  src/main/java/com/dev/bootbasic/voucher/domain/PercentDiscountVoucher.java
  src/main/java/com/dev/bootbasic/voucher/domain/Voucher.java
  src/main/resources/application.properties
  src/test/java/com/dev/bootbasic/voucher/domain/FixedAmountVoucherTest.java
  src/test/java/com/dev/bootbasic/voucher/domain/PercentDiscountVoucherTest.java
Labels: 🔥 매운맛, Team-Seunghoon

#654 [4기] 박현지 프로젝트 생성 및 주요 구조 잡기
  voucher/.gitignore
  voucher/build.gradle
  voucher/gradle/wrapper/gradle-wrapper.jar
  voucher/gradle/wrapper/gradle-wrapper.properties
  voucher/gradlew
  voucher/gradlew.bat
  voucher/settings.gradle
  voucher/src/main/java/org/prgms/voucher/FixedAmount.java
  voucher/src/main/java/org/prgms/voucher/PercentAmount.java
  voucher/src/main/java/org/prgms/voucher/Voucher.java
  voucher/src/main/java/org/prgms/voucher/VoucherApplication.java
  voucher/src/main/java/org/prgms/voucher/VoucherRepository.java
  voucher/src/main/java/org/prgms/voucher/VoucherService.java
  voucher/src/main/resources/application.properties
Labels: 🔥 매운맛, Team-Ray

#646 [4기 - 김범석] Spring Boot Basic 1W part1
  voucher/.gitignore
  voucher/build.gradle
  voucher/gradle/wrapper/gradle-wrapper.jar
  voucher/gradle/wrapper/gradle-wrapper.properties
  voucher/gradlew
  voucher/gradlew.bat
  voucher/settings.gradle
  voucher/src/main/java/com/programmers/voucher/CommandLineApplication.java
  voucher/src/main/java/com/programmers/voucher/VoucherApplication.java
  voucher/src/main/java/com/programmers/voucher/configuration/AppConfiguration.java
  voucher/src/main/java/com/programmers/voucher/console/Console.java
  voucher/src/main/java/com/programmers/voucher/console/TextIoConsole.java
  voucher/src/main/java/com/programmers/voucher/domain/Type.java
  voucher/src/main/java/com/programmers/voucher/domain/voucher/FixedAmountVoucher.java
  voucher/src/main/java/com/programmers/voucher/domain/voucher/PercentDiscountVoucher.java
  voucher/src/main/java/com/programmers/voucher/domain/voucher/Voucher.java
  voucher/src/main/java/com/programmers/voucher/domain/voucher/VoucherEnum.java
  voucher/src/main/java/com/programmers/voucher/domain/voucher/VoucherFactory.java
  voucher/src/main/java/com/programmers/voucher/stream/BlackListStream.java
  voucher/src/main/java/com/programmers/voucher/stream/CsvBlackListStream.java
  voucher/src/main/java/com/programmers/voucher/stream/CsvVoucherStream.java
  voucher/src/main/java/com/programmers/voucher/stream/MemoryVoucherStream.java
  voucher/src/main/java/com/programmers/voucher/stream/VoucherStream.java
  voucher/src/main/resources/application.properties
  voucher/src/main/resources/customer_blacklist.csv
  voucher/src/main/resources/sample.csv
  voucher/src/test/java/com/programmers/voucher/VoucherApplicationTests.java
  voucher/src/test/java/com/programmers/voucher/domain/TypeTest.java
  voucher/src/test/java/com/programmers/voucher/domain/voucher/VoucherEnumTest.java
  voucher/src/test/java/com/programmers/voucher/stream/MemoryVoucherStreamTest.java
Labels: 🔥 매운맛, Team-Allen

#647 [4기 - 박형진] SpringBoot Part1 Weekly Mission 첫 번째 PR 제출합니다.
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/dev/voucherproject/VoucherProjectApplication.java
  src/main/java/com/dev/voucherproject/config/ConsoleConfiguration.java
  src/main/java/com/dev/voucherproject/controller/console/ConsoleController.java
  src/main/java/com/dev/voucherproject/controller/console/CreateMenuExecutor.java
  src/main/java/com/dev/voucherproject/controller/console/ListMenuExecutor.java
  src/main/java/com/dev/voucherproject/controller/console/SelectMenuExecutor.java
  src/main/java/com/dev/voucherproject/model/menu/Menu.java
  src/main/java/com/dev/voucherproject/model/voucher/FixedAmountVoucher.java
  src/main/java/com/dev/voucherproject/model/voucher/PercentDiscountVoucher.java
  src/main/java/com/dev/voucherproject/model/voucher/Voucher.java
  src/main/java/com/dev/voucherproject/model/voucher/VoucherDataAccessor.java
  src/main/java/com/dev/voucherproject/model/voucher/VoucherDto.java
  src/main/java/com/dev/voucherproject/model/voucher/VoucherPolicy.java
  src/main/java/com/dev/voucherproject/storage/MemoryVoucherStorage.java
  src/main/java/com/dev/voucherproject/storage/VoucherStorage.java
  src/main/java/com/dev/voucherproject/view/Console.java
  src/main/resources/application.properties
  src/test/java/com/dev/voucherproject/VoucherProjectApplicationTests.java
Labels: 🔥 매운맛, Team-Allen

#650 [4기 - 문종운] SpringBoot Part1 Weekly Mission 첫 번째 PR 제출합니다.
  .gitignore
  .idea/.name
  .idea/compiler.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/vcs.xml
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/prgms/VoucherApp/VoucherAppApplication.java
  src/main/java/com/prgms/VoucherApp/config/IOConfiguration.java
  src/main/java/com/prgms/VoucherApp/controller/VoucherApp.java
  src/main/java/com/prgms/VoucherApp/domain/FixedAmountVoucher.java
  src/main/java/com/prgms/VoucherApp/domain/PercentDiscountVoucher.java
  src/main/java/com/prgms/VoucherApp/domain/Voucher.java
  src/main/java/com/prgms/VoucherApp/domain/VoucherCreator.java
  src/main/java/com/prgms/VoucherApp/domain/VoucherPolicy.java
  src/main/java/com/prgms/VoucherApp/domain/VoucherReader.java
  src/main/java/com/prgms/VoucherApp/storage/VoucherMemoryStorage.java
  src/main/java/com/prgms/VoucherApp/storage/VoucherStorage.java
  src/main/java/com/prgms/VoucherApp/view/Command.java
  src/main/java/com/prgms/VoucherApp/view/Input.java
  src/main/java/com/prgms/VoucherApp/view/Output.java
  src/main/java/com/prgms/VoucherApp/view/console/ConsoleInputView.java
  src/main/java/com/prgms/VoucherApp/view/console/ConsoleOutputView.java
  src/main/resources/application.properties
  src/main/resources/banner.txt
  src/main/resources/logback.xml
  src/test/java/com/prgms/VoucherApp/VoucherAppApplicationTests.java
  src/test/java/com/prgms/VoucherApp/domain/VoucherCreatorTest.java
  src/test/java/com/prgms/VoucherApp/domain/VoucherTest.java
  src/test/java/com/prgms/VoucherApp/storage/VoucherMemoryStorageTest.java
Labels: 🔥 매운맛, Team-Allen

#653 [4기 - 한희나] SpringBoot Part1 Weekly Mission 첫 번째 PR 제출합니다.
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/prgms/springbootbasic/AppConfig.java
  src/main/java/com/prgms/springbootbasic/CommandLineApplication.java
  src/main/java/com/prgms/springbootbasic/SpringbootBasicApplication.java
  src/main/java/com/prgms/springbootbasic/controller/VoucherController.java
  src/main/java/com/prgms/springbootbasic/exception/DuplicationKeyException.java
  src/main/java/com/prgms/springbootbasic/exception/NoSuchMenuException.java
  src/main/java/com/prgms/springbootbasic/exception/NoSuchVoucherTypeException.java
  src/main/java/com/prgms/springbootbasic/exception/OutOfRangePercentException.java
  src/main/java/com/prgms/springbootbasic/exception/UnderMinimumAmountException.java
  src/main/java/com/prgms/springbootbasic/model/FixedAmountVoucher.java
  src/main/java/com/prgms/springbootbasic/model/PercentAmountVoucher.java
  src/main/java/com/prgms/springbootbasic/model/Voucher.java
  src/main/java/com/prgms/springbootbasic/model/VouchersInMemory.java
  src/main/java/com/prgms/springbootbasic/ui/Console.java
  src/main/java/com/prgms/springbootbasic/ui/InputView.java
  src/main/java/com/prgms/springbootbasic/ui/OutputView.java
  src/main/java/com/prgms/springbootbasic/util/Menu.java
  src/main/java/com/prgms/springbootbasic/util/VoucherType.java
  src/main/resources/application.properties
  src/test/java/com/prgms/springbootbasic/SpringbootBasicApplicationTests.java
Labels: 🔥 매운맛, Team-Allen

#652 [4기 - 박은지] SpringBoot Part1 Weekly Mission 첫 번째 PR 제출합니다.
  .gitignore
  .idea/.gitignore
  .idea/.name
  .idea/compiler.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/vcs.xml
  HELP.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/prgrms/commandLineApplication/CommandLineApplication.java
  src/main/java/com/prgrms/commandLineApplication/repository/MemoryVoucherRepository.java
  src/main/java/com/prgrms/commandLineApplication/repository/VoucherRepository.java
  src/main/java/com/prgrms/commandLineApplication/service/VoucherService.java
  src/main/java/com/prgrms/commandLineApplication/voucher/FixedAmountVoucher.java
  src/main/java/com/prgrms/commandLineApplication/voucher/PercentDiscountVoucher.java
  src/main/java/com/prgrms/commandLineApplication/voucher/Voucher.java
  src/main/resources/application.properties
  src/test/java/com/prgrms/commandLineApplication/CommandLineApplicationTests.java
  src/test/java/com/prgrms/commandLineApplication/voucher/FixedAmountVoucherTest.java
  src/test/java/com/prgrms/commandLineApplication/voucher/PercentDiscountVoucherTest.java
Labels: 🔥 매운맛, Team-Seunghoon

#676 [4기] 고범준 바우처 생성 로직 및 조회 로직
  src/main/java/com/dev/bootbasic/voucher/domain/FixedAmountVoucher.java
  src/main/java/com/dev/bootbasic/voucher/domain/PercentDiscountVoucher.java
  src/main/java/com/dev/bootbasic/voucher/domain/Voucher.java
  src/main/java/com/dev/bootbasic/voucher/domain/VoucherFactory.java
  src/main/java/com/dev/bootbasic/voucher/domain/VoucherType.java
  src/main/java/com/dev/bootbasic/voucher/dto/VoucherCreateRequest.java
  src/main/java/com/dev/bootbasic/voucher/dto/VoucherDetailsResponse.java
  src/main/java/com/dev/bootbasic/voucher/repository/InMemoryVoucherRepository.java
  src/main/java/com/dev/bootbasic/voucher/repository/VoucherRepository.java
  src/main/java/com/dev/bootbasic/voucher/service/VoucherService.java
  src/test/java/com/dev/bootbasic/voucher/domain/FixedAmountVoucherTest.java
  src/test/java/com/dev/bootbasic/voucher/domain/VoucherFactoryTest.java
  src/test/java/com/dev/bootbasic/voucher/repository/InMemoryVoucherRepositoryTest.java
  src/test/java/com/dev/bootbasic/voucher/service/VoucherServiceTest.java
Labels: 🔥 매운맛, Team-Seunghoon

#657 [4기 - 유명한] 기능 단위 PR 제출합니다.
  .gitignore
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/programmers/voucher/AppConfiguration.java
  src/main/java/com/programmers/voucher/VoucherApplication.java
  src/main/java/com/programmers/voucher/domain/FixedAmountVoucher.java
  src/main/java/com/programmers/voucher/domain/PercentDiscountVoucher.java
  src/main/java/com/programmers/voucher/domain/Voucher.java
  src/main/java/com/programmers/voucher/domain/VoucherFactory.java
  src/main/java/com/programmers/voucher/domain/VoucherType.java
  src/main/java/com/programmers/voucher/dto/reponse/VoucherInfoResponse.java
  src/main/java/com/programmers/voucher/dto/request/VoucherCreationRequest.java
  src/main/java/com/programmers/voucher/repository/MemoryVoucherRepository.java
  src/main/java/com/programmers/voucher/repository/VoucherRepository.java
  src/main/java/com/programmers/voucher/service/VoucherService.java
  src/test/java/com/programmers/voucher/domain/FixedAmountVoucherTest.java
  src/test/java/com/programmers/voucher/domain/PercentDiscountVoucherTest.java
  src/test/java/com/programmers/voucher/repository/MemoryVoucherRepositoryTest.java
  src/test/java/com/programmers/voucher/service/VoucherServiceTest.java
Labels: 🔥 매운맛, Team-Seunghoon

#683 [4기-황준호] 프로젝트 Setting 및 전체적 구조 확립
  README.md
  voucher/.gitignore
  voucher/README.md
  voucher/build.gradle
  voucher/settings.gradle
  voucher/src/main/java/com/ray/junho/voucher/VoucherApplication.java
  voucher/src/main/java/com/ray/junho/voucher/domain/Currency.java
  voucher/src/main/java/com/ray/junho/voucher/domain/Voucher.java
  voucher/src/main/java/com/ray/junho/voucher/repository/VoucherRepository.java
  voucher/src/main/java/com/ray/junho/voucher/service/VoucherService.java
  voucher/src/main/resources/application.properties
Labels: 🔥 매운맛, Team-Ray

#688 [4기-김재웅] SpringBoot Part1 Weekly Mission 첫 번째 PR 제출합니다.
  .DS_Store
  README.md
  kdt-spring-voucher/.DS_Store
  kdt-spring-voucher/.gitignore
  kdt-spring-voucher/.mvn/wrapper/maven-wrapper.properties
  kdt-spring-voucher/mvnw
  kdt-spring-voucher/mvnw.cmd
  kdt-spring-voucher/pom.xml
  kdt-spring-voucher/src/main/java/org/prgrms/kdt/AppConfiguration.java
  kdt-spring-voucher/src/main/java/org/prgrms/kdt/KdtApplication.java
  kdt-spring-voucher/src/main/java/org/prgrms/kdt/VoucherApp.java
  kdt-spring-voucher/src/main/java/org/prgrms/kdt/controller/VoucherController.java
  kdt-spring-voucher/src/main/java/org/prgrms/kdt/database/MemoryVoucherDatabase.java
  kdt-spring-voucher/src/main/java/org/prgrms/kdt/database/VoucherDatabase.java
  kdt-spring-voucher/src/main/java/org/prgrms/kdt/input/MenuCommand.java
  kdt-spring-voucher/src/main/java/org/prgrms/kdt/input/UserInput.java
  kdt-spring-voucher/src/main/java/org/prgrms/kdt/input/UserInputMenu.java
  kdt-spring-voucher/src/main/java/org/prgrms/kdt/input/VoucherCommand.java
  kdt-spring-voucher/src/main/java/org/prgrms/kdt/output/Output.java
  kdt-spring-voucher/src/main/java/org/prgrms/kdt/output/OutputConsole.java
  kdt-spring-voucher/src/main/java/org/prgrms/kdt/voucher/FixedAmountVoucher.java
  kdt-spring-voucher/src/main/java/org/prgrms/kdt/voucher/PercentDiscountVoucher.java
  kdt-spring-voucher/src/main/java/org/prgrms/kdt/voucher/Voucher.java
  kdt-spring-voucher/src/main/resources/application.properties
  kdt-spring-voucher/src/test/java/org/prgrms/kdt/KdtApplicationTests.java
  kdt-spring-voucher/src/test/java/org/prgrms/kdt/database/VoucherDatabaseTest.java
Labels: 🔥 매운맛, Team-Allen

#656 [4기] 주홍석 도메인 객체 구현 - Voucher
  src/main/java/org/devcourse/voucher/console/dto/VoucherDto.java
  src/main/java/org/devcourse/voucher/domain/voucher/DiscountVoucher.java
  src/main/java/org/devcourse/voucher/domain/voucher/FixedAmountVoucher.java
  src/main/java/org/devcourse/voucher/domain/voucher/Money.java
  src/main/java/org/devcourse/voucher/domain/voucher/PercentDiscountVoucher.java
  src/main/java/org/devcourse/voucher/domain/voucher/Voucher.java
  src/main/java/org/devcourse/voucher/domain/voucher/VoucherType.java
  src/main/java/org/devcourse/voucher/domain/voucher/policy/DiscountPolicy.java
  src/main/java/org/devcourse/voucher/domain/voucher/policy/FixedDiscountPolicy.java
  src/main/java/org/devcourse/voucher/domain/voucher/policy/PercentDiscountPolicy.java
Labels: 🔥 매운맛, Team-Ray

#682 [4기 - 박현지] Voucher, Command-line Application 구조 설계 및 구현
  voucher/src/main/java/org/prgms/voucher/AmountType.java
  voucher/src/main/java/org/prgms/voucher/CommandLineApplication.java
  voucher/src/main/java/org/prgms/voucher/Console.java
  voucher/src/main/java/org/prgms/voucher/MemoryVoucherRepository.java
  voucher/src/main/java/org/prgms/voucher/VoucherCreateDto.java
  voucher/src/main/java/org/prgms/voucher/VoucherRepository.java
  voucher/src/main/java/org/prgms/voucher/VoucherService.java
Labels: Team-Ray

#660 [4기 - 박상민] SpringBoot Part1 Weekly Mission 첫 번째 PR 제출합니다.
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/programmers/springbootbasic/SpringbootBasicApplication.java
  src/main/java/com/programmers/springbootbasic/domain/voucher/FixedAmountVoucher.java
  src/main/java/com/programmers/springbootbasic/domain/voucher/PercentDiscountVoucher.java
  src/main/java/com/programmers/springbootbasic/domain/voucher/Voucher.java
  src/main/resources/application.properties
  src/test/java/com/programmers/springbootbasic/SpringbootBasicApplicationTests.java
  src/test/java/com/programmers/springbootbasic/domain/voucher/FixedAmountVoucherTest.java
  src/test/java/com/programmers/springbootbasic/domain/voucher/PercentDiscountVoucherTest.java
  src/test/java/com/programmers/springbootbasic/domain/voucher/VoucherTest.java
Labels: 🔥 매운맛, Team-Seunghoon

#694 [4기] 고범준 3차 사용자의 콘솔 입력, 출력 구현
  README.md
  src/main/java/com/dev/bootbasic/CommandLineApplication.java
  src/main/java/com/dev/bootbasic/util/Constant.java
  src/main/java/com/dev/bootbasic/view/Command.java
  src/main/java/com/dev/bootbasic/view/InputView.java
  src/main/java/com/dev/bootbasic/view/OutputView.java
  src/main/java/com/dev/bootbasic/view/ViewManager.java
  src/main/java/com/dev/bootbasic/view/console/ConsoleInputView.java
  src/main/java/com/dev/bootbasic/view/console/ConsoleOutputView.java
  src/main/java/com/dev/bootbasic/voucher/controller/VoucherController.java
  src/main/java/com/dev/bootbasic/voucher/domain/FixedAmountVoucher.java
  src/main/java/com/dev/bootbasic/voucher/domain/PercentDiscountVoucher.java
  src/main/java/com/dev/bootbasic/voucher/domain/Voucher.java
  src/main/java/com/dev/bootbasic/voucher/domain/VoucherFactory.java
  src/main/java/com/dev/bootbasic/voucher/domain/VoucherType.java
  src/main/java/com/dev/bootbasic/voucher/dto/VoucherDetailsResponse.java
  src/main/java/com/dev/bootbasic/voucher/repository/InMemoryVoucherRepository.java
  src/main/java/com/dev/bootbasic/voucher/repository/VoucherRepository.java
  src/main/java/com/dev/bootbasic/voucher/service/VoucherService.java
  src/test/java/com/dev/bootbasic/voucher/domain/PercentDiscountVoucherTest.java
  src/test/java/com/dev/bootbasic/voucher/domain/VoucherFactoryTest.java
  src/test/java/com/dev/bootbasic/voucher/repository/InMemoryVoucherRepositoryTest.java
  src/test/java/com/dev/bootbasic/voucher/service/VoucherServiceTest.java
Labels: 🔥 매운맛, Team-Seunghoon

#662 [4기-C] 김도연 SpringBoot Part1 Weekly Mission 첫 번째 PR 제출합니다.
  .gitignore
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/com/example/demo/common/AppConfiguration.java
  src/main/java/com/example/demo/common/io/Input.java
  src/main/java/com/example/demo/common/io/Output.java
  src/main/java/com/example/demo/common/io/impl/ConsoleInput.java
  src/main/java/com/example/demo/common/io/impl/ConsoleOutput.java
  src/main/java/com/example/demo/voucher/application/VoucherService.java
  src/main/java/com/example/demo/voucher/application/VoucherType.java
  src/main/java/com/example/demo/voucher/domain/FixedAmountVoucher.java
  src/main/java/com/example/demo/voucher/domain/PercentDiscountVoucher.java
  src/main/java/com/example/demo/voucher/domain/Voucher.java
  src/main/java/com/example/demo/voucher/domain/repository/VoucherRepository.java
  src/main/java/com/example/demo/voucher/infrastructure/MemoryRepository.java
  src/main/java/com/example/demo/voucher/presentation/VoucherRunner.java
  src/main/java/com/example/demo/voucher/presentation/command/VoucherCommand.java
  src/main/java/com/example/demo/voucher/presentation/command/impl/CreateCommand.java
  src/main/java/com/example/demo/voucher/presentation/command/impl/ListCommand.java
  src/main/java/com/example/demo/voucher/presentation/message/VoucherTypeMessage.java
  src/main/java/com/example/demo/voucher/presentation/message/VoucherTypeMessageMapper.java
  src/main/resources/application.properties
  src/test/java/com/example/demo/Demo1ApplicationTests.java
Labels: 💧 순한맛, 🔥 매운맛, Team-Allen

#648 [4기 - 이근우] SpringBoot Part1 Weekly Mission PR 제출합니다.
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/org/programers/vouchermanagement/VoucherManagementApplication.java
  src/main/java/org/programers/vouchermanagement/VoucherManagementController.java
  src/main/java/org/programers/vouchermanagement/docs/specification.md
  src/main/java/org/programers/vouchermanagement/member/application/MemberService.java
  src/main/java/org/programers/vouchermanagement/member/domain/Member.java
  src/main/java/org/programers/vouchermanagement/member/domain/MemberRepository.java
  src/main/java/org/programers/vouchermanagement/member/domain/MemberStatus.java
  src/main/java/org/programers/vouchermanagement/member/dto/MemberResponse.java
  src/main/java/org/programers/vouchermanagement/member/dto/MembersResponse.java
  src/main/java/org/programers/vouchermanagement/member/exception/NoSuchMemberException.java
  src/main/java/org/programers/vouchermanagement/member/presentation/MemberController.java
  src/main/java/org/programers/vouchermanagement/util/Converter.java
  src/main/java/org/programers/vouchermanagement/view/Command.java
  src/main/java/org/programers/vouchermanagement/view/DiscountPolicyType.java
  src/main/java/org/programers/vouchermanagement/view/InputView.java
  src/main/java/org/programers/vouchermanagement/view/OutputView.java
  src/main/java/org/programers/vouchermanagement/voucher/application/VoucherService.java
  src/main/java/org/programers/vouchermanagement/voucher/domain/FixedAmountPolicy.java
  src/main/java/org/programers/vouchermanagement/voucher/domain/InFileVoucherRepository.java
  src/main/java/org/programers/vouchermanagement/voucher/domain/InMemoryVoucherRepository.java
  src/main/java/org/programers/vouchermanagement/voucher/domain/PercentDiscountPolicy.java
  src/main/java/org/programers/vouchermanagement/voucher/domain/Voucher.java
  src/main/java/org/programers/vouchermanagement/voucher/domain/VoucherPolicy.java
  src/main/java/org/programers/vouchermanagement/voucher/domain/VoucherRepository.java
  src/main/java/org/programers/vouchermanagement/voucher/domain/VoucherType.java
  src/main/java/org/programers/vouchermanagement/voucher/dto/VoucherCreationRequest.java
  src/main/java/org/programers/vouchermanagement/voucher/dto/VoucherResponse.java
  src/main/java/org/programers/vouchermanagement/voucher/dto/VouchersResponse.java
  src/main/java/org/programers/vouchermanagement/voucher/exception/NoSuchVoucherException.java
  src/main/java/org/programers/vouchermanagement/voucher/exception/WrongVoucherPolicyException.java
  src/main/java/org/programers/vouchermanagement/voucher/presentation/VoucherController.java
  src/main/resources/application-dev.yaml
  src/main/resources/application.yaml
  src/main/resources/blacklist.csv
  src/main/resources/logback.xml
  src/test/java/org/programers/vouchermanagement/DemoApplicationTests.java
  src/test/java/org/programers/vouchermanagement/voucher/domain/FixedAmountPolicyTest.java
  src/test/java/org/programers/vouchermanagement/voucher/domain/PercentDiscountPolicyTest.java
  src/test/java/org/programers/vouchermanagement/voucher/domain/VoucherTest.java
Labels: 🔥 매운맛, Team-F

#712 [4기] 주홍석 Voucher 도메인 테스트 코드 작성
  src/main/java/org/devcourse/voucher/domain/voucher/VoucherType.java
  src/main/java/org/devcourse/voucher/domain/voucher/policy/FixedDiscountPolicy.java
  src/test/java/org/devcourse/voucher/domain/voucher/VoucherTest.java
  src/test/java/org/devcourse/voucher/domain/voucher/VoucherTypeTest.java
  src/test/java/org/devcourse/voucher/domain/voucher/policy/FixedDiscountPolicyTest.java
  src/test/java/org/devcourse/voucher/domain/voucher/policy/PercentDiscountPolicyTest.java
Labels: 🔥 매운맛, Team-Ray

#701 [4기 - 박은지] 2차 바우처 생성 및 조회 로직 구현
  .gitignore
  .idea/.name
  .idea/misc.xml
  src/main/java/com/prgrms/commandLineApplication/VoucherController.java
  src/main/java/com/prgrms/commandLineApplication/io/Input.java
  src/main/java/com/prgrms/commandLineApplication/io/Output.java
  src/main/java/com/prgrms/commandLineApplication/repository/MemoryVoucherRepository.java
  src/main/java/com/prgrms/commandLineApplication/repository/VoucherRepository.java
  src/main/java/com/prgrms/commandLineApplication/service/VoucherService.java
  src/main/java/com/prgrms/commandLineApplication/voucher/FixedAmountVoucher.java
  src/main/java/com/prgrms/commandLineApplication/voucher/PercentDiscountVoucher.java
  src/main/java/com/prgrms/commandLineApplication/voucher/Voucher.java
  src/main/java/com/prgrms/commandLineApplication/voucher/VoucherFactory.java
  src/main/java/com/prgrms/commandLineApplication/voucher/VoucherType.java
  src/main/java/com/prgrms/commandLineApplication/voucher/VoucherValidator.java
  src/test/java/com/prgrms/commandLineApplication/service/VoucherServiceTest.java
  src/test/java/com/prgrms/commandLineApplication/voucher/FixedAmountVoucherTest.java
  src/test/java/com/prgrms/commandLineApplication/voucher/PercentDiscountVoucherTest.java
Labels: 🔥 매운맛, Team-Seunghoon

#669 [4기 - 이홍섭] SpringBoot Part1 Weekly Mission 첫 번째 PR 제출합니다.
  .gitignore
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  logs/error.log
  settings.gradle
  src/main/java/org/promgrammers/springbootbasic/VoucherManagementApplication.java
  src/main/java/org/promgrammers/springbootbasic/config/AppConfig.java
  src/main/java/org/promgrammers/springbootbasic/controller/CommandLineController.java
  src/main/java/org/promgrammers/springbootbasic/controller/CommandProgramStatus.java
  src/main/java/org/promgrammers/springbootbasic/domain/customer/dto/response/CustomerResponse.java
  src/main/java/org/promgrammers/springbootbasic/domain/customer/dto/response/CustomersResponse.java
  src/main/java/org/promgrammers/springbootbasic/domain/customer/model/Customer.java
  src/main/java/org/promgrammers/springbootbasic/domain/customer/model/CustomerType.java
  src/main/java/org/promgrammers/springbootbasic/domain/customer/repository/CustomerRepository.java
  src/main/java/org/promgrammers/springbootbasic/domain/customer/service/CustomerService.java
  src/main/java/org/promgrammers/springbootbasic/domain/voucher/dto/request/CreateVoucherRequest.java
  src/main/java/org/promgrammers/springbootbasic/domain/voucher/dto/response/VoucherListResponse.java
  src/main/java/org/promgrammers/springbootbasic/domain/voucher/dto/response/VoucherResponse.java
  src/main/java/org/promgrammers/springbootbasic/domain/voucher/model/Command.java
  src/main/java/org/promgrammers/springbootbasic/domain/voucher/model/FixedAmountVoucher.java
  src/main/java/org/promgrammers/springbootbasic/domain/voucher/model/PercentDiscountVoucher.java
  src/main/java/org/promgrammers/springbootbasic/domain/voucher/model/Voucher.java
  src/main/java/org/promgrammers/springbootbasic/domain/voucher/model/VoucherType.java
  src/main/java/org/promgrammers/springbootbasic/domain/voucher/repository/FileVoucherRepository.java
  src/main/java/org/promgrammers/springbootbasic/domain/voucher/repository/MemoryVoucherRepository.java
  src/main/java/org/promgrammers/springbootbasic/domain/voucher/repository/VoucherRepository.java
  src/main/java/org/promgrammers/springbootbasic/domain/voucher/service/VoucherFactory.java
  src/main/java/org/promgrammers/springbootbasic/domain/voucher/service/VoucherService.java
  src/main/java/org/promgrammers/springbootbasic/exception/DuplicateIDException.java
  src/main/java/org/promgrammers/springbootbasic/exception/EmptyListException.java
  src/main/java/org/promgrammers/springbootbasic/exception/InvalidFilePathException.java
  src/main/java/org/promgrammers/springbootbasic/exception/VoucherFileWriteException.java
  src/main/java/org/promgrammers/springbootbasic/util/FileConverter.java
  src/main/java/org/promgrammers/springbootbasic/view/Console.java
  src/main/java/org/promgrammers/springbootbasic/view/Input.java
  src/main/java/org/promgrammers/springbootbasic/view/Output.java
  src/main/java/org/promgrammers/springbootbasic/view/Reader.java
  src/main/java/org/promgrammers/springbootbasic/view/Writer.java
  src/main/resources/application.yaml
  src/main/resources/logback.xml
  src/main/resources/storage/blacklist.csv
  src/main/resources/storage/voucherStorage.txt
  src/test/java/org/promgrammers/springbootbasic/SpringbootBasicApplicationTests.java
  src/test/java/org/promgrammers/springbootbasic/controller/CommandProgramStatusTest.java
  src/test/java/org/promgrammers/springbootbasic/controller/CommandTest.java
  src/test/java/org/promgrammers/springbootbasic/domain/customer/repository/CustomerRepositoryTest.java
  src/test/java/org/promgrammers/springbootbasic/domain/customer/service/CustomerServiceTest.java
  src/test/java/org/promgrammers/springbootbasic/domain/voucher/model/FixedAmountVoucherTest.java
  src/test/java/org/promgrammers/springbootbasic/domain/voucher/model/PercentDiscountVoucherTest.java
  src/test/java/org/promgrammers/springbootbasic/domain/voucher/model/VoucherTypeTest.java
  src/test/java/org/promgrammers/springbootbasic/domain/voucher/repository/FileVoucherRepositoryTest.java
  src/test/java/org/promgrammers/springbootbasic/domain/voucher/repository/MemoryVoucherRepositoryTest.java
  src/test/java/org/promgrammers/springbootbasic/domain/voucher/service/VoucherFactoryTest.java
  src/test/java/org/promgrammers/springbootbasic/domain/voucher/service/VoucherServiceTest.java
  src/test/java/org/promgrammers/springbootbasic/util/FileConverterTest.java
Labels: 🔥 매운맛, Team-F

#658 [4기 - 고예성] SpringBoot Part1 Weekly Mission PR 제출합니다.
  .gitignore
  build.gradle
  docs/README.md
  docs/스크린샷 2023-06-28 오전 1.26.36.png
  docs/스크린샷 2023-06-28 오전 1.26.57.png
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/kr/co/programmers/springbootbasic/Processor.java
  src/main/java/kr/co/programmers/springbootbasic/SpringbootBasicApplication.java
  src/main/java/kr/co/programmers/springbootbasic/customer/Customer.java
  src/main/java/kr/co/programmers/springbootbasic/customer/CustomerRepository.java
  src/main/java/kr/co/programmers/springbootbasic/customer/CustomerService.java
  src/main/java/kr/co/programmers/springbootbasic/customer/CustomerStatus.java
  src/main/java/kr/co/programmers/springbootbasic/customer/impl/CsvCustomer.java
  src/main/java/kr/co/programmers/springbootbasic/customer/impl/CsvCustomerRepository.java
  src/main/java/kr/co/programmers/springbootbasic/dto/CustomerResponseDto.java
  src/main/java/kr/co/programmers/springbootbasic/dto/VoucherRequestDto.java
  src/main/java/kr/co/programmers/springbootbasic/dto/VoucherResponseDto.java
  src/main/java/kr/co/programmers/springbootbasic/exception/FileConvertFailException.java
  src/main/java/kr/co/programmers/springbootbasic/exception/FileRepositoryInitException.java
  src/main/java/kr/co/programmers/springbootbasic/exception/FileSaveFailException.java
  src/main/java/kr/co/programmers/springbootbasic/exception/NoValidAmountException.java
  src/main/java/kr/co/programmers/springbootbasic/exception/NoValidCommandException.java
  src/main/java/kr/co/programmers/springbootbasic/exception/NoValidDiscountPrice.java
  src/main/java/kr/co/programmers/springbootbasic/io/ConsoleIO.java
  src/main/java/kr/co/programmers/springbootbasic/io/ConsoleMessage.java
  src/main/java/kr/co/programmers/springbootbasic/io/Input.java
  src/main/java/kr/co/programmers/springbootbasic/io/MenuCommand.java
  src/main/java/kr/co/programmers/springbootbasic/io/Output.java
  src/main/java/kr/co/programmers/springbootbasic/util/ApplicationUtils.java
  src/main/java/kr/co/programmers/springbootbasic/voucher/FileVoucherRepositoryProperties.java
  src/main/java/kr/co/programmers/springbootbasic/voucher/Voucher.java
  src/main/java/kr/co/programmers/springbootbasic/voucher/VoucherRepository.java
  src/main/java/kr/co/programmers/springbootbasic/voucher/VoucherService.java
  src/main/java/kr/co/programmers/springbootbasic/voucher/VoucherType.java
  src/main/java/kr/co/programmers/springbootbasic/voucher/impl/FileVoucherRepository.java
  src/main/java/kr/co/programmers/springbootbasic/voucher/impl/FixedAmountVoucher.java
  src/main/java/kr/co/programmers/springbootbasic/voucher/impl/MemoryVoucherRepository.java
  src/main/java/kr/co/programmers/springbootbasic/voucher/impl/PercentAmountVoucher.java
  src/main/resources/application-deploy.yml
  src/main/resources/application-dev.yml
  src/main/resources/banner.txt
  src/main/resources/customer_blacklist.csv
  src/main/resources/logback.xml
Labels: 🔥 매운맛, Team-F

#700 스프링 부트 강의 1W 2nd PR 요청합니다.
  voucher/src/main/java/com/programmers/voucher/CommandLineApplication.java
  voucher/src/main/java/com/programmers/voucher/VoucherApplication.java
  voucher/src/main/java/com/programmers/voucher/configuration/AppConfiguration.java
  voucher/src/main/java/com/programmers/voucher/console/Console.java
  voucher/src/main/java/com/programmers/voucher/console/Printer.java
  voucher/src/main/java/com/programmers/voucher/console/PrinterImpl.java
  voucher/src/main/java/com/programmers/voucher/console/TextIoConsole.java
  voucher/src/main/java/com/programmers/voucher/domain/CommandType.java
  voucher/src/main/java/com/programmers/voucher/domain/Type.java
  voucher/src/main/java/com/programmers/voucher/domain/voucher/FixedAmountVoucher.java
  voucher/src/main/java/com/programmers/voucher/domain/voucher/VoucherEnum.java
  voucher/src/main/java/com/programmers/voucher/domain/voucher/VoucherFactory.java
  voucher/src/main/java/com/programmers/voucher/stream/BlackListStream.java
  voucher/src/main/java/com/programmers/voucher/stream/CsvBlackListStream.java
  voucher/src/main/java/com/programmers/voucher/stream/CsvVoucherStream.java
  voucher/src/main/resources/application.properties
  voucher/src/main/resources/application.yaml
  voucher/src/main/resources/logback.xml
  voucher/src/test/java/com/programmers/voucher/VoucherApplicationTests.java
  voucher/src/test/java/com/programmers/voucher/domain/CommandTypeTest.java
  voucher/src/test/java/com/programmers/voucher/domain/TypeTest.java
  voucher/src/test/java/com/programmers/voucher/domain/voucher/VoucherEnumTest.java
Labels: Team-Allen

#659 [4기 - 나영경] SpringBoot Part1 Weekly Mission 첫 번째 PR 제출합니다.
  voucher/.gitignore
  voucher/build.gradle
  voucher/gradle/wrapper/gradle-wrapper.jar
  voucher/gradle/wrapper/gradle-wrapper.properties
  voucher/gradlew
  voucher/gradlew.bat
  voucher/settings.gradle
  voucher/src/main/java/org/devcourse/voucher/VoucherApplication.java
  voucher/src/main/java/org/devcourse/voucher/console/Command.java
  voucher/src/main/java/org/devcourse/voucher/console/CommandLineApplication.java
  voucher/src/main/java/org/devcourse/voucher/console/Console.java
  voucher/src/main/java/org/devcourse/voucher/console/Input.java
  voucher/src/main/java/org/devcourse/voucher/console/Output.java
  voucher/src/main/java/org/devcourse/voucher/domain/FixedAmountVoucher.java
  voucher/src/main/java/org/devcourse/voucher/domain/PercentDiscountVoucher.java
  voucher/src/main/java/org/devcourse/voucher/domain/Voucher.java
  voucher/src/main/java/org/devcourse/voucher/domain/VoucherType.java
  voucher/src/main/resources/application.properties
  voucher/src/test/java/org/devcourse/voucher/console/CommandLineApplicationTest.java
  voucher/src/test/java/org/devcourse/voucher/domain/FixedAmountVoucherTest.java
  voucher/src/test/java/org/devcourse/voucher/domain/PercentDiscountVoucherTest.java
Labels: 💧 순한맛, Team-Seunghoon
