Repository prgrms-be-devcourse/springboot-basic, pull requests merged in 2023-11, with the labels that each got.

#931 [5기 엄예림] SpringBoot Part2 Weekly Mission 제출합니다.
  .gitignore
  HELP.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  logs/error_2023-10-19.log
  settings.gradle
  src/main/java/org/programmers/springorder/SpringOrderApplication.java
  src/main/java/org/programmers/springorder/VoucherApplication.java
  src/main/java/org/programmers/springorder/console/Console.java
  src/main/java/org/programmers/springorder/constant/ErrorMessage.java
  src/main/java/org/programmers/springorder/constant/Message.java
  src/main/java/org/programmers/springorder/controller/CustomerController.java
  src/main/java/org/programmers/springorder/controller/VoucherController.java
  src/main/java/org/programmers/springorder/controller/WalletController.java
  src/main/java/org/programmers/springorder/dto/customer/CustomerRequestDto.java
  src/main/java/org/programmers/springorder/dto/customer/CustomerResponseDto.java
  src/main/java/org/programmers/springorder/dto/voucher/VoucherRequestDto.java
  src/main/java/org/programmers/springorder/dto/voucher/VoucherResponseDto.java
  src/main/java/org/programmers/springorder/dto/wallet/WalletRequestDto.java
  src/main/java/org/programmers/springorder/model/Wallet.java
  src/main/java/org/programmers/springorder/model/customer/Customer.java
  src/main/java/org/programmers/springorder/model/customer/CustomerType.java
  src/main/java/org/programmers/springorder/model/voucher/Voucher.java
  src/main/java/org/programmers/springorder/model/voucher/VoucherType.java
  src/main/java/org/programmers/springorder/repository/customer/CustomerRepository.java
  src/main/java/org/programmers/springorder/repository/customer/FileCustomerRepository.java
  src/main/java/org/programmers/springorder/repository/customer/JdbcCustomerRepository.java
  src/main/java/org/programmers/springorder/repository/voucher/FileVoucherRepository.java
  src/main/java/org/programmers/springorder/repository/voucher/JdbcVoucherRepository.java
  src/main/java/org/programmers/springorder/repository/voucher/MemoryVoucherRepository.java
  src/main/java/org/programmers/springorder/repository/voucher/VoucherRepository.java
  src/main/java/org/programmers/springorder/service/CustomerService.java
  src/main/java/org/programmers/springorder/service/VoucherService.java
  src/main/java/org/programmers/springorder/service/WalletService.java
  src/main/java/org/programmers/springorder/utils/CustomerMenuType.java
  src/main/java/org/programmers/springorder/utils/ExceptionHandler.java
  src/main/java/org/programmers/springorder/utils/MenuType.java
  src/main/java/org/programmers/springorder/utils/VoucherMenuType.java
  src/main/java/org/programmers/springorder/utils/WalletMenuType.java
  src/main/resources/application.yml
  src/main/resources/csv/customerList.csv
  src/main/resources/csv/voucher.csv
  src/main/resources/logback.xml
  src/main/resources/schema.sql
  src/test/java/org/programmers/springorder/model/CustomerTest.java
  src/test/java/org/programmers/springorder/model/VoucherTest.java
  src/test/java/org/programmers/springorder/model/VoucherTypeTest.java
  src/test/java/org/programmers/springorder/repository/JdbcCustomerRepositoryTest.java
  src/test/java/org/programmers/springorder/repository/JdbcVoucherRepositoryTest.java
  src/test/java/org/programmers/springorder/service/CustomerServiceTest.java
  src/test/java/org/programmers/springorder/service/VoucherServiceTest.java
  src/test/java/org/programmers/springorder/utils/CustomerMenuTypeTest.java
  src/test/java/org/programmers/springorder/utils/MenuTypeTest.java
  src/test/java/org/programmers/springorder/utils/VoucherMenuTypeTest.java
Labels: 🔥 매운맛, Team-Marco

#935 [5기 소승수] SpringBoot Part2 Weekly Mission 제출합니다.
  README.md
  build.gradle
  src/main/java/org/prgrms/prgrmsspring/PrgrmsSpringApplication.java
  src/main/java/org/prgrms/prgrmsspring/controller/ApplicationController.java
  src/main/java/org/prgrms/prgrmsspring/controller/CustomerController.java
  src/main/java/org/prgrms/prgrmsspring/controller/VoucherController.java
  src/main/java/org/prgrms/prgrmsspring/controller/WalletController.java
  src/main/java/org/prgrms/prgrmsspring/domain/Command.java
  src/main/java/org/prgrms/prgrmsspring/domain/ControllerManager.java
  src/main/java/org/prgrms/prgrmsspring/domain/FunctionType.java
  src/main/java/org/prgrms/prgrmsspring/domain/VoucherType.java
  src/main/java/org/prgrms/prgrmsspring/domain/command/Command.java
  src/main/java/org/prgrms/prgrmsspring/domain/command/CustomerCommand.java
  src/main/java/org/prgrms/prgrmsspring/domain/command/VoucherCommand.java
  src/main/java/org/prgrms/prgrmsspring/domain/command/WalletCommand.java
  src/main/java/org/prgrms/prgrmsspring/entity/user/Customer.java
  src/main/java/org/prgrms/prgrmsspring/entity/user/User.java
  src/main/java/org/prgrms/prgrmsspring/entity/voucher/FixedAmountVoucher.java
  src/main/java/org/prgrms/prgrmsspring/entity/voucher/PercentDiscountVoucher.java
  src/main/java/org/prgrms/prgrmsspring/entity/voucher/Voucher.java
  src/main/java/org/prgrms/prgrmsspring/entity/wallet/Wallet.java
  src/main/java/org/prgrms/prgrmsspring/exception/DataAccessException.java
  src/main/java/org/prgrms/prgrmsspring/exception/ExceptionMessage.java
  src/main/java/org/prgrms/prgrmsspring/repository/Field.java
  src/main/java/org/prgrms/prgrmsspring/repository/user/CustomerRepository.java
  src/main/java/org/prgrms/prgrmsspring/repository/user/DBCustomerRepository.java
  src/main/java/org/prgrms/prgrmsspring/repository/user/FileCustomerRepository.java
  src/main/java/org/prgrms/prgrmsspring/repository/user/FileUserRepository.java
  src/main/java/org/prgrms/prgrmsspring/repository/user/UserRepository.java
  src/main/java/org/prgrms/prgrmsspring/repository/voucher/DBVoucherRepository.java
  src/main/java/org/prgrms/prgrmsspring/repository/voucher/FileVoucherRepository.java
  src/main/java/org/prgrms/prgrmsspring/repository/voucher/InMemoryVoucherRepository.java
  src/main/java/org/prgrms/prgrmsspring/repository/voucher/VoucherRepository.java
  src/main/java/org/prgrms/prgrmsspring/repository/wallet/DBWalletRepository.java
  src/main/java/org/prgrms/prgrmsspring/repository/wallet/WalletRepository.java
  src/main/java/org/prgrms/prgrmsspring/service/CustomerService.java
  src/main/java/org/prgrms/prgrmsspring/service/UserService.java
  src/main/java/org/prgrms/prgrmsspring/service/VoucherService.java
  src/main/java/org/prgrms/prgrmsspring/service/WalletService.java
  src/main/java/org/prgrms/prgrmsspring/utils/BinaryToUUIDConverter.java
  src/main/java/org/prgrms/prgrmsspring/view/CommandLineView.java
  src/main/resources/application.yaml
  src/main/resources/customer_blacklist.csv
  src/main/resources/voucher-repo.csv
  src/test/java/org/prgrms/prgrmsspring/repository/user/DBCustomerRepositoryTest.java
  src/test/java/org/prgrms/prgrmsspring/repository/voucher/DBVoucherRepositoryTest.java
  src/test/java/org/prgrms/prgrmsspring/repository/wallet/DBWalletRepositoryTest.java
  src/test/java/org/prgrms/prgrmsspring/service/CustomerServiceTest.java
  src/test/java/org/prgrms/prgrmsspring/service/VoucherServiceTest.java
  src/test/java/org/prgrms/prgrmsspring/service/WalletServiceTest.java
  table.png
Labels: 🔥 매운맛, Team-R

#914 [5기 - 권효승] SpringBoot Part2 Weekly Mission 제출합니다.
  README.md
  build.gradle
  src/main/java/devcourse/springbootbasic/commandline/CommandLineExecutor.java
  src/main/java/devcourse/springbootbasic/commandline/console/ConsoleIOHandler.java
  src/main/java/devcourse/springbootbasic/commandline/constant/ConsoleConstants.java
  src/main/java/devcourse/springbootbasic/commandline/constant/InputMessage.java
  src/main/java/devcourse/springbootbasic/commandline/function/Function.java
  src/main/java/devcourse/springbootbasic/commandline/function/FunctionHandler.java
  src/main/java/devcourse/springbootbasic/controller/CustomerController.java
  src/main/java/devcourse/springbootbasic/controller/VoucherController.java
  src/main/java/devcourse/springbootbasic/domain/customer/Customer.java
  src/main/java/devcourse/springbootbasic/domain/voucher/Voucher.java
  src/main/java/devcourse/springbootbasic/domain/voucher/VoucherType.java
  src/main/java/devcourse/springbootbasic/dto/customer/CustomerCreateRequest.java
  src/main/java/devcourse/springbootbasic/dto/customer/CustomerFindResponse.java
  src/main/java/devcourse/springbootbasic/dto/customer/CustomerResponse.java
  src/main/java/devcourse/springbootbasic/dto/customer/CustomerUpdateBlacklistRequest.java
  src/main/java/devcourse/springbootbasic/dto/voucher/VoucherCreateRequest.java
  src/main/java/devcourse/springbootbasic/dto/voucher/VoucherFindResponse.java
  src/main/java/devcourse/springbootbasic/dto/voucher/VoucherResponse.java
  src/main/java/devcourse/springbootbasic/dto/voucher/VoucherUpdateDiscountValueRequest.java
  src/main/java/devcourse/springbootbasic/dto/wallet/VoucherAssignRequest.java
  src/main/java/devcourse/springbootbasic/dto/wallet/VoucherAssignResponse.java
  src/main/java/devcourse/springbootbasic/exception/CustomerErrorMessage.java
  src/main/java/devcourse/springbootbasic/exception/CustomerException.java
  src/main/java/devcourse/springbootbasic/exception/VoucherErrorMessage.java
  src/main/java/devcourse/springbootbasic/repository/customer/CsvCustomerRepository.java
  src/main/java/devcourse/springbootbasic/repository/customer/CustomerRepository.java
  src/main/java/devcourse/springbootbasic/repository/customer/InMemoryCustomerRepository.java
  src/main/java/devcourse/springbootbasic/repository/customer/JdbcCustomerRepository.java
  src/main/java/devcourse/springbootbasic/repository/voucher/CsvVoucherRepository.java
  src/main/java/devcourse/springbootbasic/repository/voucher/InMemoryVoucherRepository.java
  src/main/java/devcourse/springbootbasic/repository/voucher/JdbcVoucherRepository.java
  src/main/java/devcourse/springbootbasic/repository/voucher/VoucherRepository.java
  src/main/java/devcourse/springbootbasic/service/CustomerService.java
  src/main/java/devcourse/springbootbasic/service/VoucherService.java
  src/main/java/devcourse/springbootbasic/service/WalletService.java
  src/main/java/devcourse/springbootbasic/util/CsvFileHandler.java
  src/main/java/devcourse/springbootbasic/util/UUIDUtil.java
  src/main/resources/application.yaml
  src/main/resources/schema.sql
  src/test/java/devcourse/springbootbasic/JdbcRepositoryTest.java
  src/test/java/devcourse/springbootbasic/TestDataFactory.java
  src/test/java/devcourse/springbootbasic/commandline/function/FunctionTest.java
  src/test/java/devcourse/springbootbasic/domain/customer/CustomerTest.java
  src/test/java/devcourse/springbootbasic/domain/voucher/VoucherTest.java
  src/test/java/devcourse/springbootbasic/domain/voucher/VoucherTypeTest.java
  src/test/java/devcourse/springbootbasic/repository/customer/InMemoryCustomerRepositoryTest.java
  src/test/java/devcourse/springbootbasic/repository/customer/JdbcCustomerRepositoryTest.java
  src/test/java/devcourse/springbootbasic/repository/voucher/InMemoryVoucherRepositoryTest.java
  src/test/java/devcourse/springbootbasic/repository/voucher/JdbcVoucherRepositoryTest.java
  src/test/java/devcourse/springbootbasic/service/CustomerServiceTest.java
  src/test/java/devcourse/springbootbasic/service/VoucherServiceTest.java
  src/test/java/devcourse/springbootbasic/service/WalletServiceTest.java
  src/test/java/devcourse/springbootbasic/util/CsvFileHandlerTest.java
  src/test/java/devcourse/springbootbasic/util/UUIDUtilTest.java
  src/test/resources/application.yaml
  src/test/resources/schema.sql
Labels: 🔥 매운맛, Team-Dozzi

#938 [5기 - 손가현] SpringBoot Part2 Weekly Mission 제출합니다.
  .gitignore
  build.gradle
  logs/access-2023-10-17.log
  logs/access.log
  src/main/java/com/prgrms/voucher_manage/console/ConsoleManager.java
  src/main/java/com/prgrms/voucher_manage/console/ConsoleMessage.java
  src/main/java/com/prgrms/voucher_manage/console/InputUtil.java
  src/main/java/com/prgrms/voucher_manage/console/MenuType.java
  src/main/java/com/prgrms/voucher_manage/console/OutputUtil.java
  src/main/java/com/prgrms/voucher_manage/console/io/IOManager.java
  src/main/java/com/prgrms/voucher_manage/console/io/InputUtil.java
  src/main/java/com/prgrms/voucher_manage/console/io/OutputUtil.java
  src/main/java/com/prgrms/voucher_manage/domain/customer/controller/CustomerController.java
  src/main/java/com/prgrms/voucher_manage/domain/customer/dto/UpdateCustomerDto.java
  src/main/java/com/prgrms/voucher_manage/domain/customer/entity/Customer.java
  src/main/java/com/prgrms/voucher_manage/domain/customer/entity/CustomerType.java
  src/main/java/com/prgrms/voucher_manage/domain/customer/repository/CustomerRepository.java
  src/main/java/com/prgrms/voucher_manage/domain/customer/repository/JdbcCustomerRepository.java
  src/main/java/com/prgrms/voucher_manage/domain/customer/service/CustomerService.java
  src/main/java/com/prgrms/voucher_manage/domain/voucher/controller/VoucherController.java
  src/main/java/com/prgrms/voucher_manage/domain/voucher/dto/UpdateVoucherDto.java
  src/main/java/com/prgrms/voucher_manage/domain/voucher/entity/FixedAmountVoucher.java
  src/main/java/com/prgrms/voucher_manage/domain/voucher/entity/PercentDiscountVoucher.java
  src/main/java/com/prgrms/voucher_manage/domain/voucher/entity/Voucher.java
  src/main/java/com/prgrms/voucher_manage/domain/voucher/entity/VoucherType.java
  src/main/java/com/prgrms/voucher_manage/domain/voucher/repository/FileVoucherRepository.java
  src/main/java/com/prgrms/voucher_manage/domain/voucher/repository/JdbcVoucherRepository.java
  src/main/java/com/prgrms/voucher_manage/domain/voucher/repository/MemoryVoucherRepository.java
  src/main/java/com/prgrms/voucher_manage/domain/voucher/repository/VoucherRepository.java
  src/main/java/com/prgrms/voucher_manage/domain/voucher/service/VoucherService.java
  src/main/java/com/prgrms/voucher_manage/domain/wallet/controller/WalletController.java
  src/main/java/com/prgrms/voucher_manage/domain/wallet/entity/Wallet.java
  src/main/java/com/prgrms/voucher_manage/domain/wallet/repository/JdbcWalletRepository.java
  src/main/java/com/prgrms/voucher_manage/domain/wallet/repository/WalletRepository.java
  src/main/java/com/prgrms/voucher_manage/domain/wallet/service/WalletService.java
  src/main/java/com/prgrms/voucher_manage/exception/ErrorMessage.java
  src/main/java/com/prgrms/voucher_manage/exception/InvalidInputException.java
  src/main/java/com/prgrms/voucher_manage/file/CustomerFileManager.java
  src/main/java/com/prgrms/voucher_manage/file/VoucherFileManager.java
  src/main/resources/application.yml
  src/main/resources/customer_blacklist.csv
  src/main/resources/voucher.csv
  src/test/java/com/prgrms/voucher_manage/domain/customer/repository/JdbcCustomerRepositoryTest.java
  src/test/java/com/prgrms/voucher_manage/domain/voucher/repository/JdbcVoucherRepositoryTest.java
  src/test/java/com/prgrms/voucher_manage/domain/voucher/repository/MemoryVoucherRepositoryTest.java
  src/test/java/com/prgrms/voucher_manage/domain/wallet/repository/JdbcWalletRepositoryTest.java
  src/test/resources/application.yml
  src/test/resources/schema.sql
Labels: 🔥 매운맛, Team-Hoon

#921 [5기 - 이수진] SpringBoot Part2 Weekly Mission 제출합니다.
  .gitignore
  build.gradle
  logs/log
  src/main/java/com/prgrms/vouchermanagement/core/customer/controller/CustomerController.java
  src/main/java/com/prgrms/vouchermanagement/core/customer/controller/request/CustomerCreateRequest.java
  src/main/java/com/prgrms/vouchermanagement/core/customer/controller/response/CustomerResponse.java
  src/main/java/com/prgrms/vouchermanagement/core/customer/controller/response/CustomersResponse.java
  src/main/java/com/prgrms/vouchermanagement/core/customer/domain/Customer.java
  src/main/java/com/prgrms/vouchermanagement/core/customer/dto/CustomerDto.java
  src/main/java/com/prgrms/vouchermanagement/core/customer/repository/CustomerRepository.java
  src/main/java/com/prgrms/vouchermanagement/core/customer/repository/jdbc/JdbcCustomerRepository.java
  src/main/java/com/prgrms/vouchermanagement/core/customer/service/CustomerService.java
  src/main/java/com/prgrms/vouchermanagement/core/customer/utils/mapper/Mapper.java
  src/main/java/com/prgrms/vouchermanagement/core/voucher/controller/VoucherController.java
  src/main/java/com/prgrms/vouchermanagement/core/voucher/controller/request/VoucherCreateRequest.java
  src/main/java/com/prgrms/vouchermanagement/core/voucher/controller/response/VoucherResponse.java
  src/main/java/com/prgrms/vouchermanagement/core/voucher/controller/response/VouchersResponse.java
  src/main/java/com/prgrms/vouchermanagement/core/voucher/domain/Voucher.java
  src/main/java/com/prgrms/vouchermanagement/core/voucher/domain/VoucherType.java
  src/main/java/com/prgrms/vouchermanagement/core/voucher/dto/VoucherDto.java
  src/main/java/com/prgrms/vouchermanagement/core/voucher/repository/VoucherRepository.java
  src/main/java/com/prgrms/vouchermanagement/core/voucher/repository/file/FileRepository.java
  src/main/java/com/prgrms/vouchermanagement/core/voucher/repository/file/FileStorage.java
  src/main/java/com/prgrms/vouchermanagement/core/voucher/repository/file/Voucher.json
  src/main/java/com/prgrms/vouchermanagement/core/voucher/repository/file/VoucherVO.java
  src/main/java/com/prgrms/vouchermanagement/core/voucher/repository/jdbc/JdbcVoucherRepository.java
  src/main/java/com/prgrms/vouchermanagement/core/voucher/repository/memory/MemoryVoucherRepository.java
  src/main/java/com/prgrms/vouchermanagement/core/voucher/service/VoucherService.java
  src/main/java/com/prgrms/vouchermanagement/core/voucher/utils/PropertiesUtil.java
  src/main/java/com/prgrms/vouchermanagement/core/voucher/utils/mapper/Mapper.java
  src/main/java/com/prgrms/vouchermanagement/core/wallet/domain/Wallet.java
  src/main/java/com/prgrms/vouchermanagement/core/wallet/dto/WalletDto.java
  src/main/java/com/prgrms/vouchermanagement/core/wallet/repository/WalletRepository.java
  src/main/java/com/prgrms/vouchermanagement/core/wallet/repository/jdbc/JdbcWalletRepository.java
  src/main/java/com/prgrms/vouchermanagement/core/wallet/service/WalletService.java
  src/main/java/com/prgrms/vouchermanagement/infra/InfraManager.java
  src/main/java/com/prgrms/vouchermanagement/infra/input/BufferedReaderImpl.java
  src/main/java/com/prgrms/vouchermanagement/infra/input/InputProvider.java
  src/main/java/com/prgrms/vouchermanagement/infra/output/OutputImpl.java
  src/main/java/com/prgrms/vouchermanagement/infra/output/OutputProvider.java
  src/main/resources/application-common.yml
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/main/resources/sql/customer-init.sql
  src/main/resources/sql/voucher-init.sql
  src/main/resources/sql/wallet-init.sql
  src/test/java/com/prgrms/vouchermanagement/VouchermanagementApplicationTests.java
  src/test/java/com/prgrms/vouchermanagement/core/customer/repository/jdbc/JdbcCustomerRepositoryTest.java
  src/test/java/com/prgrms/vouchermanagement/core/customer/service/CustomerServiceIntegrationTest.java
  src/test/java/com/prgrms/vouchermanagement/core/customer/service/CustomerServiceTest.java
  src/test/java/com/prgrms/vouchermanagement/core/voucher/domain/VoucherTest.java
  src/test/java/com/prgrms/vouchermanagement/core/voucher/repository/file/FileStorageTest.java
  src/test/java/com/prgrms/vouchermanagement/core/voucher/repository/jdbc/JdbcVoucherRepositoryTest.java
  src/test/java/com/prgrms/vouchermanagement/core/voucher/repository/memory/MemoryVoucherRepositoryTest.java
  src/test/java/com/prgrms/vouchermanagement/core/wallet/repository/jdbc/JdbcWalletRepositoryTest.java
  src/test/java/com/prgrms/vouchermanagement/core/wallet/service/WalletServiceIntegrationTest.java
Labels: 🔥 매운맛, Team-Hoon

#950 [5기 김대휘] SpringBoot Part3 Weekly Mission 제출합니다.
  build.gradle
  src/main/java/com/programmers/vouchermanagement/controller/rest/ApiEndpoints.java
  src/main/java/com/programmers/vouchermanagement/controller/rest/RestCustomerController.java
  src/main/java/com/programmers/vouchermanagement/controller/rest/RestVoucherController.java
  src/main/java/com/programmers/vouchermanagement/controller/web/CustomerController.java
  src/main/java/com/programmers/vouchermanagement/controller/web/VoucherController.java
  src/main/java/com/programmers/vouchermanagement/controller/web/WalletController.java
  src/main/java/com/programmers/vouchermanagement/domain/customer/Customer.java
  src/main/java/com/programmers/vouchermanagement/domain/voucher/FixedAmountVoucher.java
  src/main/java/com/programmers/vouchermanagement/domain/voucher/PercentDiscountVoucher.java
  src/main/java/com/programmers/vouchermanagement/domain/voucher/Voucher.java
  src/main/java/com/programmers/vouchermanagement/domain/voucher/VoucherFactory.java
  src/main/java/com/programmers/vouchermanagement/domain/wallet/Wallet.java
  src/main/java/com/programmers/vouchermanagement/dto/CustomerDto.java
  src/main/java/com/programmers/vouchermanagement/dto/VoucherDto.java
  src/main/java/com/programmers/vouchermanagement/exception/RestExceptionHandler.java
  src/main/java/com/programmers/vouchermanagement/exception/WebExceptionHandler.java
  src/main/java/com/programmers/vouchermanagement/repository/customer/FileCustomerRepository.java
  src/main/java/com/programmers/vouchermanagement/repository/customer/JdbcCustomerRepository.java
  src/main/java/com/programmers/vouchermanagement/repository/voucher/FileVoucherRepository.java
  src/main/java/com/programmers/vouchermanagement/repository/voucher/JdbcVoucherRepository.java
  src/main/java/com/programmers/vouchermanagement/repository/voucher/VoucherRepository.java
  src/main/java/com/programmers/vouchermanagement/repository/wallet/JdbcWalletRepository.java
  src/main/java/com/programmers/vouchermanagement/repository/wallet/WalletRepository.java
  src/main/java/com/programmers/vouchermanagement/service/CustomerService.java
  src/main/java/com/programmers/vouchermanagement/service/VoucherService.java
  src/main/java/com/programmers/vouchermanagement/service/WalletService.java
  src/main/java/com/programmers/vouchermanagement/utils/CsvFileUtil.java
  src/main/java/com/programmers/vouchermanagement/view/Console.java
  src/main/resources/application.yml
  src/main/resources/database/docker-compose.yml
  src/main/resources/database/schema.sql
  src/main/resources/templates/customer/add_customer_form.html
  src/main/resources/templates/customer/customer_detail.html
  src/main/resources/templates/error.html
  src/main/resources/templates/index.html
  src/main/resources/templates/voucher/add_voucher_form.html
  src/main/resources/templates/voucher/voucher_detail.html
  src/main/resources/templates/wallet/add_wallet_form.html
  src/test/java/com/programmers/vouchermanagement/service/CustomerServiceTest.java
  src/test/java/com/programmers/vouchermanagement/service/VoucherServiceTest.java
  src/test/java/com/programmers/vouchermanagement/service/WalletServiceTest.java
  src/test/resources/schema.sql
Labels: 🔥 매운맛, Team-BingBong

#959 [5기 김별이] SpringBoot Part3 Weekly Mission 제출합니다
  build.gradle
  docker-compose.yml
  src/main/java/com/prgrms/springbasic/common/HomeController.java
  src/main/java/com/prgrms/springbasic/common/exception/DuplicateResourceException.java
  src/main/java/com/prgrms/springbasic/common/exception/ErrorResponse.java
  src/main/java/com/prgrms/springbasic/common/exception/InvalidValueException.java
  src/main/java/com/prgrms/springbasic/common/exception/ResourceNotFoundException.java
  src/main/java/com/prgrms/springbasic/common/handler/ApiExceptionHandler.java
  src/main/java/com/prgrms/springbasic/common/handler/WebExceptionHandler.java
  src/main/java/com/prgrms/springbasic/console/CommandType.java
  src/main/java/com/prgrms/springbasic/console/MenuHandler.java
  src/main/java/com/prgrms/springbasic/console/MenuType.java
  src/main/java/com/prgrms/springbasic/console/VoucherRunner.java
  src/main/java/com/prgrms/springbasic/domain/customer/controller/CustomerApiController.java
  src/main/java/com/prgrms/springbasic/domain/customer/controller/CustomerWebController.java
  src/main/java/com/prgrms/springbasic/domain/customer/repository/CustomerJdbcRepository.java
  src/main/java/com/prgrms/springbasic/domain/customer/repository/CustomerRepository.java
  src/main/java/com/prgrms/springbasic/domain/customer/service/CustomerService.java
  src/main/java/com/prgrms/springbasic/domain/voucher/controller/VoucherApiController.java
  src/main/java/com/prgrms/springbasic/domain/voucher/controller/VoucherWebController.java
  src/main/java/com/prgrms/springbasic/domain/voucher/dto/UpdateVoucherRequest.java
  src/main/java/com/prgrms/springbasic/domain/voucher/dto/VoucherResponse.java
  src/main/java/com/prgrms/springbasic/domain/voucher/entity/DiscountType.java
  src/main/java/com/prgrms/springbasic/domain/voucher/entity/FixedAmountVoucher.java
  src/main/java/com/prgrms/springbasic/domain/voucher/entity/PercentDiscountVoucher.java
  src/main/java/com/prgrms/springbasic/domain/voucher/entity/Voucher.java
  src/main/java/com/prgrms/springbasic/domain/voucher/repository/FileVoucherRepository.java
  src/main/java/com/prgrms/springbasic/domain/voucher/repository/JdbcVoucherRepository.java
  src/main/java/com/prgrms/springbasic/domain/voucher/repository/MemoryVoucherRepository.java
  src/main/java/com/prgrms/springbasic/domain/voucher/repository/VoucherRepository.java
  src/main/java/com/prgrms/springbasic/domain/voucher/service/VoucherService.java
  src/main/java/com/prgrms/springbasic/domain/wallet/dto/WalletRequest.java
  src/main/java/com/prgrms/springbasic/domain/wallet/dto/WalletResponse.java
  src/main/java/com/prgrms/springbasic/domain/wallet/entity/Wallet.java
  src/main/java/com/prgrms/springbasic/domain/wallet/repository/JdbcWalletRepository.java
  src/main/java/com/prgrms/springbasic/domain/wallet/service/WalletService.java
  src/main/java/com/prgrms/springbasic/io/Console.java
  src/main/java/com/prgrms/springbasic/io/Input.java
  src/main/resources/application.yml
  src/main/resources/schema.sql
  src/main/resources/static/css/bootstrap.min.css
  src/main/resources/templates/customer/create_form.html
  src/main/resources/templates/customer/list.html
  src/main/resources/templates/error.html
  src/main/resources/templates/index.html
  src/main/resources/templates/voucher/create_form.html
  src/main/resources/templates/voucher/detail.html
  src/main/resources/templates/voucher/list.html
  src/main/resources/templates/voucher/update_form.html
  src/test/java/com/prgrms/springbasic/domain/customer/service/CustomerServiceTest.java
  src/test/java/com/prgrms/springbasic/domain/voucher/entity/VoucherTest.java
  src/test/java/com/prgrms/springbasic/domain/voucher/repository/MemoryVoucherRepositoryTest.java
  src/test/java/com/prgrms/springbasic/domain/voucher/service/VoucherServiceTest.java
  src/test/java/com/prgrms/springbasic/domain/wallet/service/WalletServiceTest.java
Labels: 🔥 매운맛, Team-BingBong

#949 [5기 - 남은찬] SpringBoot Part3 Weekly Mission 제출합니다.
  build.gradle
  src/main/java/study/dev/spring/common/dto/ErrorResponse.java
  src/main/java/study/dev/spring/common/dto/ListWrapper.java
  src/main/java/study/dev/spring/common/exception/handler/ApiExceptionHandler.java
  src/main/java/study/dev/spring/common/exception/handler/WebExceptionHandler.java
  src/main/java/study/dev/spring/customer/application/dto/VoucherIdRequest.java
  src/main/java/study/dev/spring/customer/infrastructure/JdbcCustomerRepository.java
  src/main/java/study/dev/spring/customer/presentation/ApiCustomerController.java
  src/main/java/study/dev/spring/customer/presentation/WebCustomerController.java
  src/main/java/study/dev/spring/voucher/application/VoucherService.java
  src/main/java/study/dev/spring/voucher/application/dto/VoucherInfo.java
  src/main/java/study/dev/spring/voucher/application/dto/VoucherMapper.java
  src/main/java/study/dev/spring/voucher/infrastructure/JdbcVoucherRepository.java
  src/main/java/study/dev/spring/voucher/presentation/ApiVoucherController.java
  src/main/java/study/dev/spring/voucher/presentation/ConsoleVoucherController.java
  src/main/java/study/dev/spring/voucher/presentation/WebVoucherController.java
  src/main/java/study/dev/spring/voucher/presentation/utils/VoucherIoProcessor.java
  src/main/java/study/dev/spring/wallet/application/dto/CreateWalletRequest.java
  src/main/java/study/dev/spring/wallet/application/dto/DeleteWalletRequest.java
  src/main/java/study/dev/spring/wallet/presentation/ApiWalletController.java
  src/main/java/study/dev/spring/wallet/presentation/WebWalletController.java
  src/main/resources/templates/customers/customer_info.html
  src/main/resources/templates/error/error.html
  src/main/resources/templates/vouchers/new_voucher.html
  src/main/resources/templates/vouchers/voucher_info.html
  src/main/resources/templates/wallets/new_wallet.html
  src/main/resources/templates/wallets/remove_wallet.html
  src/test/java/study/dev/spring/voucher/application/VoucherServiceTest.java
  src/test/java/study/dev/spring/voucher/fixture/VoucherFixture.java
  src/test/java/study/dev/spring/voucher/stub/VoucherIoProcessorStub.java
  src/test/java/study/dev/spring/voucher/stub/VoucherServiceStub.java
Labels: 🔥 매운맛, Team-Hoon

#961 [5기 - 이유정] SpringBoot Part3 Weekly Mission 제출합니다.
  README.md
  build.gradle
  src/main/java/com/programmers/vouchermanagement/VoucherManagementController.java
  src/main/java/com/programmers/vouchermanagement/customer/presentation/CustomerViewExceptionController.java
  src/main/java/com/programmers/vouchermanagement/customer/repository/FileCustomerRepository.java
  src/main/java/com/programmers/vouchermanagement/customer/repository/JdbcCustomerRepository.java
  src/main/java/com/programmers/vouchermanagement/global/exception/CommandNotFoundException.java
  src/main/java/com/programmers/vouchermanagement/global/exception/FileIOException.java
  src/main/java/com/programmers/vouchermanagement/global/utils/Command.java
  src/main/java/com/programmers/vouchermanagement/global/utils/ConsoleInputManager.java
  src/main/java/com/programmers/vouchermanagement/global/utils/ConsoleOutputManager.java
  src/main/java/com/programmers/vouchermanagement/global/utils/CsvFileIoManager.java
  src/main/java/com/programmers/vouchermanagement/global/utils/TimeUtil.java
  src/main/java/com/programmers/vouchermanagement/global/utils/UuidUtil.java
  src/main/java/com/programmers/vouchermanagement/voucher/application/VoucherService.java
  src/main/java/com/programmers/vouchermanagement/voucher/domain/Voucher.java
  src/main/java/com/programmers/vouchermanagement/voucher/dto/VoucherResponseDto.java
  src/main/java/com/programmers/vouchermanagement/voucher/mapper/VoucherMapper.java
  src/main/java/com/programmers/vouchermanagement/voucher/presentation/VoucherApiController.java
  src/main/java/com/programmers/vouchermanagement/voucher/presentation/VoucherApiExceptionController.java
  src/main/java/com/programmers/vouchermanagement/voucher/presentation/VoucherViewController.java
  src/main/java/com/programmers/vouchermanagement/voucher/presentation/VoucherViewExceptionController.java
  src/main/java/com/programmers/vouchermanagement/voucher/repository/FileVoucherRepository.java
  src/main/java/com/programmers/vouchermanagement/voucher/repository/JdbcVoucherRepository.java
  src/main/java/com/programmers/vouchermanagement/voucher/repository/MemoryVoucherRepository.java
  src/main/java/com/programmers/vouchermanagement/voucher/repository/VoucherRepository.java
  src/main/java/com/programmers/vouchermanagement/wallet/application/WalletService.java
  src/main/java/com/programmers/vouchermanagement/wallet/dto/WalletResponseDto.java
  src/main/java/com/programmers/vouchermanagement/wallet/presentation/WalletViewController.java
  src/main/java/com/programmers/vouchermanagement/wallet/repository/JdbcWalletRepository.java
  src/main/java/com/programmers/vouchermanagement/wallet/repository/WalletRepository.java
  src/main/resources/schema.sql
  src/main/resources/templates/exception-detail.html
  src/main/resources/templates/voucher/voucher-detail.html
  src/main/resources/templates/voucher/voucher-form.html
  src/main/resources/templates/voucher/voucher-list.html
  src/main/resources/templates/wallet/wallet-customers.html
  src/main/resources/templates/wallet/wallet-form.html
  src/main/resources/templates/wallet/wallet-list.html
  src/main/resources/templates/wallet/wallet-vouchers.html
  src/test/java/com/programmers/vouchermanagement/voucher/JdbcVoucherRepositoryTest.java
  src/test/java/com/programmers/vouchermanagement/voucher/VoucherServiceTest.java
  src/test/java/com/programmers/vouchermanagement/wallet/JdbcWalletRepositoryTest.java
  src/test/java/com/programmers/vouchermanagement/wallet/WalletServiceTest.java
Labels: 🔥 매운맛, Team-Dozzi

#957 [5기 - 권효승] SpringBoot Part3 Weekly Mission 제출합니다.
  README.md
  build.gradle
  src/main/java/devcourse/springbootbasic/commandline/CommandLineExecutor.java
  src/main/java/devcourse/springbootbasic/commandline/function/FunctionHandler.java
  src/main/java/devcourse/springbootbasic/config/AppConfig.java
  src/main/java/devcourse/springbootbasic/config/advice/ErrorMessage.java
  src/main/java/devcourse/springbootbasic/config/advice/ExceptionControllerAdvice.java
  src/main/java/devcourse/springbootbasic/controller/VoucherController.java
  src/main/java/devcourse/springbootbasic/controller/VoucherViewController.java
  src/main/java/devcourse/springbootbasic/domain/voucher/Voucher.java
  src/main/java/devcourse/springbootbasic/dto/voucher/VoucherCreateRequest.java
  src/main/java/devcourse/springbootbasic/dto/voucher/VoucherFindResponse.java
  src/main/java/devcourse/springbootbasic/dto/voucher/VoucherUpdateDiscountValueRequest.java
  src/main/java/devcourse/springbootbasic/dto/wallet/VoucherAssignRequest.java
  src/main/java/devcourse/springbootbasic/repository/customer/JdbcCustomerRepository.java
  src/main/java/devcourse/springbootbasic/repository/voucher/CsvVoucherRepository.java
  src/main/java/devcourse/springbootbasic/repository/voucher/InMemoryVoucherRepository.java
  src/main/java/devcourse/springbootbasic/repository/voucher/JdbcVoucherRepository.java
  src/main/java/devcourse/springbootbasic/repository/voucher/VoucherRepository.java
  src/main/java/devcourse/springbootbasic/service/VoucherService.java
  src/main/java/devcourse/springbootbasic/service/WalletService.java
  src/main/resources/application.yaml
  src/main/resources/logback.xml
  src/main/resources/schema.sql
  src/main/resources/templates/voucher/voucher-detail.html
  src/main/resources/templates/voucher/voucher-form.html
  src/main/resources/templates/voucher/voucher-list.html
  src/test/java/devcourse/springbootbasic/TestDataFactory.java
  src/test/java/devcourse/springbootbasic/controller/VoucherControllerTest.java
  src/test/java/devcourse/springbootbasic/repository/voucher/InMemoryVoucherRepositoryTest.java
  src/test/java/devcourse/springbootbasic/repository/voucher/JdbcVoucherRepositoryTest.java
  src/test/java/devcourse/springbootbasic/service/VoucherServiceTest.java
  src/test/java/devcourse/springbootbasic/service/WalletServiceTest.java
  src/test/resources/application.yaml
  src/test/resources/schema.sql
Labels: 🔥 매운맛, Team-Dozzi

#958 [5기 - 김강훈] SpringBoot Part3 Weekly Mission 제출합니다.
  build.gradle
  src/main/java/com/weeklyMission/DemoApplication.java
  src/main/java/com/weeklyMission/HomeController.java
  src/main/java/com/weeklyMission/client/Client.java
  src/main/java/com/weeklyMission/client/VoucherType.java
  src/main/java/com/weeklyMission/exception/AlreadyExistsException.java
  src/main/java/com/weeklyMission/exception/ApiExceptionHandler.java
  src/main/java/com/weeklyMission/exception/ErrorResult.java
  src/main/java/com/weeklyMission/exception/ExceptionMessage.java
  src/main/java/com/weeklyMission/exception/NotFoundException.java
  src/main/java/com/weeklyMission/member/controller/MemberViewController.java
  src/main/java/com/weeklyMission/member/domain/Member.java
  src/main/java/com/weeklyMission/member/dto/MemberRequest.java
  src/main/java/com/weeklyMission/member/dto/MemberResponse.java
  src/main/java/com/weeklyMission/member/repository/DBMemberRepository.java
  src/main/java/com/weeklyMission/member/repository/FileMemberRepository.java
  src/main/java/com/weeklyMission/member/repository/MemberRepository.java
  src/main/java/com/weeklyMission/member/service/MemberService.java
  src/main/java/com/weeklyMission/voucher/controller/VoucherApiController.java
  src/main/java/com/weeklyMission/voucher/controller/VoucherViewController.java
  src/main/java/com/weeklyMission/voucher/domain/FixedAmountVoucher.java
  src/main/java/com/weeklyMission/voucher/domain/PercentDiscountVoucher.java
  src/main/java/com/weeklyMission/voucher/dto/VoucherRequest.java
  src/main/java/com/weeklyMission/voucher/repository/DBVoucherRepository.java
  src/main/java/com/weeklyMission/voucher/repository/FileVoucherRepository.java
  src/main/java/com/weeklyMission/voucher/repository/MemoryVoucherRepository.java
  src/main/java/com/weeklyMission/voucher/repository/VoucherRepository.java
  src/main/java/com/weeklyMission/voucher/service/VoucherService.java
  src/main/java/com/weeklyMission/wallet/controller/WalletController.java
  src/main/java/com/weeklyMission/wallet/controller/WalletViewController.java
  src/main/java/com/weeklyMission/wallet/dto/WalletRequest.java
  src/main/java/com/weeklyMission/wallet/dto/WalletResponse.java
  src/main/java/com/weeklyMission/wallet/repository/DBWalletRepository.java
  src/main/java/com/weeklyMission/wallet/repository/WalletRepository.java
  src/main/java/com/weeklyMission/wallet/service/WalletFacade.java
  src/main/java/com/weeklyMission/wallet/service/WalletService.java
  src/main/resources/application.yaml
  src/main/resources/errors.properties
  src/main/resources/templates/error.html
  src/main/resources/templates/home.html
  src/main/resources/templates/members/createForm.html
  src/main/resources/templates/members/memberInfo.html
  src/main/resources/templates/members/memberList.html
  src/main/resources/templates/members/members_voucherDetail.html
  src/main/resources/templates/members/members_voucherList.html
  src/main/resources/templates/vouchers/createForm.html
  src/main/resources/templates/vouchers/voucherInfo.html
  src/main/resources/templates/vouchers/voucherList.html
  src/main/resources/templates/vouchers/vouchers_memberList.html
  src/main/resources/templates/wallet/createForm.html
  src/test/java/com/weeklyMission/member/repository/FileMemberRepositoryTest.java
  src/test/java/com/weeklyMission/voucher/domain/FixedAmountVoucherTest.java
  src/test/java/com/weeklyMission/voucher/domain/PercentDiscountVoucherTest.java
  src/test/java/com/weeklyMission/voucher/repository/FileVoucherRepositoryTest.java
  src/test/java/com/weeklyMission/voucher/repository/MemoryVoucherRepositoryTest.java
  src/test/java/com/weeklyMission/voucher/service/VoucherServiceTest.java
Labels: 🔥 매운맛, Team-Hoon
